// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sentry

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-sentry/sdk/go/sentry/internal"
)

// Sentry Issue Alert data source. See the [Sentry documentation](https://docs.sentry.io/api/alerts/retrieve-an-issue-alert-rule-for-a-project/) for more information.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-sentry/sdk/go/sentry"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Retrieve an Issue Alert
//			_, err := sentry.LookupSentryIssueAlert(ctx, &sentry.LookupSentryIssueAlertArgs{
//				Organization: "my-organization",
//				Project:      "my-project",
//				Id:           "42",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupSentryIssueAlert(ctx *pulumi.Context, args *LookupSentryIssueAlertArgs, opts ...pulumi.InvokeOption) (*LookupSentryIssueAlertResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSentryIssueAlertResult
	err := ctx.Invoke("sentry:index/getSentryIssueAlert:getSentryIssueAlert", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSentryIssueAlert.
type LookupSentryIssueAlertArgs struct {
	// The ID of this resource.
	Id string `pulumi:"id"`
	// The organization the resource belongs to.
	Organization string `pulumi:"organization"`
	// The project the resource belongs to.
	Project string `pulumi:"project"`
}

// A collection of values returned by getSentryIssueAlert.
type LookupSentryIssueAlertResult struct {
	// Trigger actions when an event is captured by Sentry and `any` or `all` of the specified conditions happen.
	ActionMatch string `pulumi:"actionMatch"`
	// List of actions. In JSON string format.
	Actions string `pulumi:"actions"`
	// A list of actions that take place when all required conditions and filters for the rule are met.
	ActionsV2s []GetSentryIssueAlertActionsV2 `pulumi:"actionsV2s"`
	// List of conditions. In JSON string format.
	Conditions string `pulumi:"conditions"`
	// A list of triggers that determine when the rule fires.
	ConditionsV2s []GetSentryIssueAlertConditionsV2 `pulumi:"conditionsV2s"`
	// Perform issue alert in a specific environment.
	Environment string `pulumi:"environment"`
	// A string determining which filters need to be true before any actions take place. Required when a value is provided for `filters`.
	FilterMatch string `pulumi:"filterMatch"`
	// A list of filters that determine if a rule fires after the necessary conditions have been met. In JSON string format.
	Filters string `pulumi:"filters"`
	// A list of filters that determine if a rule fires after the necessary conditions have been met.
	FiltersV2s []GetSentryIssueAlertFiltersV2 `pulumi:"filtersV2s"`
	// Perform actions at most once every `X` minutes for this issue.
	Frequency int `pulumi:"frequency"`
	// The ID of this resource.
	Id string `pulumi:"id"`
	// The issue alert name.
	Name string `pulumi:"name"`
	// The organization the resource belongs to.
	Organization string `pulumi:"organization"`
	// The ID of the team or user that owns the rule.
	Owner string `pulumi:"owner"`
	// The project the resource belongs to.
	Project string `pulumi:"project"`
}

func LookupSentryIssueAlertOutput(ctx *pulumi.Context, args LookupSentryIssueAlertOutputArgs, opts ...pulumi.InvokeOption) LookupSentryIssueAlertResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSentryIssueAlertResultOutput, error) {
			args := v.(LookupSentryIssueAlertArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv LookupSentryIssueAlertResult
			secret, err := ctx.InvokePackageRaw("sentry:index/getSentryIssueAlert:getSentryIssueAlert", args, &rv, "", opts...)
			if err != nil {
				return LookupSentryIssueAlertResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(LookupSentryIssueAlertResultOutput)
			if secret {
				return pulumi.ToSecret(output).(LookupSentryIssueAlertResultOutput), nil
			}
			return output, nil
		}).(LookupSentryIssueAlertResultOutput)
}

// A collection of arguments for invoking getSentryIssueAlert.
type LookupSentryIssueAlertOutputArgs struct {
	// The ID of this resource.
	Id pulumi.StringInput `pulumi:"id"`
	// The organization the resource belongs to.
	Organization pulumi.StringInput `pulumi:"organization"`
	// The project the resource belongs to.
	Project pulumi.StringInput `pulumi:"project"`
}

func (LookupSentryIssueAlertOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSentryIssueAlertArgs)(nil)).Elem()
}

// A collection of values returned by getSentryIssueAlert.
type LookupSentryIssueAlertResultOutput struct{ *pulumi.OutputState }

func (LookupSentryIssueAlertResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSentryIssueAlertResult)(nil)).Elem()
}

func (o LookupSentryIssueAlertResultOutput) ToLookupSentryIssueAlertResultOutput() LookupSentryIssueAlertResultOutput {
	return o
}

func (o LookupSentryIssueAlertResultOutput) ToLookupSentryIssueAlertResultOutputWithContext(ctx context.Context) LookupSentryIssueAlertResultOutput {
	return o
}

// Trigger actions when an event is captured by Sentry and `any` or `all` of the specified conditions happen.
func (o LookupSentryIssueAlertResultOutput) ActionMatch() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryIssueAlertResult) string { return v.ActionMatch }).(pulumi.StringOutput)
}

// List of actions. In JSON string format.
func (o LookupSentryIssueAlertResultOutput) Actions() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryIssueAlertResult) string { return v.Actions }).(pulumi.StringOutput)
}

// A list of actions that take place when all required conditions and filters for the rule are met.
func (o LookupSentryIssueAlertResultOutput) ActionsV2s() GetSentryIssueAlertActionsV2ArrayOutput {
	return o.ApplyT(func(v LookupSentryIssueAlertResult) []GetSentryIssueAlertActionsV2 { return v.ActionsV2s }).(GetSentryIssueAlertActionsV2ArrayOutput)
}

// List of conditions. In JSON string format.
func (o LookupSentryIssueAlertResultOutput) Conditions() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryIssueAlertResult) string { return v.Conditions }).(pulumi.StringOutput)
}

// A list of triggers that determine when the rule fires.
func (o LookupSentryIssueAlertResultOutput) ConditionsV2s() GetSentryIssueAlertConditionsV2ArrayOutput {
	return o.ApplyT(func(v LookupSentryIssueAlertResult) []GetSentryIssueAlertConditionsV2 { return v.ConditionsV2s }).(GetSentryIssueAlertConditionsV2ArrayOutput)
}

// Perform issue alert in a specific environment.
func (o LookupSentryIssueAlertResultOutput) Environment() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryIssueAlertResult) string { return v.Environment }).(pulumi.StringOutput)
}

// A string determining which filters need to be true before any actions take place. Required when a value is provided for `filters`.
func (o LookupSentryIssueAlertResultOutput) FilterMatch() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryIssueAlertResult) string { return v.FilterMatch }).(pulumi.StringOutput)
}

// A list of filters that determine if a rule fires after the necessary conditions have been met. In JSON string format.
func (o LookupSentryIssueAlertResultOutput) Filters() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryIssueAlertResult) string { return v.Filters }).(pulumi.StringOutput)
}

// A list of filters that determine if a rule fires after the necessary conditions have been met.
func (o LookupSentryIssueAlertResultOutput) FiltersV2s() GetSentryIssueAlertFiltersV2ArrayOutput {
	return o.ApplyT(func(v LookupSentryIssueAlertResult) []GetSentryIssueAlertFiltersV2 { return v.FiltersV2s }).(GetSentryIssueAlertFiltersV2ArrayOutput)
}

// Perform actions at most once every `X` minutes for this issue.
func (o LookupSentryIssueAlertResultOutput) Frequency() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSentryIssueAlertResult) int { return v.Frequency }).(pulumi.IntOutput)
}

// The ID of this resource.
func (o LookupSentryIssueAlertResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryIssueAlertResult) string { return v.Id }).(pulumi.StringOutput)
}

// The issue alert name.
func (o LookupSentryIssueAlertResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryIssueAlertResult) string { return v.Name }).(pulumi.StringOutput)
}

// The organization the resource belongs to.
func (o LookupSentryIssueAlertResultOutput) Organization() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryIssueAlertResult) string { return v.Organization }).(pulumi.StringOutput)
}

// The ID of the team or user that owns the rule.
func (o LookupSentryIssueAlertResultOutput) Owner() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryIssueAlertResult) string { return v.Owner }).(pulumi.StringOutput)
}

// The project the resource belongs to.
func (o LookupSentryIssueAlertResultOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryIssueAlertResult) string { return v.Project }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSentryIssueAlertResultOutput{})
}
