// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sentry

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-sentry/sdk/go/sentry/internal"
)

// Retrieve a Project's Client Key.
func LookupSentryKey(ctx *pulumi.Context, args *LookupSentryKeyArgs, opts ...pulumi.InvokeOption) (*LookupSentryKeyResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSentryKeyResult
	err := ctx.Invoke("sentry:index/getSentryKey:getSentryKey", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSentryKey.
type LookupSentryKeyArgs struct {
	// Boolean flag indicating that we want the first key of the returned keys.
	First *bool `pulumi:"first"`
	// The ID of this resource.
	Id *string `pulumi:"id"`
	// The name of the client key.
	Name *string `pulumi:"name"`
	// The organization the resource belongs to.
	Organization string `pulumi:"organization"`
	// The project the resource belongs to.
	Project string `pulumi:"project"`
}

// A collection of values returned by getSentryKey.
type LookupSentryKeyResult struct {
	// This is a map of DSN values. The keys include `public`, `secret`, `csp`, `security`, `minidump`, `nel`, `unreal`, `cdn`, and `crons`.
	Dsn map[string]string `pulumi:"dsn"`
	// Security header endpoint for features like CSP and Expect-CT reports. **Deprecated** Use `dsn["csp"]` instead.
	//
	// Deprecated: This field is deprecated and will be removed in a future version. Use `dsn["csp"]` instead.
	DsnCsp string `pulumi:"dsnCsp"`
	// The DSN tells the SDK where to send the events to. **Deprecated** Use `dsn["public"]` instead.
	//
	// Deprecated: This field is deprecated and will be removed in a future version. Use `dsn["public"]` instead.
	DsnPublic string `pulumi:"dsnPublic"`
	// Deprecated DSN includes a secret which is no longer required by newer SDK versions. If you are unsure which to use, follow installation instructions for your language. **Deprecated** Use `dsn["secret"] instead.
	//
	// Deprecated: This field is deprecated and will be removed in a future version. Use `dsn["secret"]` instead.
	DsnSecret string `pulumi:"dsnSecret"`
	// Boolean flag indicating that we want the first key of the returned keys.
	First *bool `pulumi:"first"`
	// The ID of this resource.
	Id *string `pulumi:"id"`
	// The JavaScript loader script configuration.
	JavascriptLoaderScript GetSentryKeyJavascriptLoaderScript `pulumi:"javascriptLoaderScript"`
	// The name of the client key.
	Name *string `pulumi:"name"`
	// The organization the resource belongs to.
	Organization string `pulumi:"organization"`
	// The project the resource belongs to.
	Project string `pulumi:"project"`
	// The ID of the project that the key belongs to.
	ProjectId string `pulumi:"projectId"`
	// The public key.
	Public string `pulumi:"public"`
	// Number of events that can be reported within the rate limit window.
	RateLimitCount int `pulumi:"rateLimitCount"`
	// Length of time in seconds that will be considered when checking the rate limit.
	RateLimitWindow int `pulumi:"rateLimitWindow"`
	// The secret key.
	Secret string `pulumi:"secret"`
}

func LookupSentryKeyOutput(ctx *pulumi.Context, args LookupSentryKeyOutputArgs, opts ...pulumi.InvokeOption) LookupSentryKeyResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSentryKeyResultOutput, error) {
			args := v.(LookupSentryKeyArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv LookupSentryKeyResult
			secret, err := ctx.InvokePackageRaw("sentry:index/getSentryKey:getSentryKey", args, &rv, "", opts...)
			if err != nil {
				return LookupSentryKeyResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(LookupSentryKeyResultOutput)
			if secret {
				return pulumi.ToSecret(output).(LookupSentryKeyResultOutput), nil
			}
			return output, nil
		}).(LookupSentryKeyResultOutput)
}

// A collection of arguments for invoking getSentryKey.
type LookupSentryKeyOutputArgs struct {
	// Boolean flag indicating that we want the first key of the returned keys.
	First pulumi.BoolPtrInput `pulumi:"first"`
	// The ID of this resource.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// The name of the client key.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// The organization the resource belongs to.
	Organization pulumi.StringInput `pulumi:"organization"`
	// The project the resource belongs to.
	Project pulumi.StringInput `pulumi:"project"`
}

func (LookupSentryKeyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSentryKeyArgs)(nil)).Elem()
}

// A collection of values returned by getSentryKey.
type LookupSentryKeyResultOutput struct{ *pulumi.OutputState }

func (LookupSentryKeyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSentryKeyResult)(nil)).Elem()
}

func (o LookupSentryKeyResultOutput) ToLookupSentryKeyResultOutput() LookupSentryKeyResultOutput {
	return o
}

func (o LookupSentryKeyResultOutput) ToLookupSentryKeyResultOutputWithContext(ctx context.Context) LookupSentryKeyResultOutput {
	return o
}

// This is a map of DSN values. The keys include `public`, `secret`, `csp`, `security`, `minidump`, `nel`, `unreal`, `cdn`, and `crons`.
func (o LookupSentryKeyResultOutput) Dsn() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupSentryKeyResult) map[string]string { return v.Dsn }).(pulumi.StringMapOutput)
}

// Security header endpoint for features like CSP and Expect-CT reports. **Deprecated** Use `dsn["csp"]` instead.
//
// Deprecated: This field is deprecated and will be removed in a future version. Use `dsn["csp"]` instead.
func (o LookupSentryKeyResultOutput) DsnCsp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryKeyResult) string { return v.DsnCsp }).(pulumi.StringOutput)
}

// The DSN tells the SDK where to send the events to. **Deprecated** Use `dsn["public"]` instead.
//
// Deprecated: This field is deprecated and will be removed in a future version. Use `dsn["public"]` instead.
func (o LookupSentryKeyResultOutput) DsnPublic() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryKeyResult) string { return v.DsnPublic }).(pulumi.StringOutput)
}

// Deprecated DSN includes a secret which is no longer required by newer SDK versions. If you are unsure which to use, follow installation instructions for your language. **Deprecated** Use `dsn["secret"] instead.
//
// Deprecated: This field is deprecated and will be removed in a future version. Use `dsn["secret"]` instead.
func (o LookupSentryKeyResultOutput) DsnSecret() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryKeyResult) string { return v.DsnSecret }).(pulumi.StringOutput)
}

// Boolean flag indicating that we want the first key of the returned keys.
func (o LookupSentryKeyResultOutput) First() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupSentryKeyResult) *bool { return v.First }).(pulumi.BoolPtrOutput)
}

// The ID of this resource.
func (o LookupSentryKeyResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSentryKeyResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

// The JavaScript loader script configuration.
func (o LookupSentryKeyResultOutput) JavascriptLoaderScript() GetSentryKeyJavascriptLoaderScriptOutput {
	return o.ApplyT(func(v LookupSentryKeyResult) GetSentryKeyJavascriptLoaderScript { return v.JavascriptLoaderScript }).(GetSentryKeyJavascriptLoaderScriptOutput)
}

// The name of the client key.
func (o LookupSentryKeyResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSentryKeyResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// The organization the resource belongs to.
func (o LookupSentryKeyResultOutput) Organization() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryKeyResult) string { return v.Organization }).(pulumi.StringOutput)
}

// The project the resource belongs to.
func (o LookupSentryKeyResultOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryKeyResult) string { return v.Project }).(pulumi.StringOutput)
}

// The ID of the project that the key belongs to.
func (o LookupSentryKeyResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryKeyResult) string { return v.ProjectId }).(pulumi.StringOutput)
}

// The public key.
func (o LookupSentryKeyResultOutput) Public() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryKeyResult) string { return v.Public }).(pulumi.StringOutput)
}

// Number of events that can be reported within the rate limit window.
func (o LookupSentryKeyResultOutput) RateLimitCount() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSentryKeyResult) int { return v.RateLimitCount }).(pulumi.IntOutput)
}

// Length of time in seconds that will be considered when checking the rate limit.
func (o LookupSentryKeyResultOutput) RateLimitWindow() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSentryKeyResult) int { return v.RateLimitWindow }).(pulumi.IntOutput)
}

// The secret key.
func (o LookupSentryKeyResultOutput) Secret() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryKeyResult) string { return v.Secret }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSentryKeyResultOutput{})
}
