// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sentry

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-sentry/sdk/go/sentry/internal"
)

// Retrieve an organization member by email.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-sentry/sdk/go/sentry"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := sentry.LookupSentryOrganizationMember(ctx, &sentry.LookupSentryOrganizationMemberArgs{
//				Organization: "terraform-provider-sentry",
//				Email:        "test@example.com",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupSentryOrganizationMember(ctx *pulumi.Context, args *LookupSentryOrganizationMemberArgs, opts ...pulumi.InvokeOption) (*LookupSentryOrganizationMemberResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSentryOrganizationMemberResult
	err := ctx.Invoke("sentry:index/getSentryOrganizationMember:getSentryOrganizationMember", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSentryOrganizationMember.
type LookupSentryOrganizationMemberArgs struct {
	// The email of the organization member.
	Email string `pulumi:"email"`
	// The organization the resource belongs to.
	Organization string `pulumi:"organization"`
}

// A collection of values returned by getSentryOrganizationMember.
type LookupSentryOrganizationMemberResult struct {
	// The email of the organization member.
	Email string `pulumi:"email"`
	// The ID of this resource.
	Id string `pulumi:"id"`
	// The organization the resource belongs to.
	Organization string `pulumi:"organization"`
	// This is the role of the organization member.
	Role string `pulumi:"role"`
}

func LookupSentryOrganizationMemberOutput(ctx *pulumi.Context, args LookupSentryOrganizationMemberOutputArgs, opts ...pulumi.InvokeOption) LookupSentryOrganizationMemberResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSentryOrganizationMemberResultOutput, error) {
			args := v.(LookupSentryOrganizationMemberArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv LookupSentryOrganizationMemberResult
			secret, err := ctx.InvokePackageRaw("sentry:index/getSentryOrganizationMember:getSentryOrganizationMember", args, &rv, "", opts...)
			if err != nil {
				return LookupSentryOrganizationMemberResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(LookupSentryOrganizationMemberResultOutput)
			if secret {
				return pulumi.ToSecret(output).(LookupSentryOrganizationMemberResultOutput), nil
			}
			return output, nil
		}).(LookupSentryOrganizationMemberResultOutput)
}

// A collection of arguments for invoking getSentryOrganizationMember.
type LookupSentryOrganizationMemberOutputArgs struct {
	// The email of the organization member.
	Email pulumi.StringInput `pulumi:"email"`
	// The organization the resource belongs to.
	Organization pulumi.StringInput `pulumi:"organization"`
}

func (LookupSentryOrganizationMemberOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSentryOrganizationMemberArgs)(nil)).Elem()
}

// A collection of values returned by getSentryOrganizationMember.
type LookupSentryOrganizationMemberResultOutput struct{ *pulumi.OutputState }

func (LookupSentryOrganizationMemberResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSentryOrganizationMemberResult)(nil)).Elem()
}

func (o LookupSentryOrganizationMemberResultOutput) ToLookupSentryOrganizationMemberResultOutput() LookupSentryOrganizationMemberResultOutput {
	return o
}

func (o LookupSentryOrganizationMemberResultOutput) ToLookupSentryOrganizationMemberResultOutputWithContext(ctx context.Context) LookupSentryOrganizationMemberResultOutput {
	return o
}

// The email of the organization member.
func (o LookupSentryOrganizationMemberResultOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryOrganizationMemberResult) string { return v.Email }).(pulumi.StringOutput)
}

// The ID of this resource.
func (o LookupSentryOrganizationMemberResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryOrganizationMemberResult) string { return v.Id }).(pulumi.StringOutput)
}

// The organization the resource belongs to.
func (o LookupSentryOrganizationMemberResultOutput) Organization() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryOrganizationMemberResult) string { return v.Organization }).(pulumi.StringOutput)
}

// This is the role of the organization member.
func (o LookupSentryOrganizationMemberResultOutput) Role() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSentryOrganizationMemberResult) string { return v.Role }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSentryOrganizationMemberResultOutput{})
}
