// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SentryDashboardWidgetQueryArgs extends com.pulumi.resources.ResourceArgs {

    public static final SentryDashboardWidgetQueryArgs Empty = new SentryDashboardWidgetQueryArgs();

    @Import(name="aggregates")
    private @Nullable Output<List<String>> aggregates;

    public Optional<Output<List<String>>> aggregates() {
        return Optional.ofNullable(this.aggregates);
    }

    @Import(name="columns")
    private @Nullable Output<List<String>> columns;

    public Optional<Output<List<String>>> columns() {
        return Optional.ofNullable(this.columns);
    }

    @Import(name="conditions")
    private @Nullable Output<String> conditions;

    public Optional<Output<String>> conditions() {
        return Optional.ofNullable(this.conditions);
    }

    @Import(name="fieldAliases")
    private @Nullable Output<List<String>> fieldAliases;

    public Optional<Output<List<String>>> fieldAliases() {
        return Optional.ofNullable(this.fieldAliases);
    }

    @Import(name="fields")
    private @Nullable Output<List<String>> fields;

    public Optional<Output<List<String>>> fields() {
        return Optional.ofNullable(this.fields);
    }

    /**
     * The ID of the query.
     * 
     */
    @Import(name="id")
    private @Nullable Output<String> id;

    /**
     * @return The ID of the query.
     * 
     */
    public Optional<Output<String>> id() {
        return Optional.ofNullable(this.id);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="orderBy")
    private @Nullable Output<String> orderBy;

    public Optional<Output<String>> orderBy() {
        return Optional.ofNullable(this.orderBy);
    }

    private SentryDashboardWidgetQueryArgs() {}

    private SentryDashboardWidgetQueryArgs(SentryDashboardWidgetQueryArgs $) {
        this.aggregates = $.aggregates;
        this.columns = $.columns;
        this.conditions = $.conditions;
        this.fieldAliases = $.fieldAliases;
        this.fields = $.fields;
        this.id = $.id;
        this.name = $.name;
        this.orderBy = $.orderBy;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryDashboardWidgetQueryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryDashboardWidgetQueryArgs $;

        public Builder() {
            $ = new SentryDashboardWidgetQueryArgs();
        }

        public Builder(SentryDashboardWidgetQueryArgs defaults) {
            $ = new SentryDashboardWidgetQueryArgs(Objects.requireNonNull(defaults));
        }

        public Builder aggregates(@Nullable Output<List<String>> aggregates) {
            $.aggregates = aggregates;
            return this;
        }

        public Builder aggregates(List<String> aggregates) {
            return aggregates(Output.of(aggregates));
        }

        public Builder aggregates(String... aggregates) {
            return aggregates(List.of(aggregates));
        }

        public Builder columns(@Nullable Output<List<String>> columns) {
            $.columns = columns;
            return this;
        }

        public Builder columns(List<String> columns) {
            return columns(Output.of(columns));
        }

        public Builder columns(String... columns) {
            return columns(List.of(columns));
        }

        public Builder conditions(@Nullable Output<String> conditions) {
            $.conditions = conditions;
            return this;
        }

        public Builder conditions(String conditions) {
            return conditions(Output.of(conditions));
        }

        public Builder fieldAliases(@Nullable Output<List<String>> fieldAliases) {
            $.fieldAliases = fieldAliases;
            return this;
        }

        public Builder fieldAliases(List<String> fieldAliases) {
            return fieldAliases(Output.of(fieldAliases));
        }

        public Builder fieldAliases(String... fieldAliases) {
            return fieldAliases(List.of(fieldAliases));
        }

        public Builder fields(@Nullable Output<List<String>> fields) {
            $.fields = fields;
            return this;
        }

        public Builder fields(List<String> fields) {
            return fields(Output.of(fields));
        }

        public Builder fields(String... fields) {
            return fields(List.of(fields));
        }

        /**
         * @param id The ID of the query.
         * 
         * @return builder
         * 
         */
        public Builder id(@Nullable Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id The ID of the query.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder orderBy(@Nullable Output<String> orderBy) {
            $.orderBy = orderBy;
            return this;
        }

        public Builder orderBy(String orderBy) {
            return orderBy(Output.of(orderBy));
        }

        public SentryDashboardWidgetQueryArgs build() {
            return $;
        }
    }

}
