// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;


public final class SentryDashboardWidgetLayoutArgs extends com.pulumi.resources.ResourceArgs {

    public static final SentryDashboardWidgetLayoutArgs Empty = new SentryDashboardWidgetLayoutArgs();

    @Import(name="h", required=true)
    private Output<Integer> h;

    public Output<Integer> h() {
        return this.h;
    }

    @Import(name="minH", required=true)
    private Output<Integer> minH;

    public Output<Integer> minH() {
        return this.minH;
    }

    @Import(name="w", required=true)
    private Output<Integer> w;

    public Output<Integer> w() {
        return this.w;
    }

    @Import(name="x", required=true)
    private Output<Integer> x;

    public Output<Integer> x() {
        return this.x;
    }

    @Import(name="y", required=true)
    private Output<Integer> y;

    public Output<Integer> y() {
        return this.y;
    }

    private SentryDashboardWidgetLayoutArgs() {}

    private SentryDashboardWidgetLayoutArgs(SentryDashboardWidgetLayoutArgs $) {
        this.h = $.h;
        this.minH = $.minH;
        this.w = $.w;
        this.x = $.x;
        this.y = $.y;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryDashboardWidgetLayoutArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryDashboardWidgetLayoutArgs $;

        public Builder() {
            $ = new SentryDashboardWidgetLayoutArgs();
        }

        public Builder(SentryDashboardWidgetLayoutArgs defaults) {
            $ = new SentryDashboardWidgetLayoutArgs(Objects.requireNonNull(defaults));
        }

        public Builder h(Output<Integer> h) {
            $.h = h;
            return this;
        }

        public Builder h(Integer h) {
            return h(Output.of(h));
        }

        public Builder minH(Output<Integer> minH) {
            $.minH = minH;
            return this;
        }

        public Builder minH(Integer minH) {
            return minH(Output.of(minH));
        }

        public Builder w(Output<Integer> w) {
            $.w = w;
            return this;
        }

        public Builder w(Integer w) {
            return w(Output.of(w));
        }

        public Builder x(Output<Integer> x) {
            $.x = x;
            return this;
        }

        public Builder x(Integer x) {
            return x(Output.of(x));
        }

        public Builder y(Output<Integer> y) {
            $.y = y;
            return this;
        }

        public Builder y(Integer y) {
            return y(Output.of(y));
        }

        public SentryDashboardWidgetLayoutArgs build() {
            if ($.h == null) {
                throw new MissingRequiredPropertyException("SentryDashboardWidgetLayoutArgs", "h");
            }
            if ($.minH == null) {
                throw new MissingRequiredPropertyException("SentryDashboardWidgetLayoutArgs", "minH");
            }
            if ($.w == null) {
                throw new MissingRequiredPropertyException("SentryDashboardWidgetLayoutArgs", "w");
            }
            if ($.x == null) {
                throw new MissingRequiredPropertyException("SentryDashboardWidgetLayoutArgs", "x");
            }
            if ($.y == null) {
                throw new MissingRequiredPropertyException("SentryDashboardWidgetLayoutArgs", "y");
            }
            return $;
        }
    }

}
