// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SentryIssueAlertFiltersV2IssueCategoryArgs extends com.pulumi.resources.ResourceArgs {

    public static final SentryIssueAlertFiltersV2IssueCategoryArgs Empty = new SentryIssueAlertFiltersV2IssueCategoryArgs();

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Valid values are: `Error`, `Performance`, `Profile`, `Cron`, `Replay`, `Feedback`, `Uptime`, and `Metric_Alert`.
     * 
     */
    @Import(name="value", required=true)
    private Output<String> value;

    /**
     * @return Valid values are: `Error`, `Performance`, `Profile`, `Cron`, `Replay`, `Feedback`, `Uptime`, and `Metric_Alert`.
     * 
     */
    public Output<String> value() {
        return this.value;
    }

    private SentryIssueAlertFiltersV2IssueCategoryArgs() {}

    private SentryIssueAlertFiltersV2IssueCategoryArgs(SentryIssueAlertFiltersV2IssueCategoryArgs $) {
        this.name = $.name;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryIssueAlertFiltersV2IssueCategoryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryIssueAlertFiltersV2IssueCategoryArgs $;

        public Builder() {
            $ = new SentryIssueAlertFiltersV2IssueCategoryArgs();
        }

        public Builder(SentryIssueAlertFiltersV2IssueCategoryArgs defaults) {
            $ = new SentryIssueAlertFiltersV2IssueCategoryArgs(Objects.requireNonNull(defaults));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param value Valid values are: `Error`, `Performance`, `Profile`, `Cron`, `Replay`, `Feedback`, `Uptime`, and `Metric_Alert`.
         * 
         * @return builder
         * 
         */
        public Builder value(Output<String> value) {
            $.value = value;
            return this;
        }

        /**
         * @param value Valid values are: `Error`, `Performance`, `Profile`, `Cron`, `Replay`, `Feedback`, `Uptime`, and `Metric_Alert`.
         * 
         * @return builder
         * 
         */
        public Builder value(String value) {
            return value(Output.of(value));
        }

        public SentryIssueAlertFiltersV2IssueCategoryArgs build() {
            if ($.value == null) {
                throw new MissingRequiredPropertyException("SentryIssueAlertFiltersV2IssueCategoryArgs", "value");
            }
            return $;
        }
    }

}
