// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SentryOrganizationRepositoryGithubState extends com.pulumi.resources.ResourceArgs {

    public static final SentryOrganizationRepositoryGithubState Empty = new SentryOrganizationRepositoryGithubState();

    /**
     * The repo identifier. For Github it is {github*org}/{github*repo}.
     * 
     */
    @Import(name="identifier")
    private @Nullable Output<String> identifier;

    /**
     * @return The repo identifier. For Github it is {github*org}/{github*repo}.
     * 
     */
    public Optional<Output<String>> identifier() {
        return Optional.ofNullable(this.identifier);
    }

    /**
     * The organization integration ID for Github.
     * 
     */
    @Import(name="integrationId")
    private @Nullable Output<String> integrationId;

    /**
     * @return The organization integration ID for Github.
     * 
     */
    public Optional<Output<String>> integrationId() {
        return Optional.ofNullable(this.integrationId);
    }

    /**
     * The internal ID for this organization repository.
     * 
     */
    @Import(name="internalId")
    private @Nullable Output<String> internalId;

    /**
     * @return The internal ID for this organization repository.
     * 
     */
    public Optional<Output<String>> internalId() {
        return Optional.ofNullable(this.internalId);
    }

    /**
     * The slug of the Sentry organization this resource belongs to.
     * 
     */
    @Import(name="organization")
    private @Nullable Output<String> organization;

    /**
     * @return The slug of the Sentry organization this resource belongs to.
     * 
     */
    public Optional<Output<String>> organization() {
        return Optional.ofNullable(this.organization);
    }

    private SentryOrganizationRepositoryGithubState() {}

    private SentryOrganizationRepositoryGithubState(SentryOrganizationRepositoryGithubState $) {
        this.identifier = $.identifier;
        this.integrationId = $.integrationId;
        this.internalId = $.internalId;
        this.organization = $.organization;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryOrganizationRepositoryGithubState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryOrganizationRepositoryGithubState $;

        public Builder() {
            $ = new SentryOrganizationRepositoryGithubState();
        }

        public Builder(SentryOrganizationRepositoryGithubState defaults) {
            $ = new SentryOrganizationRepositoryGithubState(Objects.requireNonNull(defaults));
        }

        /**
         * @param identifier The repo identifier. For Github it is {github*org}/{github*repo}.
         * 
         * @return builder
         * 
         */
        public Builder identifier(@Nullable Output<String> identifier) {
            $.identifier = identifier;
            return this;
        }

        /**
         * @param identifier The repo identifier. For Github it is {github*org}/{github*repo}.
         * 
         * @return builder
         * 
         */
        public Builder identifier(String identifier) {
            return identifier(Output.of(identifier));
        }

        /**
         * @param integrationId The organization integration ID for Github.
         * 
         * @return builder
         * 
         */
        public Builder integrationId(@Nullable Output<String> integrationId) {
            $.integrationId = integrationId;
            return this;
        }

        /**
         * @param integrationId The organization integration ID for Github.
         * 
         * @return builder
         * 
         */
        public Builder integrationId(String integrationId) {
            return integrationId(Output.of(integrationId));
        }

        /**
         * @param internalId The internal ID for this organization repository.
         * 
         * @return builder
         * 
         */
        public Builder internalId(@Nullable Output<String> internalId) {
            $.internalId = internalId;
            return this;
        }

        /**
         * @param internalId The internal ID for this organization repository.
         * 
         * @return builder
         * 
         */
        public Builder internalId(String internalId) {
            return internalId(Output.of(internalId));
        }

        /**
         * @param organization The slug of the Sentry organization this resource belongs to.
         * 
         * @return builder
         * 
         */
        public Builder organization(@Nullable Output<String> organization) {
            $.organization = organization;
            return this;
        }

        /**
         * @param organization The slug of the Sentry organization this resource belongs to.
         * 
         * @return builder
         * 
         */
        public Builder organization(String organization) {
            return organization(Output.of(organization));
        }

        public SentryOrganizationRepositoryGithubState build() {
            return $;
        }
    }

}
