// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.sentry.inputs.SentryMetricAlertTriggerArgs;
import java.lang.Double;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SentryMetricAlertState extends com.pulumi.resources.ResourceArgs {

    public static final SentryMetricAlertState Empty = new SentryMetricAlertState();

    /**
     * The aggregation criteria to apply
     * 
     */
    @Import(name="aggregate")
    private @Nullable Output<String> aggregate;

    /**
     * @return The aggregation criteria to apply
     * 
     */
    public Optional<Output<String>> aggregate() {
        return Optional.ofNullable(this.aggregate);
    }

    /**
     * An optional int representing the time delta to use as the comparison period, in minutes. Required when using a percentage change threshold
     * 
     */
    @Import(name="comparisonDelta")
    private @Nullable Output<Double> comparisonDelta;

    /**
     * @return An optional int representing the time delta to use as the comparison period, in minutes. Required when using a percentage change threshold
     * 
     */
    public Optional<Output<Double>> comparisonDelta() {
        return Optional.ofNullable(this.comparisonDelta);
    }

    /**
     * The Sentry Alert category
     * 
     */
    @Import(name="dataset")
    private @Nullable Output<String> dataset;

    /**
     * @return The Sentry Alert category
     * 
     */
    public Optional<Output<String>> dataset() {
        return Optional.ofNullable(this.dataset);
    }

    /**
     * Perform Alert rule in a specific environment
     * 
     */
    @Import(name="environment")
    private @Nullable Output<String> environment;

    /**
     * @return Perform Alert rule in a specific environment
     * 
     */
    public Optional<Output<String>> environment() {
        return Optional.ofNullable(this.environment);
    }

    /**
     * The events type of dataset.
     * 
     */
    @Import(name="eventTypes")
    private @Nullable Output<List<String>> eventTypes;

    /**
     * @return The events type of dataset.
     * 
     */
    public Optional<Output<List<String>>> eventTypes() {
        return Optional.ofNullable(this.eventTypes);
    }

    /**
     * The internal ID for this metric alert.
     * 
     */
    @Import(name="internalId")
    private @Nullable Output<String> internalId;

    /**
     * @return The internal ID for this metric alert.
     * 
     */
    public Optional<Output<String>> internalId() {
        return Optional.ofNullable(this.internalId);
    }

    /**
     * The metric alert name.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The metric alert name.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The slug of the organization the metric alert belongs to.
     * 
     */
    @Import(name="organization")
    private @Nullable Output<String> organization;

    /**
     * @return The slug of the organization the metric alert belongs to.
     * 
     */
    public Optional<Output<String>> organization() {
        return Optional.ofNullable(this.organization);
    }

    /**
     * Specifies the owner id of this Alert rule
     * 
     */
    @Import(name="owner")
    private @Nullable Output<String> owner;

    /**
     * @return Specifies the owner id of this Alert rule
     * 
     */
    public Optional<Output<String>> owner() {
        return Optional.ofNullable(this.owner);
    }

    /**
     * The slug of the project to create the metric alert for.
     * 
     */
    @Import(name="project")
    private @Nullable Output<String> project;

    /**
     * @return The slug of the project to create the metric alert for.
     * 
     */
    public Optional<Output<String>> project() {
        return Optional.ofNullable(this.project);
    }

    /**
     * The query filter to apply
     * 
     */
    @Import(name="query")
    private @Nullable Output<String> query;

    /**
     * @return The query filter to apply
     * 
     */
    public Optional<Output<String>> query() {
        return Optional.ofNullable(this.query);
    }

    /**
     * The value at which the Alert rule resolves
     * 
     */
    @Import(name="resolveThreshold")
    private @Nullable Output<Double> resolveThreshold;

    /**
     * @return The value at which the Alert rule resolves
     * 
     */
    public Optional<Output<Double>> resolveThreshold() {
        return Optional.ofNullable(this.resolveThreshold);
    }

    /**
     * The type of threshold
     * 
     */
    @Import(name="thresholdType")
    private @Nullable Output<Integer> thresholdType;

    /**
     * @return The type of threshold
     * 
     */
    public Optional<Output<Integer>> thresholdType() {
        return Optional.ofNullable(this.thresholdType);
    }

    /**
     * The period to evaluate the Alert rule in minutes
     * 
     */
    @Import(name="timeWindow")
    private @Nullable Output<Double> timeWindow;

    /**
     * @return The period to evaluate the Alert rule in minutes
     * 
     */
    public Optional<Output<Double>> timeWindow() {
        return Optional.ofNullable(this.timeWindow);
    }

    @Import(name="triggers")
    private @Nullable Output<List<SentryMetricAlertTriggerArgs>> triggers;

    public Optional<Output<List<SentryMetricAlertTriggerArgs>>> triggers() {
        return Optional.ofNullable(this.triggers);
    }

    private SentryMetricAlertState() {}

    private SentryMetricAlertState(SentryMetricAlertState $) {
        this.aggregate = $.aggregate;
        this.comparisonDelta = $.comparisonDelta;
        this.dataset = $.dataset;
        this.environment = $.environment;
        this.eventTypes = $.eventTypes;
        this.internalId = $.internalId;
        this.name = $.name;
        this.organization = $.organization;
        this.owner = $.owner;
        this.project = $.project;
        this.query = $.query;
        this.resolveThreshold = $.resolveThreshold;
        this.thresholdType = $.thresholdType;
        this.timeWindow = $.timeWindow;
        this.triggers = $.triggers;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryMetricAlertState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryMetricAlertState $;

        public Builder() {
            $ = new SentryMetricAlertState();
        }

        public Builder(SentryMetricAlertState defaults) {
            $ = new SentryMetricAlertState(Objects.requireNonNull(defaults));
        }

        /**
         * @param aggregate The aggregation criteria to apply
         * 
         * @return builder
         * 
         */
        public Builder aggregate(@Nullable Output<String> aggregate) {
            $.aggregate = aggregate;
            return this;
        }

        /**
         * @param aggregate The aggregation criteria to apply
         * 
         * @return builder
         * 
         */
        public Builder aggregate(String aggregate) {
            return aggregate(Output.of(aggregate));
        }

        /**
         * @param comparisonDelta An optional int representing the time delta to use as the comparison period, in minutes. Required when using a percentage change threshold
         * 
         * @return builder
         * 
         */
        public Builder comparisonDelta(@Nullable Output<Double> comparisonDelta) {
            $.comparisonDelta = comparisonDelta;
            return this;
        }

        /**
         * @param comparisonDelta An optional int representing the time delta to use as the comparison period, in minutes. Required when using a percentage change threshold
         * 
         * @return builder
         * 
         */
        public Builder comparisonDelta(Double comparisonDelta) {
            return comparisonDelta(Output.of(comparisonDelta));
        }

        /**
         * @param dataset The Sentry Alert category
         * 
         * @return builder
         * 
         */
        public Builder dataset(@Nullable Output<String> dataset) {
            $.dataset = dataset;
            return this;
        }

        /**
         * @param dataset The Sentry Alert category
         * 
         * @return builder
         * 
         */
        public Builder dataset(String dataset) {
            return dataset(Output.of(dataset));
        }

        /**
         * @param environment Perform Alert rule in a specific environment
         * 
         * @return builder
         * 
         */
        public Builder environment(@Nullable Output<String> environment) {
            $.environment = environment;
            return this;
        }

        /**
         * @param environment Perform Alert rule in a specific environment
         * 
         * @return builder
         * 
         */
        public Builder environment(String environment) {
            return environment(Output.of(environment));
        }

        /**
         * @param eventTypes The events type of dataset.
         * 
         * @return builder
         * 
         */
        public Builder eventTypes(@Nullable Output<List<String>> eventTypes) {
            $.eventTypes = eventTypes;
            return this;
        }

        /**
         * @param eventTypes The events type of dataset.
         * 
         * @return builder
         * 
         */
        public Builder eventTypes(List<String> eventTypes) {
            return eventTypes(Output.of(eventTypes));
        }

        /**
         * @param eventTypes The events type of dataset.
         * 
         * @return builder
         * 
         */
        public Builder eventTypes(String... eventTypes) {
            return eventTypes(List.of(eventTypes));
        }

        /**
         * @param internalId The internal ID for this metric alert.
         * 
         * @return builder
         * 
         */
        public Builder internalId(@Nullable Output<String> internalId) {
            $.internalId = internalId;
            return this;
        }

        /**
         * @param internalId The internal ID for this metric alert.
         * 
         * @return builder
         * 
         */
        public Builder internalId(String internalId) {
            return internalId(Output.of(internalId));
        }

        /**
         * @param name The metric alert name.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The metric alert name.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param organization The slug of the organization the metric alert belongs to.
         * 
         * @return builder
         * 
         */
        public Builder organization(@Nullable Output<String> organization) {
            $.organization = organization;
            return this;
        }

        /**
         * @param organization The slug of the organization the metric alert belongs to.
         * 
         * @return builder
         * 
         */
        public Builder organization(String organization) {
            return organization(Output.of(organization));
        }

        /**
         * @param owner Specifies the owner id of this Alert rule
         * 
         * @return builder
         * 
         */
        public Builder owner(@Nullable Output<String> owner) {
            $.owner = owner;
            return this;
        }

        /**
         * @param owner Specifies the owner id of this Alert rule
         * 
         * @return builder
         * 
         */
        public Builder owner(String owner) {
            return owner(Output.of(owner));
        }

        /**
         * @param project The slug of the project to create the metric alert for.
         * 
         * @return builder
         * 
         */
        public Builder project(@Nullable Output<String> project) {
            $.project = project;
            return this;
        }

        /**
         * @param project The slug of the project to create the metric alert for.
         * 
         * @return builder
         * 
         */
        public Builder project(String project) {
            return project(Output.of(project));
        }

        /**
         * @param query The query filter to apply
         * 
         * @return builder
         * 
         */
        public Builder query(@Nullable Output<String> query) {
            $.query = query;
            return this;
        }

        /**
         * @param query The query filter to apply
         * 
         * @return builder
         * 
         */
        public Builder query(String query) {
            return query(Output.of(query));
        }

        /**
         * @param resolveThreshold The value at which the Alert rule resolves
         * 
         * @return builder
         * 
         */
        public Builder resolveThreshold(@Nullable Output<Double> resolveThreshold) {
            $.resolveThreshold = resolveThreshold;
            return this;
        }

        /**
         * @param resolveThreshold The value at which the Alert rule resolves
         * 
         * @return builder
         * 
         */
        public Builder resolveThreshold(Double resolveThreshold) {
            return resolveThreshold(Output.of(resolveThreshold));
        }

        /**
         * @param thresholdType The type of threshold
         * 
         * @return builder
         * 
         */
        public Builder thresholdType(@Nullable Output<Integer> thresholdType) {
            $.thresholdType = thresholdType;
            return this;
        }

        /**
         * @param thresholdType The type of threshold
         * 
         * @return builder
         * 
         */
        public Builder thresholdType(Integer thresholdType) {
            return thresholdType(Output.of(thresholdType));
        }

        /**
         * @param timeWindow The period to evaluate the Alert rule in minutes
         * 
         * @return builder
         * 
         */
        public Builder timeWindow(@Nullable Output<Double> timeWindow) {
            $.timeWindow = timeWindow;
            return this;
        }

        /**
         * @param timeWindow The period to evaluate the Alert rule in minutes
         * 
         * @return builder
         * 
         */
        public Builder timeWindow(Double timeWindow) {
            return timeWindow(Output.of(timeWindow));
        }

        public Builder triggers(@Nullable Output<List<SentryMetricAlertTriggerArgs>> triggers) {
            $.triggers = triggers;
            return this;
        }

        public Builder triggers(List<SentryMetricAlertTriggerArgs> triggers) {
            return triggers(Output.of(triggers));
        }

        public Builder triggers(SentryMetricAlertTriggerArgs... triggers) {
            return triggers(List.of(triggers));
        }

        public SentryMetricAlertState build() {
            return $;
        }
    }

}
