// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SentryIssueAlertActionsV2DiscordNotifyServiceArgs extends com.pulumi.resources.ResourceArgs {

    public static final SentryIssueAlertActionsV2DiscordNotifyServiceArgs Empty = new SentryIssueAlertActionsV2DiscordNotifyServiceArgs();

    /**
     * The ID of the channel to send the notification to. You must enter either a channel ID or a channel URL, not a channel name
     * 
     */
    @Import(name="channelId", required=true)
    private Output<String> channelId;

    /**
     * @return The ID of the channel to send the notification to. You must enter either a channel ID or a channel URL, not a channel name
     * 
     */
    public Output<String> channelId() {
        return this.channelId;
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The integration ID associated with the Discord server.
     * 
     */
    @Import(name="server", required=true)
    private Output<String> server;

    /**
     * @return The integration ID associated with the Discord server.
     * 
     */
    public Output<String> server() {
        return this.server;
    }

    /**
     * A string of tags to show in the notification.
     * 
     */
    @Import(name="tags")
    private @Nullable Output<List<String>> tags;

    /**
     * @return A string of tags to show in the notification.
     * 
     */
    public Optional<Output<List<String>>> tags() {
        return Optional.ofNullable(this.tags);
    }

    private SentryIssueAlertActionsV2DiscordNotifyServiceArgs() {}

    private SentryIssueAlertActionsV2DiscordNotifyServiceArgs(SentryIssueAlertActionsV2DiscordNotifyServiceArgs $) {
        this.channelId = $.channelId;
        this.name = $.name;
        this.server = $.server;
        this.tags = $.tags;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryIssueAlertActionsV2DiscordNotifyServiceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryIssueAlertActionsV2DiscordNotifyServiceArgs $;

        public Builder() {
            $ = new SentryIssueAlertActionsV2DiscordNotifyServiceArgs();
        }

        public Builder(SentryIssueAlertActionsV2DiscordNotifyServiceArgs defaults) {
            $ = new SentryIssueAlertActionsV2DiscordNotifyServiceArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param channelId The ID of the channel to send the notification to. You must enter either a channel ID or a channel URL, not a channel name
         * 
         * @return builder
         * 
         */
        public Builder channelId(Output<String> channelId) {
            $.channelId = channelId;
            return this;
        }

        /**
         * @param channelId The ID of the channel to send the notification to. You must enter either a channel ID or a channel URL, not a channel name
         * 
         * @return builder
         * 
         */
        public Builder channelId(String channelId) {
            return channelId(Output.of(channelId));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param server The integration ID associated with the Discord server.
         * 
         * @return builder
         * 
         */
        public Builder server(Output<String> server) {
            $.server = server;
            return this;
        }

        /**
         * @param server The integration ID associated with the Discord server.
         * 
         * @return builder
         * 
         */
        public Builder server(String server) {
            return server(Output.of(server));
        }

        /**
         * @param tags A string of tags to show in the notification.
         * 
         * @return builder
         * 
         */
        public Builder tags(@Nullable Output<List<String>> tags) {
            $.tags = tags;
            return this;
        }

        /**
         * @param tags A string of tags to show in the notification.
         * 
         * @return builder
         * 
         */
        public Builder tags(List<String> tags) {
            return tags(Output.of(tags));
        }

        /**
         * @param tags A string of tags to show in the notification.
         * 
         * @return builder
         * 
         */
        public Builder tags(String... tags) {
            return tags(List.of(tags));
        }

        public SentryIssueAlertActionsV2DiscordNotifyServiceArgs build() {
            if ($.channelId == null) {
                throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2DiscordNotifyServiceArgs", "channelId");
            }
            if ($.server == null) {
                throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2DiscordNotifyServiceArgs", "server");
            }
            return $;
        }
    }

}
