// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SentryIssueAlertActionsV2JiraCreateTicketArgs extends com.pulumi.resources.ResourceArgs {

    public static final SentryIssueAlertActionsV2JiraCreateTicketArgs Empty = new SentryIssueAlertActionsV2JiraCreateTicketArgs();

    /**
     * The integration ID associated with Jira.
     * 
     */
    @Import(name="integration", required=true)
    private Output<String> integration;

    /**
     * @return The integration ID associated with Jira.
     * 
     */
    public Output<String> integration() {
        return this.integration;
    }

    /**
     * The ID of the type of issue that the ticket should be created as.
     * 
     */
    @Import(name="issueType", required=true)
    private Output<String> issueType;

    /**
     * @return The ID of the type of issue that the ticket should be created as.
     * 
     */
    public Output<String> issueType() {
        return this.issueType;
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The ID of the Jira project.
     * 
     */
    @Import(name="project", required=true)
    private Output<String> project;

    /**
     * @return The ID of the Jira project.
     * 
     */
    public Output<String> project() {
        return this.project;
    }

    private SentryIssueAlertActionsV2JiraCreateTicketArgs() {}

    private SentryIssueAlertActionsV2JiraCreateTicketArgs(SentryIssueAlertActionsV2JiraCreateTicketArgs $) {
        this.integration = $.integration;
        this.issueType = $.issueType;
        this.name = $.name;
        this.project = $.project;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryIssueAlertActionsV2JiraCreateTicketArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryIssueAlertActionsV2JiraCreateTicketArgs $;

        public Builder() {
            $ = new SentryIssueAlertActionsV2JiraCreateTicketArgs();
        }

        public Builder(SentryIssueAlertActionsV2JiraCreateTicketArgs defaults) {
            $ = new SentryIssueAlertActionsV2JiraCreateTicketArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param integration The integration ID associated with Jira.
         * 
         * @return builder
         * 
         */
        public Builder integration(Output<String> integration) {
            $.integration = integration;
            return this;
        }

        /**
         * @param integration The integration ID associated with Jira.
         * 
         * @return builder
         * 
         */
        public Builder integration(String integration) {
            return integration(Output.of(integration));
        }

        /**
         * @param issueType The ID of the type of issue that the ticket should be created as.
         * 
         * @return builder
         * 
         */
        public Builder issueType(Output<String> issueType) {
            $.issueType = issueType;
            return this;
        }

        /**
         * @param issueType The ID of the type of issue that the ticket should be created as.
         * 
         * @return builder
         * 
         */
        public Builder issueType(String issueType) {
            return issueType(Output.of(issueType));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param project The ID of the Jira project.
         * 
         * @return builder
         * 
         */
        public Builder project(Output<String> project) {
            $.project = project;
            return this;
        }

        /**
         * @param project The ID of the Jira project.
         * 
         * @return builder
         * 
         */
        public Builder project(String project) {
            return project(Output.of(project));
        }

        public SentryIssueAlertActionsV2JiraCreateTicketArgs build() {
            if ($.integration == null) {
                throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2JiraCreateTicketArgs", "integration");
            }
            if ($.issueType == null) {
                throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2JiraCreateTicketArgs", "issueType");
            }
            if ($.project == null) {
                throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2JiraCreateTicketArgs", "project");
            }
            return $;
        }
    }

}
