// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class SentrygetIssueAlertPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final SentrygetIssueAlertPlainArgs Empty = new SentrygetIssueAlertPlainArgs();

    /**
     * The ID of this resource.
     * 
     */
    @Import(name="id", required=true)
    private String id;

    /**
     * @return The ID of this resource.
     * 
     */
    public String id() {
        return this.id;
    }

    /**
     * The organization the resource belongs to.
     * 
     */
    @Import(name="organization", required=true)
    private String organization;

    /**
     * @return The organization the resource belongs to.
     * 
     */
    public String organization() {
        return this.organization;
    }

    /**
     * The project the resource belongs to.
     * 
     */
    @Import(name="project", required=true)
    private String project;

    /**
     * @return The project the resource belongs to.
     * 
     */
    public String project() {
        return this.project;
    }

    private SentrygetIssueAlertPlainArgs() {}

    private SentrygetIssueAlertPlainArgs(SentrygetIssueAlertPlainArgs $) {
        this.id = $.id;
        this.organization = $.organization;
        this.project = $.project;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentrygetIssueAlertPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentrygetIssueAlertPlainArgs $;

        public Builder() {
            $ = new SentrygetIssueAlertPlainArgs();
        }

        public Builder(SentrygetIssueAlertPlainArgs defaults) {
            $ = new SentrygetIssueAlertPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The ID of this resource.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            $.id = id;
            return this;
        }

        /**
         * @param organization The organization the resource belongs to.
         * 
         * @return builder
         * 
         */
        public Builder organization(String organization) {
            $.organization = organization;
            return this;
        }

        /**
         * @param project The project the resource belongs to.
         * 
         * @return builder
         * 
         */
        public Builder project(String project) {
            $.project = project;
            return this;
        }

        public SentrygetIssueAlertPlainArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("SentrygetIssueAlertPlainArgs", "id");
            }
            if ($.organization == null) {
                throw new MissingRequiredPropertyException("SentrygetIssueAlertPlainArgs", "organization");
            }
            if ($.project == null) {
                throw new MissingRequiredPropertyException("SentrygetIssueAlertPlainArgs", "project");
            }
            return $;
        }
    }

}
