// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SentryIssueAlertActionsV2NotifyEventArgs extends com.pulumi.resources.ResourceArgs {

    public static final SentryIssueAlertActionsV2NotifyEventArgs Empty = new SentryIssueAlertActionsV2NotifyEventArgs();

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    private SentryIssueAlertActionsV2NotifyEventArgs() {}

    private SentryIssueAlertActionsV2NotifyEventArgs(SentryIssueAlertActionsV2NotifyEventArgs $) {
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryIssueAlertActionsV2NotifyEventArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryIssueAlertActionsV2NotifyEventArgs $;

        public Builder() {
            $ = new SentryIssueAlertActionsV2NotifyEventArgs();
        }

        public Builder(SentryIssueAlertActionsV2NotifyEventArgs defaults) {
            $ = new SentryIssueAlertActionsV2NotifyEventArgs(Objects.requireNonNull(defaults));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public SentryIssueAlertActionsV2NotifyEventArgs build() {
            return $;
        }
    }

}
