// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.sentry.inputs.SentryKeyJavascriptLoaderScriptArgs;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SentryKeyState extends com.pulumi.resources.ResourceArgs {

    public static final SentryKeyState Empty = new SentryKeyState();

    /**
     * This is a map of DSN values. The keys include `public`, `secret`, `csp`, `security`, `minidump`, `nel`, `unreal`, `cdn`, and `crons`.
     * 
     */
    @Import(name="dsn")
    private @Nullable Output<Map<String,String>> dsn;

    /**
     * @return This is a map of DSN values. The keys include `public`, `secret`, `csp`, `security`, `minidump`, `nel`, `unreal`, `cdn`, and `crons`.
     * 
     */
    public Optional<Output<Map<String,String>>> dsn() {
        return Optional.ofNullable(this.dsn);
    }

    /**
     * Security header endpoint for features like CSP and Expect-CT reports. **Deprecated** Use `dsn[&#34;csp&#34;]` instead.
     * 
     * @deprecated
     * This field is deprecated and will be removed in a future version. Use `dsn[&#34;csp&#34;]` instead.
     * 
     */
    @Deprecated /* This field is deprecated and will be removed in a future version. Use `dsn[""csp""]` instead. */
    @Import(name="dsnCsp")
    private @Nullable Output<String> dsnCsp;

    /**
     * @return Security header endpoint for features like CSP and Expect-CT reports. **Deprecated** Use `dsn[&#34;csp&#34;]` instead.
     * 
     * @deprecated
     * This field is deprecated and will be removed in a future version. Use `dsn[&#34;csp&#34;]` instead.
     * 
     */
    @Deprecated /* This field is deprecated and will be removed in a future version. Use `dsn[""csp""]` instead. */
    public Optional<Output<String>> dsnCsp() {
        return Optional.ofNullable(this.dsnCsp);
    }

    /**
     * The DSN tells the SDK where to send the events to. **Deprecated** Use `dsn[&#34;public&#34;]` instead.
     * 
     * @deprecated
     * This field is deprecated and will be removed in a future version. Use `dsn[&#34;public&#34;]` instead.
     * 
     */
    @Deprecated /* This field is deprecated and will be removed in a future version. Use `dsn[""public""]` instead. */
    @Import(name="dsnPublic")
    private @Nullable Output<String> dsnPublic;

    /**
     * @return The DSN tells the SDK where to send the events to. **Deprecated** Use `dsn[&#34;public&#34;]` instead.
     * 
     * @deprecated
     * This field is deprecated and will be removed in a future version. Use `dsn[&#34;public&#34;]` instead.
     * 
     */
    @Deprecated /* This field is deprecated and will be removed in a future version. Use `dsn[""public""]` instead. */
    public Optional<Output<String>> dsnPublic() {
        return Optional.ofNullable(this.dsnPublic);
    }

    /**
     * Deprecated DSN includes a secret which is no longer required by newer SDK versions. If you are unsure which to use, follow installation instructions for your language. **Deprecated** Use `dsn[&#34;secret&#34;] instead.
     * 
     * @deprecated
     * This field is deprecated and will be removed in a future version. Use `dsn[&#34;secret&#34;]` instead.
     * 
     */
    @Deprecated /* This field is deprecated and will be removed in a future version. Use `dsn[""secret""]` instead. */
    @Import(name="dsnSecret")
    private @Nullable Output<String> dsnSecret;

    /**
     * @return Deprecated DSN includes a secret which is no longer required by newer SDK versions. If you are unsure which to use, follow installation instructions for your language. **Deprecated** Use `dsn[&#34;secret&#34;] instead.
     * 
     * @deprecated
     * This field is deprecated and will be removed in a future version. Use `dsn[&#34;secret&#34;]` instead.
     * 
     */
    @Deprecated /* This field is deprecated and will be removed in a future version. Use `dsn[""secret""]` instead. */
    public Optional<Output<String>> dsnSecret() {
        return Optional.ofNullable(this.dsnSecret);
    }

    /**
     * The JavaScript loader script configuration.
     * 
     */
    @Import(name="javascriptLoaderScript")
    private @Nullable Output<SentryKeyJavascriptLoaderScriptArgs> javascriptLoaderScript;

    /**
     * @return The JavaScript loader script configuration.
     * 
     */
    public Optional<Output<SentryKeyJavascriptLoaderScriptArgs>> javascriptLoaderScript() {
        return Optional.ofNullable(this.javascriptLoaderScript);
    }

    /**
     * The name of the client key.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the client key.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The organization of this resource.
     * 
     */
    @Import(name="organization")
    private @Nullable Output<String> organization;

    /**
     * @return The organization of this resource.
     * 
     */
    public Optional<Output<String>> organization() {
        return Optional.ofNullable(this.organization);
    }

    /**
     * The project of this resource.
     * 
     */
    @Import(name="project")
    private @Nullable Output<String> project;

    /**
     * @return The project of this resource.
     * 
     */
    public Optional<Output<String>> project() {
        return Optional.ofNullable(this.project);
    }

    /**
     * The ID of the project that the key belongs to.
     * 
     */
    @Import(name="projectId")
    private @Nullable Output<String> projectId;

    /**
     * @return The ID of the project that the key belongs to.
     * 
     */
    public Optional<Output<String>> projectId() {
        return Optional.ofNullable(this.projectId);
    }

    /**
     * The public key.
     * 
     */
    @Import(name="public")
    private @Nullable Output<String> public_;

    /**
     * @return The public key.
     * 
     */
    public Optional<Output<String>> public_() {
        return Optional.ofNullable(this.public_);
    }

    /**
     * Number of events that can be reported within the rate limit window.
     * 
     */
    @Import(name="rateLimitCount")
    private @Nullable Output<Integer> rateLimitCount;

    /**
     * @return Number of events that can be reported within the rate limit window.
     * 
     */
    public Optional<Output<Integer>> rateLimitCount() {
        return Optional.ofNullable(this.rateLimitCount);
    }

    /**
     * Length of time in seconds that will be considered when checking the rate limit.
     * 
     */
    @Import(name="rateLimitWindow")
    private @Nullable Output<Integer> rateLimitWindow;

    /**
     * @return Length of time in seconds that will be considered when checking the rate limit.
     * 
     */
    public Optional<Output<Integer>> rateLimitWindow() {
        return Optional.ofNullable(this.rateLimitWindow);
    }

    /**
     * The secret key.
     * 
     */
    @Import(name="secret")
    private @Nullable Output<String> secret;

    /**
     * @return The secret key.
     * 
     */
    public Optional<Output<String>> secret() {
        return Optional.ofNullable(this.secret);
    }

    private SentryKeyState() {}

    private SentryKeyState(SentryKeyState $) {
        this.dsn = $.dsn;
        this.dsnCsp = $.dsnCsp;
        this.dsnPublic = $.dsnPublic;
        this.dsnSecret = $.dsnSecret;
        this.javascriptLoaderScript = $.javascriptLoaderScript;
        this.name = $.name;
        this.organization = $.organization;
        this.project = $.project;
        this.projectId = $.projectId;
        this.public_ = $.public_;
        this.rateLimitCount = $.rateLimitCount;
        this.rateLimitWindow = $.rateLimitWindow;
        this.secret = $.secret;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryKeyState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryKeyState $;

        public Builder() {
            $ = new SentryKeyState();
        }

        public Builder(SentryKeyState defaults) {
            $ = new SentryKeyState(Objects.requireNonNull(defaults));
        }

        /**
         * @param dsn This is a map of DSN values. The keys include `public`, `secret`, `csp`, `security`, `minidump`, `nel`, `unreal`, `cdn`, and `crons`.
         * 
         * @return builder
         * 
         */
        public Builder dsn(@Nullable Output<Map<String,String>> dsn) {
            $.dsn = dsn;
            return this;
        }

        /**
         * @param dsn This is a map of DSN values. The keys include `public`, `secret`, `csp`, `security`, `minidump`, `nel`, `unreal`, `cdn`, and `crons`.
         * 
         * @return builder
         * 
         */
        public Builder dsn(Map<String,String> dsn) {
            return dsn(Output.of(dsn));
        }

        /**
         * @param dsnCsp Security header endpoint for features like CSP and Expect-CT reports. **Deprecated** Use `dsn[&#34;csp&#34;]` instead.
         * 
         * @return builder
         * 
         * @deprecated
         * This field is deprecated and will be removed in a future version. Use `dsn[&#34;csp&#34;]` instead.
         * 
         */
        @Deprecated /* This field is deprecated and will be removed in a future version. Use `dsn[""csp""]` instead. */
        public Builder dsnCsp(@Nullable Output<String> dsnCsp) {
            $.dsnCsp = dsnCsp;
            return this;
        }

        /**
         * @param dsnCsp Security header endpoint for features like CSP and Expect-CT reports. **Deprecated** Use `dsn[&#34;csp&#34;]` instead.
         * 
         * @return builder
         * 
         * @deprecated
         * This field is deprecated and will be removed in a future version. Use `dsn[&#34;csp&#34;]` instead.
         * 
         */
        @Deprecated /* This field is deprecated and will be removed in a future version. Use `dsn[""csp""]` instead. */
        public Builder dsnCsp(String dsnCsp) {
            return dsnCsp(Output.of(dsnCsp));
        }

        /**
         * @param dsnPublic The DSN tells the SDK where to send the events to. **Deprecated** Use `dsn[&#34;public&#34;]` instead.
         * 
         * @return builder
         * 
         * @deprecated
         * This field is deprecated and will be removed in a future version. Use `dsn[&#34;public&#34;]` instead.
         * 
         */
        @Deprecated /* This field is deprecated and will be removed in a future version. Use `dsn[""public""]` instead. */
        public Builder dsnPublic(@Nullable Output<String> dsnPublic) {
            $.dsnPublic = dsnPublic;
            return this;
        }

        /**
         * @param dsnPublic The DSN tells the SDK where to send the events to. **Deprecated** Use `dsn[&#34;public&#34;]` instead.
         * 
         * @return builder
         * 
         * @deprecated
         * This field is deprecated and will be removed in a future version. Use `dsn[&#34;public&#34;]` instead.
         * 
         */
        @Deprecated /* This field is deprecated and will be removed in a future version. Use `dsn[""public""]` instead. */
        public Builder dsnPublic(String dsnPublic) {
            return dsnPublic(Output.of(dsnPublic));
        }

        /**
         * @param dsnSecret Deprecated DSN includes a secret which is no longer required by newer SDK versions. If you are unsure which to use, follow installation instructions for your language. **Deprecated** Use `dsn[&#34;secret&#34;] instead.
         * 
         * @return builder
         * 
         * @deprecated
         * This field is deprecated and will be removed in a future version. Use `dsn[&#34;secret&#34;]` instead.
         * 
         */
        @Deprecated /* This field is deprecated and will be removed in a future version. Use `dsn[""secret""]` instead. */
        public Builder dsnSecret(@Nullable Output<String> dsnSecret) {
            $.dsnSecret = dsnSecret;
            return this;
        }

        /**
         * @param dsnSecret Deprecated DSN includes a secret which is no longer required by newer SDK versions. If you are unsure which to use, follow installation instructions for your language. **Deprecated** Use `dsn[&#34;secret&#34;] instead.
         * 
         * @return builder
         * 
         * @deprecated
         * This field is deprecated and will be removed in a future version. Use `dsn[&#34;secret&#34;]` instead.
         * 
         */
        @Deprecated /* This field is deprecated and will be removed in a future version. Use `dsn[""secret""]` instead. */
        public Builder dsnSecret(String dsnSecret) {
            return dsnSecret(Output.of(dsnSecret));
        }

        /**
         * @param javascriptLoaderScript The JavaScript loader script configuration.
         * 
         * @return builder
         * 
         */
        public Builder javascriptLoaderScript(@Nullable Output<SentryKeyJavascriptLoaderScriptArgs> javascriptLoaderScript) {
            $.javascriptLoaderScript = javascriptLoaderScript;
            return this;
        }

        /**
         * @param javascriptLoaderScript The JavaScript loader script configuration.
         * 
         * @return builder
         * 
         */
        public Builder javascriptLoaderScript(SentryKeyJavascriptLoaderScriptArgs javascriptLoaderScript) {
            return javascriptLoaderScript(Output.of(javascriptLoaderScript));
        }

        /**
         * @param name The name of the client key.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the client key.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param organization The organization of this resource.
         * 
         * @return builder
         * 
         */
        public Builder organization(@Nullable Output<String> organization) {
            $.organization = organization;
            return this;
        }

        /**
         * @param organization The organization of this resource.
         * 
         * @return builder
         * 
         */
        public Builder organization(String organization) {
            return organization(Output.of(organization));
        }

        /**
         * @param project The project of this resource.
         * 
         * @return builder
         * 
         */
        public Builder project(@Nullable Output<String> project) {
            $.project = project;
            return this;
        }

        /**
         * @param project The project of this resource.
         * 
         * @return builder
         * 
         */
        public Builder project(String project) {
            return project(Output.of(project));
        }

        /**
         * @param projectId The ID of the project that the key belongs to.
         * 
         * @return builder
         * 
         */
        public Builder projectId(@Nullable Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId The ID of the project that the key belongs to.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param public_ The public key.
         * 
         * @return builder
         * 
         */
        public Builder public_(@Nullable Output<String> public_) {
            $.public_ = public_;
            return this;
        }

        /**
         * @param public_ The public key.
         * 
         * @return builder
         * 
         */
        public Builder public_(String public_) {
            return public_(Output.of(public_));
        }

        /**
         * @param rateLimitCount Number of events that can be reported within the rate limit window.
         * 
         * @return builder
         * 
         */
        public Builder rateLimitCount(@Nullable Output<Integer> rateLimitCount) {
            $.rateLimitCount = rateLimitCount;
            return this;
        }

        /**
         * @param rateLimitCount Number of events that can be reported within the rate limit window.
         * 
         * @return builder
         * 
         */
        public Builder rateLimitCount(Integer rateLimitCount) {
            return rateLimitCount(Output.of(rateLimitCount));
        }

        /**
         * @param rateLimitWindow Length of time in seconds that will be considered when checking the rate limit.
         * 
         * @return builder
         * 
         */
        public Builder rateLimitWindow(@Nullable Output<Integer> rateLimitWindow) {
            $.rateLimitWindow = rateLimitWindow;
            return this;
        }

        /**
         * @param rateLimitWindow Length of time in seconds that will be considered when checking the rate limit.
         * 
         * @return builder
         * 
         */
        public Builder rateLimitWindow(Integer rateLimitWindow) {
            return rateLimitWindow(Output.of(rateLimitWindow));
        }

        /**
         * @param secret The secret key.
         * 
         * @return builder
         * 
         */
        public Builder secret(@Nullable Output<String> secret) {
            $.secret = secret;
            return this;
        }

        /**
         * @param secret The secret key.
         * 
         * @return builder
         * 
         */
        public Builder secret(String secret) {
            return secret(Output.of(secret));
        }

        public SentryKeyState build() {
            return $;
        }
    }

}
