// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs extends com.pulumi.resources.ResourceArgs {

    public static final SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs Empty = new SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs();

    @Import(name="account", required=true)
    private Output<String> account;

    public Output<String> account() {
        return this.account;
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="priority", required=true)
    private Output<String> priority;

    public Output<String> priority() {
        return this.priority;
    }

    @Import(name="team", required=true)
    private Output<String> team;

    public Output<String> team() {
        return this.team;
    }

    private SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs() {}

    private SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs(SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs $) {
        this.account = $.account;
        this.name = $.name;
        this.priority = $.priority;
        this.team = $.team;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs $;

        public Builder() {
            $ = new SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs();
        }

        public Builder(SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs defaults) {
            $ = new SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs(Objects.requireNonNull(defaults));
        }

        public Builder account(Output<String> account) {
            $.account = account;
            return this;
        }

        public Builder account(String account) {
            return account(Output.of(account));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder priority(Output<String> priority) {
            $.priority = priority;
            return this;
        }

        public Builder priority(String priority) {
            return priority(Output.of(priority));
        }

        public Builder team(Output<String> team) {
            $.team = team;
            return this;
        }

        public Builder team(String team) {
            return team(Output.of(team));
        }

        public SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs build() {
            if ($.account == null) {
                throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs", "account");
            }
            if ($.priority == null) {
                throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs", "priority");
            }
            if ($.team == null) {
                throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs", "team");
            }
            return $;
        }
    }

}
