// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SentryIssueAlertConditionsV2EventUniqueUserFrequencyArgs extends com.pulumi.resources.ResourceArgs {

    public static final SentryIssueAlertConditionsV2EventUniqueUserFrequencyArgs Empty = new SentryIssueAlertConditionsV2EventUniqueUserFrequencyArgs();

    /**
     * `m` for minutes, `h` for hours, `d` for days, and `w` for weeks. Valid values are: `5m`, `15m`, `1h`, `1d`, `1w`, and `30d`.
     * 
     */
    @Import(name="comparisonInterval")
    private @Nullable Output<String> comparisonInterval;

    /**
     * @return `m` for minutes, `h` for hours, `d` for days, and `w` for weeks. Valid values are: `5m`, `15m`, `1h`, `1d`, `1w`, and `30d`.
     * 
     */
    public Optional<Output<String>> comparisonInterval() {
        return Optional.ofNullable(this.comparisonInterval);
    }

    /**
     * Valid values are: `count`, and `percent`.
     * 
     */
    @Import(name="comparisonType", required=true)
    private Output<String> comparisonType;

    /**
     * @return Valid values are: `count`, and `percent`.
     * 
     */
    public Output<String> comparisonType() {
        return this.comparisonType;
    }

    /**
     * `m` for minutes, `h` for hours, `d` for days, and `w` for weeks. Valid values are: `1m`, `5m`, `15m`, `1h`, `1d`, `1w`, and `30d`.
     * 
     */
    @Import(name="interval")
    private @Nullable Output<String> interval;

    /**
     * @return `m` for minutes, `h` for hours, `d` for days, and `w` for weeks. Valid values are: `1m`, `5m`, `15m`, `1h`, `1d`, `1w`, and `30d`.
     * 
     */
    public Optional<Output<String>> interval() {
        return Optional.ofNullable(this.interval);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="value", required=true)
    private Output<Integer> value;

    public Output<Integer> value() {
        return this.value;
    }

    private SentryIssueAlertConditionsV2EventUniqueUserFrequencyArgs() {}

    private SentryIssueAlertConditionsV2EventUniqueUserFrequencyArgs(SentryIssueAlertConditionsV2EventUniqueUserFrequencyArgs $) {
        this.comparisonInterval = $.comparisonInterval;
        this.comparisonType = $.comparisonType;
        this.interval = $.interval;
        this.name = $.name;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryIssueAlertConditionsV2EventUniqueUserFrequencyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryIssueAlertConditionsV2EventUniqueUserFrequencyArgs $;

        public Builder() {
            $ = new SentryIssueAlertConditionsV2EventUniqueUserFrequencyArgs();
        }

        public Builder(SentryIssueAlertConditionsV2EventUniqueUserFrequencyArgs defaults) {
            $ = new SentryIssueAlertConditionsV2EventUniqueUserFrequencyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param comparisonInterval `m` for minutes, `h` for hours, `d` for days, and `w` for weeks. Valid values are: `5m`, `15m`, `1h`, `1d`, `1w`, and `30d`.
         * 
         * @return builder
         * 
         */
        public Builder comparisonInterval(@Nullable Output<String> comparisonInterval) {
            $.comparisonInterval = comparisonInterval;
            return this;
        }

        /**
         * @param comparisonInterval `m` for minutes, `h` for hours, `d` for days, and `w` for weeks. Valid values are: `5m`, `15m`, `1h`, `1d`, `1w`, and `30d`.
         * 
         * @return builder
         * 
         */
        public Builder comparisonInterval(String comparisonInterval) {
            return comparisonInterval(Output.of(comparisonInterval));
        }

        /**
         * @param comparisonType Valid values are: `count`, and `percent`.
         * 
         * @return builder
         * 
         */
        public Builder comparisonType(Output<String> comparisonType) {
            $.comparisonType = comparisonType;
            return this;
        }

        /**
         * @param comparisonType Valid values are: `count`, and `percent`.
         * 
         * @return builder
         * 
         */
        public Builder comparisonType(String comparisonType) {
            return comparisonType(Output.of(comparisonType));
        }

        /**
         * @param interval `m` for minutes, `h` for hours, `d` for days, and `w` for weeks. Valid values are: `1m`, `5m`, `15m`, `1h`, `1d`, `1w`, and `30d`.
         * 
         * @return builder
         * 
         */
        public Builder interval(@Nullable Output<String> interval) {
            $.interval = interval;
            return this;
        }

        /**
         * @param interval `m` for minutes, `h` for hours, `d` for days, and `w` for weeks. Valid values are: `1m`, `5m`, `15m`, `1h`, `1d`, `1w`, and `30d`.
         * 
         * @return builder
         * 
         */
        public Builder interval(String interval) {
            return interval(Output.of(interval));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder value(Output<Integer> value) {
            $.value = value;
            return this;
        }

        public Builder value(Integer value) {
            return value(Output.of(value));
        }

        public SentryIssueAlertConditionsV2EventUniqueUserFrequencyArgs build() {
            if ($.comparisonType == null) {
                throw new MissingRequiredPropertyException("SentryIssueAlertConditionsV2EventUniqueUserFrequencyArgs", "comparisonType");
            }
            if ($.value == null) {
                throw new MissingRequiredPropertyException("SentryIssueAlertConditionsV2EventUniqueUserFrequencyArgs", "value");
            }
            return $;
        }
    }

}
