// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SentryAllProjectsSpikeProtectionState extends com.pulumi.resources.ResourceArgs {

    public static final SentryAllProjectsSpikeProtectionState Empty = new SentryAllProjectsSpikeProtectionState();

    /**
     * Toggle the browser-extensions, localhost, filtered-transaction, or web-crawlers filter on or off for all projects.
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return Toggle the browser-extensions, localhost, filtered-transaction, or web-crawlers filter on or off for all projects.
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * The organization of this resource.
     * 
     */
    @Import(name="organization")
    private @Nullable Output<String> organization;

    /**
     * @return The organization of this resource.
     * 
     */
    public Optional<Output<String>> organization() {
        return Optional.ofNullable(this.organization);
    }

    /**
     * The slugs of the projects to enable or disable spike protection for.
     * 
     */
    @Import(name="projects")
    private @Nullable Output<List<String>> projects;

    /**
     * @return The slugs of the projects to enable or disable spike protection for.
     * 
     */
    public Optional<Output<List<String>>> projects() {
        return Optional.ofNullable(this.projects);
    }

    private SentryAllProjectsSpikeProtectionState() {}

    private SentryAllProjectsSpikeProtectionState(SentryAllProjectsSpikeProtectionState $) {
        this.enabled = $.enabled;
        this.organization = $.organization;
        this.projects = $.projects;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryAllProjectsSpikeProtectionState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryAllProjectsSpikeProtectionState $;

        public Builder() {
            $ = new SentryAllProjectsSpikeProtectionState();
        }

        public Builder(SentryAllProjectsSpikeProtectionState defaults) {
            $ = new SentryAllProjectsSpikeProtectionState(Objects.requireNonNull(defaults));
        }

        /**
         * @param enabled Toggle the browser-extensions, localhost, filtered-transaction, or web-crawlers filter on or off for all projects.
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Toggle the browser-extensions, localhost, filtered-transaction, or web-crawlers filter on or off for all projects.
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param organization The organization of this resource.
         * 
         * @return builder
         * 
         */
        public Builder organization(@Nullable Output<String> organization) {
            $.organization = organization;
            return this;
        }

        /**
         * @param organization The organization of this resource.
         * 
         * @return builder
         * 
         */
        public Builder organization(String organization) {
            return organization(Output.of(organization));
        }

        /**
         * @param projects The slugs of the projects to enable or disable spike protection for.
         * 
         * @return builder
         * 
         */
        public Builder projects(@Nullable Output<List<String>> projects) {
            $.projects = projects;
            return this;
        }

        /**
         * @param projects The slugs of the projects to enable or disable spike protection for.
         * 
         * @return builder
         * 
         */
        public Builder projects(List<String> projects) {
            return projects(Output.of(projects));
        }

        /**
         * @param projects The slugs of the projects to enable or disable spike protection for.
         * 
         * @return builder
         * 
         */
        public Builder projects(String... projects) {
            return projects(List.of(projects));
        }

        public SentryAllProjectsSpikeProtectionState build() {
            return $;
        }
    }

}
