// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SentryTeamState extends com.pulumi.resources.ResourceArgs {

    public static final SentryTeamState Empty = new SentryTeamState();

    @Import(name="hasAccess")
    private @Nullable Output<Boolean> hasAccess;

    public Optional<Output<Boolean>> hasAccess() {
        return Optional.ofNullable(this.hasAccess);
    }

    /**
     * The internal ID for this team.
     * 
     */
    @Import(name="internalId")
    private @Nullable Output<String> internalId;

    /**
     * @return The internal ID for this team.
     * 
     */
    public Optional<Output<String>> internalId() {
        return Optional.ofNullable(this.internalId);
    }

    @Import(name="isMember")
    private @Nullable Output<Boolean> isMember;

    public Optional<Output<Boolean>> isMember() {
        return Optional.ofNullable(this.isMember);
    }

    @Import(name="isPending")
    private @Nullable Output<Boolean> isPending;

    public Optional<Output<Boolean>> isPending() {
        return Optional.ofNullable(this.isPending);
    }

    /**
     * The name of the team.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the team.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The slug of the organization the team should be created for.
     * 
     */
    @Import(name="organization")
    private @Nullable Output<String> organization;

    /**
     * @return The slug of the organization the team should be created for.
     * 
     */
    public Optional<Output<String>> organization() {
        return Optional.ofNullable(this.organization);
    }

    /**
     * The optional slug for this team.
     * 
     */
    @Import(name="slug")
    private @Nullable Output<String> slug;

    /**
     * @return The optional slug for this team.
     * 
     */
    public Optional<Output<String>> slug() {
        return Optional.ofNullable(this.slug);
    }

    /**
     * Use `internal_id` instead.
     * 
     * @deprecated
     * Use `internal_id` instead.
     * 
     */
    @Deprecated /* Use `internal_id` instead. */
    @Import(name="teamId")
    private @Nullable Output<String> teamId;

    /**
     * @return Use `internal_id` instead.
     * 
     * @deprecated
     * Use `internal_id` instead.
     * 
     */
    @Deprecated /* Use `internal_id` instead. */
    public Optional<Output<String>> teamId() {
        return Optional.ofNullable(this.teamId);
    }

    private SentryTeamState() {}

    private SentryTeamState(SentryTeamState $) {
        this.hasAccess = $.hasAccess;
        this.internalId = $.internalId;
        this.isMember = $.isMember;
        this.isPending = $.isPending;
        this.name = $.name;
        this.organization = $.organization;
        this.slug = $.slug;
        this.teamId = $.teamId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryTeamState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryTeamState $;

        public Builder() {
            $ = new SentryTeamState();
        }

        public Builder(SentryTeamState defaults) {
            $ = new SentryTeamState(Objects.requireNonNull(defaults));
        }

        public Builder hasAccess(@Nullable Output<Boolean> hasAccess) {
            $.hasAccess = hasAccess;
            return this;
        }

        public Builder hasAccess(Boolean hasAccess) {
            return hasAccess(Output.of(hasAccess));
        }

        /**
         * @param internalId The internal ID for this team.
         * 
         * @return builder
         * 
         */
        public Builder internalId(@Nullable Output<String> internalId) {
            $.internalId = internalId;
            return this;
        }

        /**
         * @param internalId The internal ID for this team.
         * 
         * @return builder
         * 
         */
        public Builder internalId(String internalId) {
            return internalId(Output.of(internalId));
        }

        public Builder isMember(@Nullable Output<Boolean> isMember) {
            $.isMember = isMember;
            return this;
        }

        public Builder isMember(Boolean isMember) {
            return isMember(Output.of(isMember));
        }

        public Builder isPending(@Nullable Output<Boolean> isPending) {
            $.isPending = isPending;
            return this;
        }

        public Builder isPending(Boolean isPending) {
            return isPending(Output.of(isPending));
        }

        /**
         * @param name The name of the team.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the team.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param organization The slug of the organization the team should be created for.
         * 
         * @return builder
         * 
         */
        public Builder organization(@Nullable Output<String> organization) {
            $.organization = organization;
            return this;
        }

        /**
         * @param organization The slug of the organization the team should be created for.
         * 
         * @return builder
         * 
         */
        public Builder organization(String organization) {
            return organization(Output.of(organization));
        }

        /**
         * @param slug The optional slug for this team.
         * 
         * @return builder
         * 
         */
        public Builder slug(@Nullable Output<String> slug) {
            $.slug = slug;
            return this;
        }

        /**
         * @param slug The optional slug for this team.
         * 
         * @return builder
         * 
         */
        public Builder slug(String slug) {
            return slug(Output.of(slug));
        }

        /**
         * @param teamId Use `internal_id` instead.
         * 
         * @return builder
         * 
         * @deprecated
         * Use `internal_id` instead.
         * 
         */
        @Deprecated /* Use `internal_id` instead. */
        public Builder teamId(@Nullable Output<String> teamId) {
            $.teamId = teamId;
            return this;
        }

        /**
         * @param teamId Use `internal_id` instead.
         * 
         * @return builder
         * 
         * @deprecated
         * Use `internal_id` instead.
         * 
         */
        @Deprecated /* Use `internal_id` instead. */
        public Builder teamId(String teamId) {
            return teamId(Output.of(teamId));
        }

        public SentryTeamState build() {
            return $;
        }
    }

}
