// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.sentry.inputs.SentryProjectSymbolSourceLayoutArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SentryProjectSymbolSourceState extends com.pulumi.resources.ResourceArgs {

    public static final SentryProjectSymbolSourceState Empty = new SentryProjectSymbolSourceState();

    /**
     * The AWS Access Key.Required for S3 sources, invalid for all others.
     * 
     */
    @Import(name="accessKey")
    private @Nullable Output<String> accessKey;

    /**
     * @return The AWS Access Key.Required for S3 sources, invalid for all others.
     * 
     */
    public Optional<Output<String>> accessKey() {
        return Optional.ofNullable(this.accessKey);
    }

    /**
     * The App Store Connect Issuer ID. Required for AppStoreConnect sources, invalid for all others.
     * 
     */
    @Import(name="appConnectIssuer")
    private @Nullable Output<String> appConnectIssuer;

    /**
     * @return The App Store Connect Issuer ID. Required for AppStoreConnect sources, invalid for all others.
     * 
     */
    public Optional<Output<String>> appConnectIssuer() {
        return Optional.ofNullable(this.appConnectIssuer);
    }

    /**
     * The App Store Connect API Private Key. Required for AppStoreConnect sources, invalid for all others.
     * 
     */
    @Import(name="appConnectPrivateKey")
    private @Nullable Output<String> appConnectPrivateKey;

    /**
     * @return The App Store Connect API Private Key. Required for AppStoreConnect sources, invalid for all others.
     * 
     */
    public Optional<Output<String>> appConnectPrivateKey() {
        return Optional.ofNullable(this.appConnectPrivateKey);
    }

    /**
     * The App Store Connect App ID. Required for AppStoreConnect sources, invalid for all others.
     * 
     */
    @Import(name="appId")
    private @Nullable Output<String> appId;

    /**
     * @return The App Store Connect App ID. Required for AppStoreConnect sources, invalid for all others.
     * 
     */
    public Optional<Output<String>> appId() {
        return Optional.ofNullable(this.appId);
    }

    /**
     * The GCS or S3 bucket where the source resides. Required for GCS and S3 sourcse, invalid for HTTP and AppStoreConnect sources.
     * 
     */
    @Import(name="bucket")
    private @Nullable Output<String> bucket;

    /**
     * @return The GCS or S3 bucket where the source resides. Required for GCS and S3 sourcse, invalid for HTTP and AppStoreConnect sources.
     * 
     */
    public Optional<Output<String>> bucket() {
        return Optional.ofNullable(this.bucket);
    }

    /**
     * The GCS email address for authentication. Required for GCS sources, invalid for all others.
     * 
     */
    @Import(name="clientEmail")
    private @Nullable Output<String> clientEmail;

    /**
     * @return The GCS email address for authentication. Required for GCS sources, invalid for all others.
     * 
     */
    public Optional<Output<String>> clientEmail() {
        return Optional.ofNullable(this.clientEmail);
    }

    /**
     * Layout settings for the source. This is required for HTTP, GCS, and S3 sources and invalid for AppStoreConnect sources.
     * 
     */
    @Import(name="layout")
    private @Nullable Output<SentryProjectSymbolSourceLayoutArgs> layout;

    /**
     * @return Layout settings for the source. This is required for HTTP, GCS, and S3 sources and invalid for AppStoreConnect sources.
     * 
     */
    public Optional<Output<SentryProjectSymbolSourceLayoutArgs>> layout() {
        return Optional.ofNullable(this.layout);
    }

    /**
     * The human-readable name of the source.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The human-readable name of the source.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * The organization of this resource.
     * 
     */
    @Import(name="organization")
    private @Nullable Output<String> organization;

    /**
     * @return The organization of this resource.
     * 
     */
    public Optional<Output<String>> organization() {
        return Optional.ofNullable(this.organization);
    }

    /**
     * The password for accessing the source. Optional for HTTP sources, invalid for all others.
     * 
     */
    @Import(name="password")
    private @Nullable Output<String> password;

    /**
     * @return The password for accessing the source. Optional for HTTP sources, invalid for all others.
     * 
     */
    public Optional<Output<String>> password() {
        return Optional.ofNullable(this.password);
    }

    /**
     * The GCS or S3 prefix. Optional for GCS and S3 sourcse, invalid for HTTP and AppStoreConnect sources.
     * 
     */
    @Import(name="prefix")
    private @Nullable Output<String> prefix;

    /**
     * @return The GCS or S3 prefix. Optional for GCS and S3 sourcse, invalid for HTTP and AppStoreConnect sources.
     * 
     */
    public Optional<Output<String>> prefix() {
        return Optional.ofNullable(this.prefix);
    }

    /**
     * The GCS private key. Required for GCS sources, invalid for all others.
     * 
     */
    @Import(name="privateKey")
    private @Nullable Output<String> privateKey;

    /**
     * @return The GCS private key. Required for GCS sources, invalid for all others.
     * 
     */
    public Optional<Output<String>> privateKey() {
        return Optional.ofNullable(this.privateKey);
    }

    /**
     * The project of this resource.
     * 
     */
    @Import(name="project")
    private @Nullable Output<String> project;

    /**
     * @return The project of this resource.
     * 
     */
    public Optional<Output<String>> project() {
        return Optional.ofNullable(this.project);
    }

    /**
     * The source&#39;s S3 region. Required for S3 sources, invalid for all others.
     * 
     */
    @Import(name="region")
    private @Nullable Output<String> region;

    /**
     * @return The source&#39;s S3 region. Required for S3 sources, invalid for all others.
     * 
     */
    public Optional<Output<String>> region() {
        return Optional.ofNullable(this.region);
    }

    /**
     * The AWS Secret Access Key.Required for S3 sources, invalid for all others.
     * 
     */
    @Import(name="secretKey")
    private @Nullable Output<String> secretKey;

    /**
     * @return The AWS Secret Access Key.Required for S3 sources, invalid for all others.
     * 
     */
    public Optional<Output<String>> secretKey() {
        return Optional.ofNullable(this.secretKey);
    }

    /**
     * The type of symbol source. One of `appStoreConnect` (App Store Connect), `http` (SymbolServer (HTTP)), `gcs` (Google Cloud Storage), `s3` (Amazon S3).
     * 
     */
    @Import(name="type")
    private @Nullable Output<String> type;

    /**
     * @return The type of symbol source. One of `appStoreConnect` (App Store Connect), `http` (SymbolServer (HTTP)), `gcs` (Google Cloud Storage), `s3` (Amazon S3).
     * 
     */
    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    /**
     * The source&#39;s URL. Optional for HTTP sources, invalid for all others.
     * 
     */
    @Import(name="url")
    private @Nullable Output<String> url;

    /**
     * @return The source&#39;s URL. Optional for HTTP sources, invalid for all others.
     * 
     */
    public Optional<Output<String>> url() {
        return Optional.ofNullable(this.url);
    }

    /**
     * The user name for accessing the source. Optional for HTTP sources, invalid for all others.
     * 
     */
    @Import(name="username")
    private @Nullable Output<String> username;

    /**
     * @return The user name for accessing the source. Optional for HTTP sources, invalid for all others.
     * 
     */
    public Optional<Output<String>> username() {
        return Optional.ofNullable(this.username);
    }

    private SentryProjectSymbolSourceState() {}

    private SentryProjectSymbolSourceState(SentryProjectSymbolSourceState $) {
        this.accessKey = $.accessKey;
        this.appConnectIssuer = $.appConnectIssuer;
        this.appConnectPrivateKey = $.appConnectPrivateKey;
        this.appId = $.appId;
        this.bucket = $.bucket;
        this.clientEmail = $.clientEmail;
        this.layout = $.layout;
        this.name = $.name;
        this.organization = $.organization;
        this.password = $.password;
        this.prefix = $.prefix;
        this.privateKey = $.privateKey;
        this.project = $.project;
        this.region = $.region;
        this.secretKey = $.secretKey;
        this.type = $.type;
        this.url = $.url;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryProjectSymbolSourceState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryProjectSymbolSourceState $;

        public Builder() {
            $ = new SentryProjectSymbolSourceState();
        }

        public Builder(SentryProjectSymbolSourceState defaults) {
            $ = new SentryProjectSymbolSourceState(Objects.requireNonNull(defaults));
        }

        /**
         * @param accessKey The AWS Access Key.Required for S3 sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder accessKey(@Nullable Output<String> accessKey) {
            $.accessKey = accessKey;
            return this;
        }

        /**
         * @param accessKey The AWS Access Key.Required for S3 sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder accessKey(String accessKey) {
            return accessKey(Output.of(accessKey));
        }

        /**
         * @param appConnectIssuer The App Store Connect Issuer ID. Required for AppStoreConnect sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder appConnectIssuer(@Nullable Output<String> appConnectIssuer) {
            $.appConnectIssuer = appConnectIssuer;
            return this;
        }

        /**
         * @param appConnectIssuer The App Store Connect Issuer ID. Required for AppStoreConnect sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder appConnectIssuer(String appConnectIssuer) {
            return appConnectIssuer(Output.of(appConnectIssuer));
        }

        /**
         * @param appConnectPrivateKey The App Store Connect API Private Key. Required for AppStoreConnect sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder appConnectPrivateKey(@Nullable Output<String> appConnectPrivateKey) {
            $.appConnectPrivateKey = appConnectPrivateKey;
            return this;
        }

        /**
         * @param appConnectPrivateKey The App Store Connect API Private Key. Required for AppStoreConnect sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder appConnectPrivateKey(String appConnectPrivateKey) {
            return appConnectPrivateKey(Output.of(appConnectPrivateKey));
        }

        /**
         * @param appId The App Store Connect App ID. Required for AppStoreConnect sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder appId(@Nullable Output<String> appId) {
            $.appId = appId;
            return this;
        }

        /**
         * @param appId The App Store Connect App ID. Required for AppStoreConnect sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder appId(String appId) {
            return appId(Output.of(appId));
        }

        /**
         * @param bucket The GCS or S3 bucket where the source resides. Required for GCS and S3 sourcse, invalid for HTTP and AppStoreConnect sources.
         * 
         * @return builder
         * 
         */
        public Builder bucket(@Nullable Output<String> bucket) {
            $.bucket = bucket;
            return this;
        }

        /**
         * @param bucket The GCS or S3 bucket where the source resides. Required for GCS and S3 sourcse, invalid for HTTP and AppStoreConnect sources.
         * 
         * @return builder
         * 
         */
        public Builder bucket(String bucket) {
            return bucket(Output.of(bucket));
        }

        /**
         * @param clientEmail The GCS email address for authentication. Required for GCS sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder clientEmail(@Nullable Output<String> clientEmail) {
            $.clientEmail = clientEmail;
            return this;
        }

        /**
         * @param clientEmail The GCS email address for authentication. Required for GCS sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder clientEmail(String clientEmail) {
            return clientEmail(Output.of(clientEmail));
        }

        /**
         * @param layout Layout settings for the source. This is required for HTTP, GCS, and S3 sources and invalid for AppStoreConnect sources.
         * 
         * @return builder
         * 
         */
        public Builder layout(@Nullable Output<SentryProjectSymbolSourceLayoutArgs> layout) {
            $.layout = layout;
            return this;
        }

        /**
         * @param layout Layout settings for the source. This is required for HTTP, GCS, and S3 sources and invalid for AppStoreConnect sources.
         * 
         * @return builder
         * 
         */
        public Builder layout(SentryProjectSymbolSourceLayoutArgs layout) {
            return layout(Output.of(layout));
        }

        /**
         * @param name The human-readable name of the source.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The human-readable name of the source.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param organization The organization of this resource.
         * 
         * @return builder
         * 
         */
        public Builder organization(@Nullable Output<String> organization) {
            $.organization = organization;
            return this;
        }

        /**
         * @param organization The organization of this resource.
         * 
         * @return builder
         * 
         */
        public Builder organization(String organization) {
            return organization(Output.of(organization));
        }

        /**
         * @param password The password for accessing the source. Optional for HTTP sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder password(@Nullable Output<String> password) {
            $.password = password;
            return this;
        }

        /**
         * @param password The password for accessing the source. Optional for HTTP sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder password(String password) {
            return password(Output.of(password));
        }

        /**
         * @param prefix The GCS or S3 prefix. Optional for GCS and S3 sourcse, invalid for HTTP and AppStoreConnect sources.
         * 
         * @return builder
         * 
         */
        public Builder prefix(@Nullable Output<String> prefix) {
            $.prefix = prefix;
            return this;
        }

        /**
         * @param prefix The GCS or S3 prefix. Optional for GCS and S3 sourcse, invalid for HTTP and AppStoreConnect sources.
         * 
         * @return builder
         * 
         */
        public Builder prefix(String prefix) {
            return prefix(Output.of(prefix));
        }

        /**
         * @param privateKey The GCS private key. Required for GCS sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder privateKey(@Nullable Output<String> privateKey) {
            $.privateKey = privateKey;
            return this;
        }

        /**
         * @param privateKey The GCS private key. Required for GCS sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder privateKey(String privateKey) {
            return privateKey(Output.of(privateKey));
        }

        /**
         * @param project The project of this resource.
         * 
         * @return builder
         * 
         */
        public Builder project(@Nullable Output<String> project) {
            $.project = project;
            return this;
        }

        /**
         * @param project The project of this resource.
         * 
         * @return builder
         * 
         */
        public Builder project(String project) {
            return project(Output.of(project));
        }

        /**
         * @param region The source&#39;s S3 region. Required for S3 sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder region(@Nullable Output<String> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region The source&#39;s S3 region. Required for S3 sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            return region(Output.of(region));
        }

        /**
         * @param secretKey The AWS Secret Access Key.Required for S3 sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder secretKey(@Nullable Output<String> secretKey) {
            $.secretKey = secretKey;
            return this;
        }

        /**
         * @param secretKey The AWS Secret Access Key.Required for S3 sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder secretKey(String secretKey) {
            return secretKey(Output.of(secretKey));
        }

        /**
         * @param type The type of symbol source. One of `appStoreConnect` (App Store Connect), `http` (SymbolServer (HTTP)), `gcs` (Google Cloud Storage), `s3` (Amazon S3).
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type The type of symbol source. One of `appStoreConnect` (App Store Connect), `http` (SymbolServer (HTTP)), `gcs` (Google Cloud Storage), `s3` (Amazon S3).
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        /**
         * @param url The source&#39;s URL. Optional for HTTP sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder url(@Nullable Output<String> url) {
            $.url = url;
            return this;
        }

        /**
         * @param url The source&#39;s URL. Optional for HTTP sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder url(String url) {
            return url(Output.of(url));
        }

        /**
         * @param username The user name for accessing the source. Optional for HTTP sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder username(@Nullable Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username The user name for accessing the source. Optional for HTTP sources, invalid for all others.
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public SentryProjectSymbolSourceState build() {
            return $;
        }
    }

}
