// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.sentry.inputs.SentryIssueAlertActionsV2AzureDevopsCreateTicketArgs;
import com.pulumi.sentry.inputs.SentryIssueAlertActionsV2DiscordNotifyServiceArgs;
import com.pulumi.sentry.inputs.SentryIssueAlertActionsV2GithubCreateTicketArgs;
import com.pulumi.sentry.inputs.SentryIssueAlertActionsV2GithubEnterpriseCreateTicketArgs;
import com.pulumi.sentry.inputs.SentryIssueAlertActionsV2JiraCreateTicketArgs;
import com.pulumi.sentry.inputs.SentryIssueAlertActionsV2JiraServerCreateTicketArgs;
import com.pulumi.sentry.inputs.SentryIssueAlertActionsV2MsteamsNotifyServiceArgs;
import com.pulumi.sentry.inputs.SentryIssueAlertActionsV2NotifyEmailArgs;
import com.pulumi.sentry.inputs.SentryIssueAlertActionsV2NotifyEventArgs;
import com.pulumi.sentry.inputs.SentryIssueAlertActionsV2NotifyEventSentryAppArgs;
import com.pulumi.sentry.inputs.SentryIssueAlertActionsV2NotifyEventServiceArgs;
import com.pulumi.sentry.inputs.SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs;
import com.pulumi.sentry.inputs.SentryIssueAlertActionsV2PagerdutyNotifyServiceArgs;
import com.pulumi.sentry.inputs.SentryIssueAlertActionsV2SlackNotifyServiceArgs;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SentryIssueAlertActionsV2Args extends com.pulumi.resources.ResourceArgs {

    public static final SentryIssueAlertActionsV2Args Empty = new SentryIssueAlertActionsV2Args();

    /**
     * Create an Azure DevOps work item in `integration`.
     * 
     */
    @Import(name="azureDevopsCreateTicket")
    private @Nullable Output<SentryIssueAlertActionsV2AzureDevopsCreateTicketArgs> azureDevopsCreateTicket;

    /**
     * @return Create an Azure DevOps work item in `integration`.
     * 
     */
    public Optional<Output<SentryIssueAlertActionsV2AzureDevopsCreateTicketArgs>> azureDevopsCreateTicket() {
        return Optional.ofNullable(this.azureDevopsCreateTicket);
    }

    /**
     * Send a notification to the `server` Discord server in the channel with ID or URL: `channel_id` and show tags `tags` in the notification.
     * 
     */
    @Import(name="discordNotifyService")
    private @Nullable Output<SentryIssueAlertActionsV2DiscordNotifyServiceArgs> discordNotifyService;

    /**
     * @return Send a notification to the `server` Discord server in the channel with ID or URL: `channel_id` and show tags `tags` in the notification.
     * 
     */
    public Optional<Output<SentryIssueAlertActionsV2DiscordNotifyServiceArgs>> discordNotifyService() {
        return Optional.ofNullable(this.discordNotifyService);
    }

    /**
     * Create a GitHub issue in `integration`.
     * 
     */
    @Import(name="githubCreateTicket")
    private @Nullable Output<SentryIssueAlertActionsV2GithubCreateTicketArgs> githubCreateTicket;

    /**
     * @return Create a GitHub issue in `integration`.
     * 
     */
    public Optional<Output<SentryIssueAlertActionsV2GithubCreateTicketArgs>> githubCreateTicket() {
        return Optional.ofNullable(this.githubCreateTicket);
    }

    /**
     * Create a GitHub Enterprise issue in `integration`.
     * 
     */
    @Import(name="githubEnterpriseCreateTicket")
    private @Nullable Output<SentryIssueAlertActionsV2GithubEnterpriseCreateTicketArgs> githubEnterpriseCreateTicket;

    /**
     * @return Create a GitHub Enterprise issue in `integration`.
     * 
     */
    public Optional<Output<SentryIssueAlertActionsV2GithubEnterpriseCreateTicketArgs>> githubEnterpriseCreateTicket() {
        return Optional.ofNullable(this.githubEnterpriseCreateTicket);
    }

    /**
     * Create a Jira issue in `integration`.
     * 
     */
    @Import(name="jiraCreateTicket")
    private @Nullable Output<SentryIssueAlertActionsV2JiraCreateTicketArgs> jiraCreateTicket;

    /**
     * @return Create a Jira issue in `integration`.
     * 
     */
    public Optional<Output<SentryIssueAlertActionsV2JiraCreateTicketArgs>> jiraCreateTicket() {
        return Optional.ofNullable(this.jiraCreateTicket);
    }

    /**
     * Create a Jira Server issue in `integration`.
     * 
     */
    @Import(name="jiraServerCreateTicket")
    private @Nullable Output<SentryIssueAlertActionsV2JiraServerCreateTicketArgs> jiraServerCreateTicket;

    /**
     * @return Create a Jira Server issue in `integration`.
     * 
     */
    public Optional<Output<SentryIssueAlertActionsV2JiraServerCreateTicketArgs>> jiraServerCreateTicket() {
        return Optional.ofNullable(this.jiraServerCreateTicket);
    }

    /**
     * Send a notification to the `team` Team to `channel`.
     * 
     */
    @Import(name="msteamsNotifyService")
    private @Nullable Output<SentryIssueAlertActionsV2MsteamsNotifyServiceArgs> msteamsNotifyService;

    /**
     * @return Send a notification to the `team` Team to `channel`.
     * 
     */
    public Optional<Output<SentryIssueAlertActionsV2MsteamsNotifyServiceArgs>> msteamsNotifyService() {
        return Optional.ofNullable(this.msteamsNotifyService);
    }

    /**
     * Send a notification to `target_type` and if none can be found then send a notification to `fallthrough_type`.
     * 
     */
    @Import(name="notifyEmail")
    private @Nullable Output<SentryIssueAlertActionsV2NotifyEmailArgs> notifyEmail;

    /**
     * @return Send a notification to `target_type` and if none can be found then send a notification to `fallthrough_type`.
     * 
     */
    public Optional<Output<SentryIssueAlertActionsV2NotifyEmailArgs>> notifyEmail() {
        return Optional.ofNullable(this.notifyEmail);
    }

    /**
     * Send a notification to all legacy integrations.
     * 
     */
    @Import(name="notifyEvent")
    private @Nullable Output<SentryIssueAlertActionsV2NotifyEventArgs> notifyEvent;

    /**
     * @return Send a notification to all legacy integrations.
     * 
     */
    public Optional<Output<SentryIssueAlertActionsV2NotifyEventArgs>> notifyEvent() {
        return Optional.ofNullable(this.notifyEvent);
    }

    /**
     * Send a notification to a Sentry app.
     * 
     */
    @Import(name="notifyEventSentryApp")
    private @Nullable Output<SentryIssueAlertActionsV2NotifyEventSentryAppArgs> notifyEventSentryApp;

    /**
     * @return Send a notification to a Sentry app.
     * 
     */
    public Optional<Output<SentryIssueAlertActionsV2NotifyEventSentryAppArgs>> notifyEventSentryApp() {
        return Optional.ofNullable(this.notifyEventSentryApp);
    }

    /**
     * Send a notification via an integration.
     * 
     */
    @Import(name="notifyEventService")
    private @Nullable Output<SentryIssueAlertActionsV2NotifyEventServiceArgs> notifyEventService;

    /**
     * @return Send a notification via an integration.
     * 
     */
    public Optional<Output<SentryIssueAlertActionsV2NotifyEventServiceArgs>> notifyEventService() {
        return Optional.ofNullable(this.notifyEventService);
    }

    /**
     * Send a notification to Opsgenie account `account` and team `team` with `priority` priority.
     * 
     */
    @Import(name="opsgenieNotifyTeam")
    private @Nullable Output<SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs> opsgenieNotifyTeam;

    /**
     * @return Send a notification to Opsgenie account `account` and team `team` with `priority` priority.
     * 
     */
    public Optional<Output<SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs>> opsgenieNotifyTeam() {
        return Optional.ofNullable(this.opsgenieNotifyTeam);
    }

    /**
     * Send a notification to PagerDuty account `account` and service `service` with `severity` severity.
     * 
     */
    @Import(name="pagerdutyNotifyService")
    private @Nullable Output<SentryIssueAlertActionsV2PagerdutyNotifyServiceArgs> pagerdutyNotifyService;

    /**
     * @return Send a notification to PagerDuty account `account` and service `service` with `severity` severity.
     * 
     */
    public Optional<Output<SentryIssueAlertActionsV2PagerdutyNotifyServiceArgs>> pagerdutyNotifyService() {
        return Optional.ofNullable(this.pagerdutyNotifyService);
    }

    /**
     * Send a notification to the `workspace` Slack workspace to `channel` (optionally, an ID: `channel_id`) and show tags `tags` and notes `notes` in notification.
     * 
     */
    @Import(name="slackNotifyService")
    private @Nullable Output<SentryIssueAlertActionsV2SlackNotifyServiceArgs> slackNotifyService;

    /**
     * @return Send a notification to the `workspace` Slack workspace to `channel` (optionally, an ID: `channel_id`) and show tags `tags` and notes `notes` in notification.
     * 
     */
    public Optional<Output<SentryIssueAlertActionsV2SlackNotifyServiceArgs>> slackNotifyService() {
        return Optional.ofNullable(this.slackNotifyService);
    }

    private SentryIssueAlertActionsV2Args() {}

    private SentryIssueAlertActionsV2Args(SentryIssueAlertActionsV2Args $) {
        this.azureDevopsCreateTicket = $.azureDevopsCreateTicket;
        this.discordNotifyService = $.discordNotifyService;
        this.githubCreateTicket = $.githubCreateTicket;
        this.githubEnterpriseCreateTicket = $.githubEnterpriseCreateTicket;
        this.jiraCreateTicket = $.jiraCreateTicket;
        this.jiraServerCreateTicket = $.jiraServerCreateTicket;
        this.msteamsNotifyService = $.msteamsNotifyService;
        this.notifyEmail = $.notifyEmail;
        this.notifyEvent = $.notifyEvent;
        this.notifyEventSentryApp = $.notifyEventSentryApp;
        this.notifyEventService = $.notifyEventService;
        this.opsgenieNotifyTeam = $.opsgenieNotifyTeam;
        this.pagerdutyNotifyService = $.pagerdutyNotifyService;
        this.slackNotifyService = $.slackNotifyService;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryIssueAlertActionsV2Args defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryIssueAlertActionsV2Args $;

        public Builder() {
            $ = new SentryIssueAlertActionsV2Args();
        }

        public Builder(SentryIssueAlertActionsV2Args defaults) {
            $ = new SentryIssueAlertActionsV2Args(Objects.requireNonNull(defaults));
        }

        /**
         * @param azureDevopsCreateTicket Create an Azure DevOps work item in `integration`.
         * 
         * @return builder
         * 
         */
        public Builder azureDevopsCreateTicket(@Nullable Output<SentryIssueAlertActionsV2AzureDevopsCreateTicketArgs> azureDevopsCreateTicket) {
            $.azureDevopsCreateTicket = azureDevopsCreateTicket;
            return this;
        }

        /**
         * @param azureDevopsCreateTicket Create an Azure DevOps work item in `integration`.
         * 
         * @return builder
         * 
         */
        public Builder azureDevopsCreateTicket(SentryIssueAlertActionsV2AzureDevopsCreateTicketArgs azureDevopsCreateTicket) {
            return azureDevopsCreateTicket(Output.of(azureDevopsCreateTicket));
        }

        /**
         * @param discordNotifyService Send a notification to the `server` Discord server in the channel with ID or URL: `channel_id` and show tags `tags` in the notification.
         * 
         * @return builder
         * 
         */
        public Builder discordNotifyService(@Nullable Output<SentryIssueAlertActionsV2DiscordNotifyServiceArgs> discordNotifyService) {
            $.discordNotifyService = discordNotifyService;
            return this;
        }

        /**
         * @param discordNotifyService Send a notification to the `server` Discord server in the channel with ID or URL: `channel_id` and show tags `tags` in the notification.
         * 
         * @return builder
         * 
         */
        public Builder discordNotifyService(SentryIssueAlertActionsV2DiscordNotifyServiceArgs discordNotifyService) {
            return discordNotifyService(Output.of(discordNotifyService));
        }

        /**
         * @param githubCreateTicket Create a GitHub issue in `integration`.
         * 
         * @return builder
         * 
         */
        public Builder githubCreateTicket(@Nullable Output<SentryIssueAlertActionsV2GithubCreateTicketArgs> githubCreateTicket) {
            $.githubCreateTicket = githubCreateTicket;
            return this;
        }

        /**
         * @param githubCreateTicket Create a GitHub issue in `integration`.
         * 
         * @return builder
         * 
         */
        public Builder githubCreateTicket(SentryIssueAlertActionsV2GithubCreateTicketArgs githubCreateTicket) {
            return githubCreateTicket(Output.of(githubCreateTicket));
        }

        /**
         * @param githubEnterpriseCreateTicket Create a GitHub Enterprise issue in `integration`.
         * 
         * @return builder
         * 
         */
        public Builder githubEnterpriseCreateTicket(@Nullable Output<SentryIssueAlertActionsV2GithubEnterpriseCreateTicketArgs> githubEnterpriseCreateTicket) {
            $.githubEnterpriseCreateTicket = githubEnterpriseCreateTicket;
            return this;
        }

        /**
         * @param githubEnterpriseCreateTicket Create a GitHub Enterprise issue in `integration`.
         * 
         * @return builder
         * 
         */
        public Builder githubEnterpriseCreateTicket(SentryIssueAlertActionsV2GithubEnterpriseCreateTicketArgs githubEnterpriseCreateTicket) {
            return githubEnterpriseCreateTicket(Output.of(githubEnterpriseCreateTicket));
        }

        /**
         * @param jiraCreateTicket Create a Jira issue in `integration`.
         * 
         * @return builder
         * 
         */
        public Builder jiraCreateTicket(@Nullable Output<SentryIssueAlertActionsV2JiraCreateTicketArgs> jiraCreateTicket) {
            $.jiraCreateTicket = jiraCreateTicket;
            return this;
        }

        /**
         * @param jiraCreateTicket Create a Jira issue in `integration`.
         * 
         * @return builder
         * 
         */
        public Builder jiraCreateTicket(SentryIssueAlertActionsV2JiraCreateTicketArgs jiraCreateTicket) {
            return jiraCreateTicket(Output.of(jiraCreateTicket));
        }

        /**
         * @param jiraServerCreateTicket Create a Jira Server issue in `integration`.
         * 
         * @return builder
         * 
         */
        public Builder jiraServerCreateTicket(@Nullable Output<SentryIssueAlertActionsV2JiraServerCreateTicketArgs> jiraServerCreateTicket) {
            $.jiraServerCreateTicket = jiraServerCreateTicket;
            return this;
        }

        /**
         * @param jiraServerCreateTicket Create a Jira Server issue in `integration`.
         * 
         * @return builder
         * 
         */
        public Builder jiraServerCreateTicket(SentryIssueAlertActionsV2JiraServerCreateTicketArgs jiraServerCreateTicket) {
            return jiraServerCreateTicket(Output.of(jiraServerCreateTicket));
        }

        /**
         * @param msteamsNotifyService Send a notification to the `team` Team to `channel`.
         * 
         * @return builder
         * 
         */
        public Builder msteamsNotifyService(@Nullable Output<SentryIssueAlertActionsV2MsteamsNotifyServiceArgs> msteamsNotifyService) {
            $.msteamsNotifyService = msteamsNotifyService;
            return this;
        }

        /**
         * @param msteamsNotifyService Send a notification to the `team` Team to `channel`.
         * 
         * @return builder
         * 
         */
        public Builder msteamsNotifyService(SentryIssueAlertActionsV2MsteamsNotifyServiceArgs msteamsNotifyService) {
            return msteamsNotifyService(Output.of(msteamsNotifyService));
        }

        /**
         * @param notifyEmail Send a notification to `target_type` and if none can be found then send a notification to `fallthrough_type`.
         * 
         * @return builder
         * 
         */
        public Builder notifyEmail(@Nullable Output<SentryIssueAlertActionsV2NotifyEmailArgs> notifyEmail) {
            $.notifyEmail = notifyEmail;
            return this;
        }

        /**
         * @param notifyEmail Send a notification to `target_type` and if none can be found then send a notification to `fallthrough_type`.
         * 
         * @return builder
         * 
         */
        public Builder notifyEmail(SentryIssueAlertActionsV2NotifyEmailArgs notifyEmail) {
            return notifyEmail(Output.of(notifyEmail));
        }

        /**
         * @param notifyEvent Send a notification to all legacy integrations.
         * 
         * @return builder
         * 
         */
        public Builder notifyEvent(@Nullable Output<SentryIssueAlertActionsV2NotifyEventArgs> notifyEvent) {
            $.notifyEvent = notifyEvent;
            return this;
        }

        /**
         * @param notifyEvent Send a notification to all legacy integrations.
         * 
         * @return builder
         * 
         */
        public Builder notifyEvent(SentryIssueAlertActionsV2NotifyEventArgs notifyEvent) {
            return notifyEvent(Output.of(notifyEvent));
        }

        /**
         * @param notifyEventSentryApp Send a notification to a Sentry app.
         * 
         * @return builder
         * 
         */
        public Builder notifyEventSentryApp(@Nullable Output<SentryIssueAlertActionsV2NotifyEventSentryAppArgs> notifyEventSentryApp) {
            $.notifyEventSentryApp = notifyEventSentryApp;
            return this;
        }

        /**
         * @param notifyEventSentryApp Send a notification to a Sentry app.
         * 
         * @return builder
         * 
         */
        public Builder notifyEventSentryApp(SentryIssueAlertActionsV2NotifyEventSentryAppArgs notifyEventSentryApp) {
            return notifyEventSentryApp(Output.of(notifyEventSentryApp));
        }

        /**
         * @param notifyEventService Send a notification via an integration.
         * 
         * @return builder
         * 
         */
        public Builder notifyEventService(@Nullable Output<SentryIssueAlertActionsV2NotifyEventServiceArgs> notifyEventService) {
            $.notifyEventService = notifyEventService;
            return this;
        }

        /**
         * @param notifyEventService Send a notification via an integration.
         * 
         * @return builder
         * 
         */
        public Builder notifyEventService(SentryIssueAlertActionsV2NotifyEventServiceArgs notifyEventService) {
            return notifyEventService(Output.of(notifyEventService));
        }

        /**
         * @param opsgenieNotifyTeam Send a notification to Opsgenie account `account` and team `team` with `priority` priority.
         * 
         * @return builder
         * 
         */
        public Builder opsgenieNotifyTeam(@Nullable Output<SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs> opsgenieNotifyTeam) {
            $.opsgenieNotifyTeam = opsgenieNotifyTeam;
            return this;
        }

        /**
         * @param opsgenieNotifyTeam Send a notification to Opsgenie account `account` and team `team` with `priority` priority.
         * 
         * @return builder
         * 
         */
        public Builder opsgenieNotifyTeam(SentryIssueAlertActionsV2OpsgenieNotifyTeamArgs opsgenieNotifyTeam) {
            return opsgenieNotifyTeam(Output.of(opsgenieNotifyTeam));
        }

        /**
         * @param pagerdutyNotifyService Send a notification to PagerDuty account `account` and service `service` with `severity` severity.
         * 
         * @return builder
         * 
         */
        public Builder pagerdutyNotifyService(@Nullable Output<SentryIssueAlertActionsV2PagerdutyNotifyServiceArgs> pagerdutyNotifyService) {
            $.pagerdutyNotifyService = pagerdutyNotifyService;
            return this;
        }

        /**
         * @param pagerdutyNotifyService Send a notification to PagerDuty account `account` and service `service` with `severity` severity.
         * 
         * @return builder
         * 
         */
        public Builder pagerdutyNotifyService(SentryIssueAlertActionsV2PagerdutyNotifyServiceArgs pagerdutyNotifyService) {
            return pagerdutyNotifyService(Output.of(pagerdutyNotifyService));
        }

        /**
         * @param slackNotifyService Send a notification to the `workspace` Slack workspace to `channel` (optionally, an ID: `channel_id`) and show tags `tags` and notes `notes` in notification.
         * 
         * @return builder
         * 
         */
        public Builder slackNotifyService(@Nullable Output<SentryIssueAlertActionsV2SlackNotifyServiceArgs> slackNotifyService) {
            $.slackNotifyService = slackNotifyService;
            return this;
        }

        /**
         * @param slackNotifyService Send a notification to the `workspace` Slack workspace to `channel` (optionally, an ID: `channel_id`) and show tags `tags` and notes `notes` in notification.
         * 
         * @return builder
         * 
         */
        public Builder slackNotifyService(SentryIssueAlertActionsV2SlackNotifyServiceArgs slackNotifyService) {
            return slackNotifyService(Output.of(slackNotifyService));
        }

        public SentryIssueAlertActionsV2Args build() {
            return $;
        }
    }

}
