// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Sentry
{
    public static class GetSentryAllOrganizationMembers
    {
        /// <summary>
        /// Retrieve all organization members.
        /// </summary>
        public static Task<GetSentryAllOrganizationMembersResult> InvokeAsync(GetSentryAllOrganizationMembersArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSentryAllOrganizationMembersResult>("sentry:index/getSentryAllOrganizationMembers:getSentryAllOrganizationMembers", args ?? new GetSentryAllOrganizationMembersArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieve all organization members.
        /// </summary>
        public static Output<GetSentryAllOrganizationMembersResult> Invoke(GetSentryAllOrganizationMembersInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSentryAllOrganizationMembersResult>("sentry:index/getSentryAllOrganizationMembers:getSentryAllOrganizationMembers", args ?? new GetSentryAllOrganizationMembersInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSentryAllOrganizationMembersArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The organization the resource belongs to.
        /// </summary>
        [Input("organization", required: true)]
        public string Organization { get; set; } = null!;

        public GetSentryAllOrganizationMembersArgs()
        {
        }
        public static new GetSentryAllOrganizationMembersArgs Empty => new GetSentryAllOrganizationMembersArgs();
    }

    public sealed class GetSentryAllOrganizationMembersInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The organization the resource belongs to.
        /// </summary>
        [Input("organization", required: true)]
        public Input<string> Organization { get; set; } = null!;

        public GetSentryAllOrganizationMembersInvokeArgs()
        {
        }
        public static new GetSentryAllOrganizationMembersInvokeArgs Empty => new GetSentryAllOrganizationMembersInvokeArgs();
    }


    [OutputType]
    public sealed class GetSentryAllOrganizationMembersResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The list of members.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetSentryAllOrganizationMembersMemberResult> Members;
        /// <summary>
        /// The organization the resource belongs to.
        /// </summary>
        public readonly string Organization;

        [OutputConstructor]
        private GetSentryAllOrganizationMembersResult(
            string id,

            ImmutableArray<Outputs.GetSentryAllOrganizationMembersMemberResult> members,

            string organization)
        {
            Id = id;
            Members = members;
            Organization = organization;
        }
    }
}
