// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class SentryIntegrationOpsgenieArgs extends com.pulumi.resources.ResourceArgs {

    public static final SentryIntegrationOpsgenieArgs Empty = new SentryIntegrationOpsgenieArgs();

    /**
     * The ID of the Opsgenie integration. Source from the URL `https://&lt;organization&gt;.sentry.io/settings/integrations/opsgenie/&lt;integration-id&gt;/` or use the `sentry.SentrygetOrganizationIntegration` data source.
     * 
     */
    @Import(name="integrationId", required=true)
    private Output<String> integrationId;

    /**
     * @return The ID of the Opsgenie integration. Source from the URL `https://&lt;organization&gt;.sentry.io/settings/integrations/opsgenie/&lt;integration-id&gt;/` or use the `sentry.SentrygetOrganizationIntegration` data source.
     * 
     */
    public Output<String> integrationId() {
        return this.integrationId;
    }

    /**
     * The integration key of the Opsgenie service.
     * 
     */
    @Import(name="integrationKey", required=true)
    private Output<String> integrationKey;

    /**
     * @return The integration key of the Opsgenie service.
     * 
     */
    public Output<String> integrationKey() {
        return this.integrationKey;
    }

    /**
     * The organization of this resource.
     * 
     */
    @Import(name="organization", required=true)
    private Output<String> organization;

    /**
     * @return The organization of this resource.
     * 
     */
    public Output<String> organization() {
        return this.organization;
    }

    /**
     * The name of the Opsgenie team. In Sentry, this is called Label.
     * 
     */
    @Import(name="team", required=true)
    private Output<String> team;

    /**
     * @return The name of the Opsgenie team. In Sentry, this is called Label.
     * 
     */
    public Output<String> team() {
        return this.team;
    }

    private SentryIntegrationOpsgenieArgs() {}

    private SentryIntegrationOpsgenieArgs(SentryIntegrationOpsgenieArgs $) {
        this.integrationId = $.integrationId;
        this.integrationKey = $.integrationKey;
        this.organization = $.organization;
        this.team = $.team;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryIntegrationOpsgenieArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryIntegrationOpsgenieArgs $;

        public Builder() {
            $ = new SentryIntegrationOpsgenieArgs();
        }

        public Builder(SentryIntegrationOpsgenieArgs defaults) {
            $ = new SentryIntegrationOpsgenieArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param integrationId The ID of the Opsgenie integration. Source from the URL `https://&lt;organization&gt;.sentry.io/settings/integrations/opsgenie/&lt;integration-id&gt;/` or use the `sentry.SentrygetOrganizationIntegration` data source.
         * 
         * @return builder
         * 
         */
        public Builder integrationId(Output<String> integrationId) {
            $.integrationId = integrationId;
            return this;
        }

        /**
         * @param integrationId The ID of the Opsgenie integration. Source from the URL `https://&lt;organization&gt;.sentry.io/settings/integrations/opsgenie/&lt;integration-id&gt;/` or use the `sentry.SentrygetOrganizationIntegration` data source.
         * 
         * @return builder
         * 
         */
        public Builder integrationId(String integrationId) {
            return integrationId(Output.of(integrationId));
        }

        /**
         * @param integrationKey The integration key of the Opsgenie service.
         * 
         * @return builder
         * 
         */
        public Builder integrationKey(Output<String> integrationKey) {
            $.integrationKey = integrationKey;
            return this;
        }

        /**
         * @param integrationKey The integration key of the Opsgenie service.
         * 
         * @return builder
         * 
         */
        public Builder integrationKey(String integrationKey) {
            return integrationKey(Output.of(integrationKey));
        }

        /**
         * @param organization The organization of this resource.
         * 
         * @return builder
         * 
         */
        public Builder organization(Output<String> organization) {
            $.organization = organization;
            return this;
        }

        /**
         * @param organization The organization of this resource.
         * 
         * @return builder
         * 
         */
        public Builder organization(String organization) {
            return organization(Output.of(organization));
        }

        /**
         * @param team The name of the Opsgenie team. In Sentry, this is called Label.
         * 
         * @return builder
         * 
         */
        public Builder team(Output<String> team) {
            $.team = team;
            return this;
        }

        /**
         * @param team The name of the Opsgenie team. In Sentry, this is called Label.
         * 
         * @return builder
         * 
         */
        public Builder team(String team) {
            return team(Output.of(team));
        }

        public SentryIntegrationOpsgenieArgs build() {
            if ($.integrationId == null) {
                throw new MissingRequiredPropertyException("SentryIntegrationOpsgenieArgs", "integrationId");
            }
            if ($.integrationKey == null) {
                throw new MissingRequiredPropertyException("SentryIntegrationOpsgenieArgs", "integrationKey");
            }
            if ($.organization == null) {
                throw new MissingRequiredPropertyException("SentryIntegrationOpsgenieArgs", "organization");
            }
            if ($.team == null) {
                throw new MissingRequiredPropertyException("SentryIntegrationOpsgenieArgs", "team");
            }
            return $;
        }
    }

}
