// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.sentry.SentryOrganizationCodeMappingArgs;
import com.pulumi.sentry.Utilities;
import com.pulumi.sentry.inputs.SentryOrganizationCodeMappingState;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Sentry Organization Code Mapping resource.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.sentry.SentryFunctions;
 * import com.pulumi.sentry.inputs.SentrygetOrganizationIntegrationArgs;
 * import com.pulumi.sentry.SentryProject;
 * import com.pulumi.sentry.SentryProjectArgs;
 * import com.pulumi.sentry.SentryOrganizationRepositoryGithub;
 * import com.pulumi.sentry.SentryOrganizationRepositoryGithubArgs;
 * import com.pulumi.sentry.SentryOrganizationCodeMapping;
 * import com.pulumi.sentry.SentryOrganizationCodeMappingArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         // Retrieve the Github organization integration
 *         final var github = SentryFunctions.SentrygetOrganizationIntegration(SentrygetOrganizationIntegrationArgs.builder()
 *             .organization("my-organization")
 *             .providerKey("github")
 *             .name("my-github-organization")
 *             .build());
 * 
 *         var this_ = new SentryProject("this", SentryProjectArgs.builder()
 *             .organization("my-organization")
 *             .teams("my-team")
 *             .name("Web App")
 *             .slug("web-app")
 *             .platform("javascript")
 *             .resolveAge(720)
 *             .build());
 * 
 *         var thisSentryOrganizationRepositoryGithub = new SentryOrganizationRepositoryGithub("thisSentryOrganizationRepositoryGithub", SentryOrganizationRepositoryGithubArgs.builder()
 *             .organization("my-organization")
 *             .integrationId(github.applyValue(sentrygetOrganizationIntegrationResult -> sentrygetOrganizationIntegrationResult.internalId()))
 *             .identifier("my-github-organization/my-github-repo")
 *             .build());
 * 
 *         var thisSentryOrganizationCodeMapping = new SentryOrganizationCodeMapping("thisSentryOrganizationCodeMapping", SentryOrganizationCodeMappingArgs.builder()
 *             .organization("my-organization")
 *             .integrationId(github.applyValue(sentrygetOrganizationIntegrationResult -> sentrygetOrganizationIntegrationResult.internalId()))
 *             .repositoryId(thisSentryOrganizationRepositoryGithub.internalId())
 *             .projectId(this_.internalId())
 *             .defaultBranch("main")
 *             .stackRoot("/")
 *             .sourceRoot("src/")
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * import using the organization slug from the URL:
 * 
 * https://sentry.io/settings/[org-slug]/integrations/github/[org-integration-id]/
 * 
 * and inspect network tab for request to https://sentry.io/api/0/organizations/[org-slug]/code-mappings/
 * 
 * find the corresponding list element and reference [code-mapping-id] from the key &#34;id&#34;
 * 
 * ```sh
 * $ pulumi import sentry:index/sentryOrganizationCodeMapping:SentryOrganizationCodeMapping this org-slug/31347
 * ```
 * 
 */
@ResourceType(type="sentry:index/sentryOrganizationCodeMapping:SentryOrganizationCodeMapping")
public class SentryOrganizationCodeMapping extends com.pulumi.resources.CustomResource {
    /**
     * Default branch of your code we fall back to if you do not have commit tracking set up.
     * 
     */
    @Export(name="defaultBranch", refs={String.class}, tree="[0]")
    private Output<String> defaultBranch;

    /**
     * @return Default branch of your code we fall back to if you do not have commit tracking set up.
     * 
     */
    public Output<String> defaultBranch() {
        return this.defaultBranch;
    }
    /**
     * Sentry Organization Integration ID.
     * 
     */
    @Export(name="integrationId", refs={String.class}, tree="[0]")
    private Output<String> integrationId;

    /**
     * @return Sentry Organization Integration ID.
     * 
     */
    public Output<String> integrationId() {
        return this.integrationId;
    }
    /**
     * The internal ID for this resource.
     * 
     */
    @Export(name="internalId", refs={String.class}, tree="[0]")
    private Output<String> internalId;

    /**
     * @return The internal ID for this resource.
     * 
     */
    public Output<String> internalId() {
        return this.internalId;
    }
    /**
     * The slug of the organization the code mapping is under.
     * 
     */
    @Export(name="organization", refs={String.class}, tree="[0]")
    private Output<String> organization;

    /**
     * @return The slug of the organization the code mapping is under.
     * 
     */
    public Output<String> organization() {
        return this.organization;
    }
    /**
     * Sentry Project ID.
     * 
     */
    @Export(name="projectId", refs={String.class}, tree="[0]")
    private Output<String> projectId;

    /**
     * @return Sentry Project ID.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }
    /**
     * Sentry Organization Repository ID.
     * 
     */
    @Export(name="repositoryId", refs={String.class}, tree="[0]")
    private Output<String> repositoryId;

    /**
     * @return Sentry Organization Repository ID.
     * 
     */
    public Output<String> repositoryId() {
        return this.repositoryId;
    }
    /**
     * https://docs.sentry.io/product/integrations/source-code-mgmt/github/#stack-trace-linking
     * 
     */
    @Export(name="sourceRoot", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> sourceRoot;

    /**
     * @return https://docs.sentry.io/product/integrations/source-code-mgmt/github/#stack-trace-linking
     * 
     */
    public Output<Optional<String>> sourceRoot() {
        return Codegen.optional(this.sourceRoot);
    }
    /**
     * https://docs.sentry.io/product/integrations/source-code-mgmt/github/#stack-trace-linking
     * 
     */
    @Export(name="stackRoot", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> stackRoot;

    /**
     * @return https://docs.sentry.io/product/integrations/source-code-mgmt/github/#stack-trace-linking
     * 
     */
    public Output<Optional<String>> stackRoot() {
        return Codegen.optional(this.stackRoot);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public SentryOrganizationCodeMapping(java.lang.String name) {
        this(name, SentryOrganizationCodeMappingArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public SentryOrganizationCodeMapping(java.lang.String name, SentryOrganizationCodeMappingArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public SentryOrganizationCodeMapping(java.lang.String name, SentryOrganizationCodeMappingArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sentry:index/sentryOrganizationCodeMapping:SentryOrganizationCodeMapping", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private SentryOrganizationCodeMapping(java.lang.String name, Output<java.lang.String> id, @Nullable SentryOrganizationCodeMappingState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sentry:index/sentryOrganizationCodeMapping:SentryOrganizationCodeMapping", name, state, makeResourceOptions(options, id), false);
    }

    private static SentryOrganizationCodeMappingArgs makeArgs(SentryOrganizationCodeMappingArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? SentryOrganizationCodeMappingArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static SentryOrganizationCodeMapping get(java.lang.String name, Output<java.lang.String> id, @Nullable SentryOrganizationCodeMappingState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new SentryOrganizationCodeMapping(name, id, state, options);
    }
}
