// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class SentryAllProjectsSpikeProtectionArgs extends com.pulumi.resources.ResourceArgs {

    public static final SentryAllProjectsSpikeProtectionArgs Empty = new SentryAllProjectsSpikeProtectionArgs();

    /**
     * Toggle the browser-extensions, localhost, filtered-transaction, or web-crawlers filter on or off for all projects.
     * 
     */
    @Import(name="enabled", required=true)
    private Output<Boolean> enabled;

    /**
     * @return Toggle the browser-extensions, localhost, filtered-transaction, or web-crawlers filter on or off for all projects.
     * 
     */
    public Output<Boolean> enabled() {
        return this.enabled;
    }

    /**
     * The organization of this resource.
     * 
     */
    @Import(name="organization", required=true)
    private Output<String> organization;

    /**
     * @return The organization of this resource.
     * 
     */
    public Output<String> organization() {
        return this.organization;
    }

    /**
     * The slugs of the projects to enable or disable spike protection for.
     * 
     */
    @Import(name="projects", required=true)
    private Output<List<String>> projects;

    /**
     * @return The slugs of the projects to enable or disable spike protection for.
     * 
     */
    public Output<List<String>> projects() {
        return this.projects;
    }

    private SentryAllProjectsSpikeProtectionArgs() {}

    private SentryAllProjectsSpikeProtectionArgs(SentryAllProjectsSpikeProtectionArgs $) {
        this.enabled = $.enabled;
        this.organization = $.organization;
        this.projects = $.projects;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryAllProjectsSpikeProtectionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryAllProjectsSpikeProtectionArgs $;

        public Builder() {
            $ = new SentryAllProjectsSpikeProtectionArgs();
        }

        public Builder(SentryAllProjectsSpikeProtectionArgs defaults) {
            $ = new SentryAllProjectsSpikeProtectionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param enabled Toggle the browser-extensions, localhost, filtered-transaction, or web-crawlers filter on or off for all projects.
         * 
         * @return builder
         * 
         */
        public Builder enabled(Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Toggle the browser-extensions, localhost, filtered-transaction, or web-crawlers filter on or off for all projects.
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param organization The organization of this resource.
         * 
         * @return builder
         * 
         */
        public Builder organization(Output<String> organization) {
            $.organization = organization;
            return this;
        }

        /**
         * @param organization The organization of this resource.
         * 
         * @return builder
         * 
         */
        public Builder organization(String organization) {
            return organization(Output.of(organization));
        }

        /**
         * @param projects The slugs of the projects to enable or disable spike protection for.
         * 
         * @return builder
         * 
         */
        public Builder projects(Output<List<String>> projects) {
            $.projects = projects;
            return this;
        }

        /**
         * @param projects The slugs of the projects to enable or disable spike protection for.
         * 
         * @return builder
         * 
         */
        public Builder projects(List<String> projects) {
            return projects(Output.of(projects));
        }

        /**
         * @param projects The slugs of the projects to enable or disable spike protection for.
         * 
         * @return builder
         * 
         */
        public Builder projects(String... projects) {
            return projects(List.of(projects));
        }

        public SentryAllProjectsSpikeProtectionArgs build() {
            if ($.enabled == null) {
                throw new MissingRequiredPropertyException("SentryAllProjectsSpikeProtectionArgs", "enabled");
            }
            if ($.organization == null) {
                throw new MissingRequiredPropertyException("SentryAllProjectsSpikeProtectionArgs", "organization");
            }
            if ($.projects == null) {
                throw new MissingRequiredPropertyException("SentryAllProjectsSpikeProtectionArgs", "projects");
            }
            return $;
        }
    }

}
