// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.sentry.SentryProjectArgs;
import com.pulumi.sentry.Utilities;
import com.pulumi.sentry.inputs.SentryProjectState;
import com.pulumi.sentry.outputs.SentryProjectClientSecurity;
import com.pulumi.sentry.outputs.SentryProjectFilters;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Sentry Project resource.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.sentry.SentryProject;
 * import com.pulumi.sentry.SentryProjectArgs;
 * import com.pulumi.sentry.inputs.SentryProjectFiltersArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         // Create a project
 *         var default_ = new SentryProject("default", SentryProjectArgs.builder()
 *             .organization("my-organization")
 *             .teams(            
 *                 "my-first-team",
 *                 "my-second-team")
 *             .name("Web App")
 *             .slug("web-app")
 *             .platform("javascript")
 *             .resolveAge(720)
 *             .defaultRules(false)
 *             .filters(SentryProjectFiltersArgs.builder()
 *                 .blacklisted_ips(                
 *                     "127.0.0.1",
 *                     "0.0.0.0/8")
 *                 .releases(                
 *                     "1.*",
 *                     "[!3].[0-9].*")
 *                 .error_messages(                
 *                     "TypeError*",
 *                     "*: integer division or modulo by zero")
 *                 .build())
 *             .fingerprintingRules("""
 * # force all errors of the same type to have the same fingerprint
 * error.type:DatabaseUnavailable -> system-down
 * # force all memory allocation errors to be grouped together
 * stack.function:malloc -> memory-allocation-error
 *             """)
 *             .groupingEnhancements("""
 * # remove all frames above a certain function from grouping
 * stack.function:panic_handler ^-group
 * # mark all functions following a prefix in-app
 * stack.function:mylibrary_* +app
 *             """)
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * import using the organization and team slugs from the URL:
 * 
 * https://sentry.io/settings/[org-slug]/projects/[project-slug]/
 * 
 * ```sh
 * $ pulumi import sentry:index/sentryProject:SentryProject default org-slug/project-slug
 * ```
 * 
 */
@ResourceType(type="sentry:index/sentryProject:SentryProject")
public class SentryProject extends com.pulumi.resources.CustomResource {
    /**
     * Configure origin URLs which Sentry should accept events from. This is used for communication with clients like [sentry-javascript](https://github.com/getsentry/sentry-javascript).
     * 
     */
    @Export(name="clientSecurity", refs={SentryProjectClientSecurity.class}, tree="[0]")
    private Output<SentryProjectClientSecurity> clientSecurity;

    /**
     * @return Configure origin URLs which Sentry should accept events from. This is used for communication with clients like [sentry-javascript](https://github.com/getsentry/sentry-javascript).
     * 
     */
    public Output<SentryProjectClientSecurity> clientSecurity() {
        return this.clientSecurity;
    }
    /**
     * Whether to create a default key. By default, Sentry will create a key for you. If you wish to manage keys manually, set this to false and create keys using the `sentry.SentryKey` resource.
     * 
     */
    @Export(name="defaultKey", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> defaultKey;

    /**
     * @return Whether to create a default key. By default, Sentry will create a key for you. If you wish to manage keys manually, set this to false and create keys using the `sentry.SentryKey` resource.
     * 
     */
    public Output<Optional<Boolean>> defaultKey() {
        return Codegen.optional(this.defaultKey);
    }
    /**
     * Whether to create a default issue alert. Defaults to true where the behavior is to alert the user on every new issue.
     * 
     */
    @Export(name="defaultRules", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> defaultRules;

    /**
     * @return Whether to create a default issue alert. Defaults to true where the behavior is to alert the user on every new issue.
     * 
     */
    public Output<Optional<Boolean>> defaultRules() {
        return Codegen.optional(this.defaultRules);
    }
    /**
     * The maximum amount of time (in seconds) to wait between scheduling digests for delivery.
     * 
     */
    @Export(name="digestsMaxDelay", refs={Integer.class}, tree="[0]")
    private Output<Integer> digestsMaxDelay;

    /**
     * @return The maximum amount of time (in seconds) to wait between scheduling digests for delivery.
     * 
     */
    public Output<Integer> digestsMaxDelay() {
        return this.digestsMaxDelay;
    }
    /**
     * The minimum amount of time (in seconds) to wait between scheduling digests for delivery after the initial scheduling.
     * 
     */
    @Export(name="digestsMinDelay", refs={Integer.class}, tree="[0]")
    private Output<Integer> digestsMinDelay;

    /**
     * @return The minimum amount of time (in seconds) to wait between scheduling digests for delivery after the initial scheduling.
     * 
     */
    public Output<Integer> digestsMinDelay() {
        return this.digestsMinDelay;
    }
    @Export(name="features", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> features;

    public Output<List<String>> features() {
        return this.features;
    }
    /**
     * Custom filters for this project.
     * 
     */
    @Export(name="filters", refs={SentryProjectFilters.class}, tree="[0]")
    private Output<SentryProjectFilters> filters;

    /**
     * @return Custom filters for this project.
     * 
     */
    public Output<SentryProjectFilters> filters() {
        return this.filters;
    }
    /**
     * This can be used to modify the fingerprint rules on the server with custom rules. Rules follow the pattern `matcher:glob &gt; fingerprint, values`. To learn more about fingerprint rules, [read the docs](https://docs.sentry.io/concepts/data-management/event-grouping/fingerprint-rules/).
     * 
     */
    @Export(name="fingerprintingRules", refs={String.class}, tree="[0]")
    private Output<String> fingerprintingRules;

    /**
     * @return This can be used to modify the fingerprint rules on the server with custom rules. Rules follow the pattern `matcher:glob &gt; fingerprint, values`. To learn more about fingerprint rules, [read the docs](https://docs.sentry.io/concepts/data-management/event-grouping/fingerprint-rules/).
     * 
     */
    public Output<String> fingerprintingRules() {
        return this.fingerprintingRules;
    }
    /**
     * This can be used to enhance the grouping algorithm with custom rules. Rules follow the pattern `matcher:glob [v^]?[+-]flag`. To learn more about stack trace rules, [read the docs](https://docs.sentry.io/concepts/data-management/event-grouping/stack-trace-rules/).
     * 
     */
    @Export(name="groupingEnhancements", refs={String.class}, tree="[0]")
    private Output<String> groupingEnhancements;

    /**
     * @return This can be used to enhance the grouping algorithm with custom rules. Rules follow the pattern `matcher:glob [v^]?[+-]flag`. To learn more about stack trace rules, [read the docs](https://docs.sentry.io/concepts/data-management/event-grouping/stack-trace-rules/).
     * 
     */
    public Output<String> groupingEnhancements() {
        return this.groupingEnhancements;
    }
    /**
     * The internal ID for this project.
     * 
     */
    @Export(name="internalId", refs={String.class}, tree="[0]")
    private Output<String> internalId;

    /**
     * @return The internal ID for this project.
     * 
     */
    public Output<String> internalId() {
        return this.internalId;
    }
    /**
     * The name for the project.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name for the project.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The organization of this resource.
     * 
     */
    @Export(name="organization", refs={String.class}, tree="[0]")
    private Output<String> organization;

    /**
     * @return The organization of this resource.
     * 
     */
    public Output<String> organization() {
        return this.organization;
    }
    /**
     * The platform for this project. For a list of valid values, see this page. Use `other` for platforms not listed.
     * 
     */
    @Export(name="platform", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> platform;

    /**
     * @return The platform for this project. For a list of valid values, see this page. Use `other` for platforms not listed.
     * 
     */
    public Output<Optional<String>> platform() {
        return Codegen.optional(this.platform);
    }
    /**
     * Hours in which an issue is automatically resolve if not seen after this amount of time.
     * 
     */
    @Export(name="resolveAge", refs={Integer.class}, tree="[0]")
    private Output<Integer> resolveAge;

    /**
     * @return Hours in which an issue is automatically resolve if not seen after this amount of time.
     * 
     */
    public Output<Integer> resolveAge() {
        return this.resolveAge;
    }
    /**
     * The optional slug for this project.
     * 
     */
    @Export(name="slug", refs={String.class}, tree="[0]")
    private Output<String> slug;

    /**
     * @return The optional slug for this project.
     * 
     */
    public Output<String> slug() {
        return this.slug;
    }
    /**
     * The slugs of the teams to create the project for.
     * 
     */
    @Export(name="teams", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> teams;

    /**
     * @return The slugs of the teams to create the project for.
     * 
     */
    public Output<List<String>> teams() {
        return this.teams;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public SentryProject(java.lang.String name) {
        this(name, SentryProjectArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public SentryProject(java.lang.String name, SentryProjectArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public SentryProject(java.lang.String name, SentryProjectArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sentry:index/sentryProject:SentryProject", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private SentryProject(java.lang.String name, Output<java.lang.String> id, @Nullable SentryProjectState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sentry:index/sentryProject:SentryProject", name, state, makeResourceOptions(options, id), false);
    }

    private static SentryProjectArgs makeArgs(SentryProjectArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? SentryProjectArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static SentryProject get(java.lang.String name, Output<java.lang.String> id, @Nullable SentryProjectState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new SentryProject(name, id, state, options);
    }
}
