// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SentryTeamMemberArgs extends com.pulumi.resources.ResourceArgs {

    public static final SentryTeamMemberArgs Empty = new SentryTeamMemberArgs();

    /**
     * The ID of the member to add to the team.
     * 
     */
    @Import(name="memberId", required=true)
    private Output<String> memberId;

    /**
     * @return The ID of the member to add to the team.
     * 
     */
    public Output<String> memberId() {
        return this.memberId;
    }

    /**
     * The organization of this resource.
     * 
     */
    @Import(name="organization", required=true)
    private Output<String> organization;

    /**
     * @return The organization of this resource.
     * 
     */
    public Output<String> organization() {
        return this.organization;
    }

    /**
     * The role of the member in the team. When not set, resolve to the minimum team role given by this member&#39;s organization role.
     * 
     */
    @Import(name="role")
    private @Nullable Output<String> role;

    /**
     * @return The role of the member in the team. When not set, resolve to the minimum team role given by this member&#39;s organization role.
     * 
     */
    public Optional<Output<String>> role() {
        return Optional.ofNullable(this.role);
    }

    /**
     * The slug of the team to add the member to.
     * 
     */
    @Import(name="team", required=true)
    private Output<String> team;

    /**
     * @return The slug of the team to add the member to.
     * 
     */
    public Output<String> team() {
        return this.team;
    }

    private SentryTeamMemberArgs() {}

    private SentryTeamMemberArgs(SentryTeamMemberArgs $) {
        this.memberId = $.memberId;
        this.organization = $.organization;
        this.role = $.role;
        this.team = $.team;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SentryTeamMemberArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SentryTeamMemberArgs $;

        public Builder() {
            $ = new SentryTeamMemberArgs();
        }

        public Builder(SentryTeamMemberArgs defaults) {
            $ = new SentryTeamMemberArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param memberId The ID of the member to add to the team.
         * 
         * @return builder
         * 
         */
        public Builder memberId(Output<String> memberId) {
            $.memberId = memberId;
            return this;
        }

        /**
         * @param memberId The ID of the member to add to the team.
         * 
         * @return builder
         * 
         */
        public Builder memberId(String memberId) {
            return memberId(Output.of(memberId));
        }

        /**
         * @param organization The organization of this resource.
         * 
         * @return builder
         * 
         */
        public Builder organization(Output<String> organization) {
            $.organization = organization;
            return this;
        }

        /**
         * @param organization The organization of this resource.
         * 
         * @return builder
         * 
         */
        public Builder organization(String organization) {
            return organization(Output.of(organization));
        }

        /**
         * @param role The role of the member in the team. When not set, resolve to the minimum team role given by this member&#39;s organization role.
         * 
         * @return builder
         * 
         */
        public Builder role(@Nullable Output<String> role) {
            $.role = role;
            return this;
        }

        /**
         * @param role The role of the member in the team. When not set, resolve to the minimum team role given by this member&#39;s organization role.
         * 
         * @return builder
         * 
         */
        public Builder role(String role) {
            return role(Output.of(role));
        }

        /**
         * @param team The slug of the team to add the member to.
         * 
         * @return builder
         * 
         */
        public Builder team(Output<String> team) {
            $.team = team;
            return this;
        }

        /**
         * @param team The slug of the team to add the member to.
         * 
         * @return builder
         * 
         */
        public Builder team(String team) {
            return team(Output.of(team));
        }

        public SentryTeamMemberArgs build() {
            if ($.memberId == null) {
                throw new MissingRequiredPropertyException("SentryTeamMemberArgs", "memberId");
            }
            if ($.organization == null) {
                throw new MissingRequiredPropertyException("SentryTeamMemberArgs", "organization");
            }
            if ($.team == null) {
                throw new MissingRequiredPropertyException("SentryTeamMemberArgs", "team");
            }
            return $;
        }
    }

}
