// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.sentry.SentryTeamMemberArgs;
import com.pulumi.sentry.Utilities;
import com.pulumi.sentry.inputs.SentryTeamMemberState;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Sentry Team Member resource.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.sentry.SentryOrganizationMember;
 * import com.pulumi.sentry.SentryOrganizationMemberArgs;
 * import com.pulumi.sentry.SentryTeam;
 * import com.pulumi.sentry.SentryTeamArgs;
 * import com.pulumi.sentry.SentryTeamMember;
 * import com.pulumi.sentry.SentryTeamMemberArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App }{{@code
 *     public static void main(String[] args) }{{@code
 *         Pulumi.run(App::stack);
 *     }}{@code
 * 
 *     public static void stack(Context ctx) }{{@code
 *         // Add a member to a team
 *         var default_ = new SentryOrganizationMember("default", SentryOrganizationMemberArgs.builder()
 *             .organization("my-organization")
 *             .email("test}{@literal @}{@code example.com")
 *             .role("member")
 *             .build());
 * 
 *         var defaultSentryTeam = new SentryTeam("defaultSentryTeam", SentryTeamArgs.builder()
 *             .organization("my-organization")
 *             .name("my-team")
 *             .slug("my-team")
 *             .build());
 * 
 *         var defaultSentryTeamMember = new SentryTeamMember("defaultSentryTeamMember", SentryTeamMemberArgs.builder()
 *             .organization("my-organization")
 *             .team(defaultSentryTeam.id())
 *             .memberId(default_.internalId())
 *             .build());
 * 
 *     }}{@code
 * }}{@code
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * import using the member ID and team slug from the URL:
 * 
 * https://[org-slug].sentry.io/settings/teams/[team-slug]/members/
 * 
 * https://[org-slug].sentry.io/settings/members/[member-id]/
 * 
 * ```sh
 * $ pulumi import sentry:index/sentryTeamMember:SentryTeamMember default org-slug/team-slug/member-id
 * ```
 * 
 */
@ResourceType(type="sentry:index/sentryTeamMember:SentryTeamMember")
public class SentryTeamMember extends com.pulumi.resources.CustomResource {
    /**
     * The effective role of the member in the team. This represents the highest role, determined by comparing the lower role assigned by the member&#39;s organizational role with the role assigned by the member&#39;s team role.
     * 
     */
    @Export(name="effectiveRole", refs={String.class}, tree="[0]")
    private Output<String> effectiveRole;

    /**
     * @return The effective role of the member in the team. This represents the highest role, determined by comparing the lower role assigned by the member&#39;s organizational role with the role assigned by the member&#39;s team role.
     * 
     */
    public Output<String> effectiveRole() {
        return this.effectiveRole;
    }
    /**
     * The ID of the member to add to the team.
     * 
     */
    @Export(name="memberId", refs={String.class}, tree="[0]")
    private Output<String> memberId;

    /**
     * @return The ID of the member to add to the team.
     * 
     */
    public Output<String> memberId() {
        return this.memberId;
    }
    /**
     * The organization of this resource.
     * 
     */
    @Export(name="organization", refs={String.class}, tree="[0]")
    private Output<String> organization;

    /**
     * @return The organization of this resource.
     * 
     */
    public Output<String> organization() {
        return this.organization;
    }
    /**
     * The role of the member in the team. When not set, resolve to the minimum team role given by this member&#39;s organization role.
     * 
     */
    @Export(name="role", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> role;

    /**
     * @return The role of the member in the team. When not set, resolve to the minimum team role given by this member&#39;s organization role.
     * 
     */
    public Output<Optional<String>> role() {
        return Codegen.optional(this.role);
    }
    /**
     * The slug of the team to add the member to.
     * 
     */
    @Export(name="team", refs={String.class}, tree="[0]")
    private Output<String> team;

    /**
     * @return The slug of the team to add the member to.
     * 
     */
    public Output<String> team() {
        return this.team;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public SentryTeamMember(java.lang.String name) {
        this(name, SentryTeamMemberArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public SentryTeamMember(java.lang.String name, SentryTeamMemberArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public SentryTeamMember(java.lang.String name, SentryTeamMemberArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sentry:index/sentryTeamMember:SentryTeamMember", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private SentryTeamMember(java.lang.String name, Output<java.lang.String> id, @Nullable SentryTeamMemberState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sentry:index/sentryTeamMember:SentryTeamMember", name, state, makeResourceOptions(options, id), false);
    }

    private static SentryTeamMemberArgs makeArgs(SentryTeamMemberArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? SentryTeamMemberArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static SentryTeamMember get(java.lang.String name, Output<java.lang.String> id, @Nullable SentryTeamMemberState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new SentryTeamMember(name, id, state, options);
    }
}
