// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.sentry.SentryProjectSpikeProtectionArgs;
import com.pulumi.sentry.Utilities;
import com.pulumi.sentry.inputs.SentryProjectSpikeProtectionState;
import java.lang.Boolean;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * Sentry Project Spike Protection resource. This resource is used to create and manage spike protection for a project.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.sentry.SentryProject;
 * import com.pulumi.sentry.SentryProjectArgs;
 * import com.pulumi.sentry.SentryProjectSpikeProtection;
 * import com.pulumi.sentry.SentryProjectSpikeProtectionArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var default_ = new SentryProject("default", SentryProjectArgs.builder()
 *             .organization("my-organization")
 *             .teams(            
 *                 "my-first-team",
 *                 "my-second-team")
 *             .name("web-app")
 *             .platform("javascript")
 *             .build());
 * 
 *         // Enable spike protection for the project
 *         var defaultSentryProjectSpikeProtection = new SentryProjectSpikeProtection("defaultSentryProjectSpikeProtection", SentryProjectSpikeProtectionArgs.builder()
 *             .organization(default_.organization())
 *             .project(default_.id())
 *             .enabled(true)
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 */
@ResourceType(type="sentry:index/sentryProjectSpikeProtection:SentryProjectSpikeProtection")
public class SentryProjectSpikeProtection extends com.pulumi.resources.CustomResource {
    /**
     * Toggle the browser-extensions, localhost, filtered-transaction, or web-crawlers filter on or off.
     * 
     */
    @Export(name="enabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> enabled;

    /**
     * @return Toggle the browser-extensions, localhost, filtered-transaction, or web-crawlers filter on or off.
     * 
     */
    public Output<Boolean> enabled() {
        return this.enabled;
    }
    /**
     * The organization of this resource.
     * 
     */
    @Export(name="organization", refs={String.class}, tree="[0]")
    private Output<String> organization;

    /**
     * @return The organization of this resource.
     * 
     */
    public Output<String> organization() {
        return this.organization;
    }
    /**
     * The project of this resource.
     * 
     */
    @Export(name="project", refs={String.class}, tree="[0]")
    private Output<String> project;

    /**
     * @return The project of this resource.
     * 
     */
    public Output<String> project() {
        return this.project;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public SentryProjectSpikeProtection(java.lang.String name) {
        this(name, SentryProjectSpikeProtectionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public SentryProjectSpikeProtection(java.lang.String name, SentryProjectSpikeProtectionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public SentryProjectSpikeProtection(java.lang.String name, SentryProjectSpikeProtectionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sentry:index/sentryProjectSpikeProtection:SentryProjectSpikeProtection", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private SentryProjectSpikeProtection(java.lang.String name, Output<java.lang.String> id, @Nullable SentryProjectSpikeProtectionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sentry:index/sentryProjectSpikeProtection:SentryProjectSpikeProtection", name, state, makeResourceOptions(options, id), false);
    }

    private static SentryProjectSpikeProtectionArgs makeArgs(SentryProjectSpikeProtectionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? SentryProjectSpikeProtectionArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static SentryProjectSpikeProtection get(java.lang.String name, Output<java.lang.String> id, @Nullable SentryProjectSpikeProtectionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new SentryProjectSpikeProtection(name, id, state, options);
    }
}
