// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.sentry.SentryKeyArgs;
import com.pulumi.sentry.Utilities;
import com.pulumi.sentry.inputs.SentryKeyState;
import com.pulumi.sentry.outputs.SentryKeyJavascriptLoaderScript;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import javax.annotation.Nullable;

/**
 * Return a client key bound to a project.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.sentry.SentryKey;
 * import com.pulumi.sentry.SentryKeyArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         // Create a key
 *         var default_ = new SentryKey("default", SentryKeyArgs.builder()
 *             .organization("my-organization")
 *             .project("web-app")
 *             .name("My Key")
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * import using the organization, project slugs and key id from the URL:
 * 
 * https://sentry.io/settings/[org-slug]/projects/[project-slug]/keys/[key-id]/
 * 
 * ```sh
 * $ pulumi import sentry:index/sentryKey:SentryKey default org-slug/project-slug/key-id
 * ```
 * 
 */
@ResourceType(type="sentry:index/sentryKey:SentryKey")
public class SentryKey extends com.pulumi.resources.CustomResource {
    /**
     * This is a map of DSN values. The keys include `public`, `secret`, `csp`, `security`, `minidump`, `nel`, `unreal`, `cdn`, and `crons`.
     * 
     */
    @Export(name="dsn", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output<Map<String,String>> dsn;

    /**
     * @return This is a map of DSN values. The keys include `public`, `secret`, `csp`, `security`, `minidump`, `nel`, `unreal`, `cdn`, and `crons`.
     * 
     */
    public Output<Map<String,String>> dsn() {
        return this.dsn;
    }
    /**
     * Security header endpoint for features like CSP and Expect-CT reports. **Deprecated** Use `dsn[&#34;csp&#34;]` instead.
     * 
     * @deprecated
     * This field is deprecated and will be removed in a future version. Use `dsn[&#34;csp&#34;]` instead.
     * 
     */
    @Deprecated /* This field is deprecated and will be removed in a future version. Use `dsn[""csp""]` instead. */
    @Export(name="dsnCsp", refs={String.class}, tree="[0]")
    private Output<String> dsnCsp;

    /**
     * @return Security header endpoint for features like CSP and Expect-CT reports. **Deprecated** Use `dsn[&#34;csp&#34;]` instead.
     * 
     */
    public Output<String> dsnCsp() {
        return this.dsnCsp;
    }
    /**
     * The DSN tells the SDK where to send the events to. **Deprecated** Use `dsn[&#34;public&#34;]` instead.
     * 
     * @deprecated
     * This field is deprecated and will be removed in a future version. Use `dsn[&#34;public&#34;]` instead.
     * 
     */
    @Deprecated /* This field is deprecated and will be removed in a future version. Use `dsn[""public""]` instead. */
    @Export(name="dsnPublic", refs={String.class}, tree="[0]")
    private Output<String> dsnPublic;

    /**
     * @return The DSN tells the SDK where to send the events to. **Deprecated** Use `dsn[&#34;public&#34;]` instead.
     * 
     */
    public Output<String> dsnPublic() {
        return this.dsnPublic;
    }
    /**
     * Deprecated DSN includes a secret which is no longer required by newer SDK versions. If you are unsure which to use, follow installation instructions for your language. **Deprecated** Use `dsn[&#34;secret&#34;] instead.
     * 
     * @deprecated
     * This field is deprecated and will be removed in a future version. Use `dsn[&#34;secret&#34;]` instead.
     * 
     */
    @Deprecated /* This field is deprecated and will be removed in a future version. Use `dsn[""secret""]` instead. */
    @Export(name="dsnSecret", refs={String.class}, tree="[0]")
    private Output<String> dsnSecret;

    /**
     * @return Deprecated DSN includes a secret which is no longer required by newer SDK versions. If you are unsure which to use, follow installation instructions for your language. **Deprecated** Use `dsn[&#34;secret&#34;] instead.
     * 
     */
    public Output<String> dsnSecret() {
        return this.dsnSecret;
    }
    /**
     * The JavaScript loader script configuration.
     * 
     */
    @Export(name="javascriptLoaderScript", refs={SentryKeyJavascriptLoaderScript.class}, tree="[0]")
    private Output<SentryKeyJavascriptLoaderScript> javascriptLoaderScript;

    /**
     * @return The JavaScript loader script configuration.
     * 
     */
    public Output<SentryKeyJavascriptLoaderScript> javascriptLoaderScript() {
        return this.javascriptLoaderScript;
    }
    /**
     * The name of the client key.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the client key.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The organization of this resource.
     * 
     */
    @Export(name="organization", refs={String.class}, tree="[0]")
    private Output<String> organization;

    /**
     * @return The organization of this resource.
     * 
     */
    public Output<String> organization() {
        return this.organization;
    }
    /**
     * The project of this resource.
     * 
     */
    @Export(name="project", refs={String.class}, tree="[0]")
    private Output<String> project;

    /**
     * @return The project of this resource.
     * 
     */
    public Output<String> project() {
        return this.project;
    }
    /**
     * The ID of the project that the key belongs to.
     * 
     */
    @Export(name="projectId", refs={String.class}, tree="[0]")
    private Output<String> projectId;

    /**
     * @return The ID of the project that the key belongs to.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }
    /**
     * The public key.
     * 
     */
    @Export(name="public", refs={String.class}, tree="[0]")
    private Output<String> public_;

    /**
     * @return The public key.
     * 
     */
    public Output<String> public_() {
        return this.public_;
    }
    /**
     * Number of events that can be reported within the rate limit window.
     * 
     */
    @Export(name="rateLimitCount", refs={Integer.class}, tree="[0]")
    private Output<Integer> rateLimitCount;

    /**
     * @return Number of events that can be reported within the rate limit window.
     * 
     */
    public Output<Integer> rateLimitCount() {
        return this.rateLimitCount;
    }
    /**
     * Length of time in seconds that will be considered when checking the rate limit.
     * 
     */
    @Export(name="rateLimitWindow", refs={Integer.class}, tree="[0]")
    private Output<Integer> rateLimitWindow;

    /**
     * @return Length of time in seconds that will be considered when checking the rate limit.
     * 
     */
    public Output<Integer> rateLimitWindow() {
        return this.rateLimitWindow;
    }
    /**
     * The secret key.
     * 
     */
    @Export(name="secret", refs={String.class}, tree="[0]")
    private Output<String> secret;

    /**
     * @return The secret key.
     * 
     */
    public Output<String> secret() {
        return this.secret;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public SentryKey(java.lang.String name) {
        this(name, SentryKeyArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public SentryKey(java.lang.String name, SentryKeyArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public SentryKey(java.lang.String name, SentryKeyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sentry:index/sentryKey:SentryKey", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private SentryKey(java.lang.String name, Output<java.lang.String> id, @Nullable SentryKeyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sentry:index/sentryKey:SentryKey", name, state, makeResourceOptions(options, id), false);
    }

    private static SentryKeyArgs makeArgs(SentryKeyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? SentryKeyArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "dsnSecret",
                "secret"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static SentryKey get(java.lang.String name, Output<java.lang.String> id, @Nullable SentryKeyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new SentryKey(name, id, state, options);
    }
}
