// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.sentry.SentryOrganizationArgs;
import com.pulumi.sentry.Utilities;
import com.pulumi.sentry.inputs.SentryOrganizationState;
import java.lang.Boolean;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * Sentry Organization resource.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.sentry.SentryOrganization;
 * import com.pulumi.sentry.SentryOrganizationArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         // Create an organization
 *         var default_ = new SentryOrganization("default", SentryOrganizationArgs.builder()
 *             .name("My Organization")
 *             .slug("my-organization")
 *             .agreeTerms(true)
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * import using the organization slug from the URL:
 * 
 * https://sentry.io/organizations/[org-slug]/issues/
 * 
 * ```sh
 * $ pulumi import sentry:index/sentryOrganization:SentryOrganization default org-slug
 * ```
 * 
 */
@ResourceType(type="sentry:index/sentryOrganization:SentryOrganization")
public class SentryOrganization extends com.pulumi.resources.CustomResource {
    /**
     * You agree to the applicable terms of service and privacy policy.
     * 
     */
    @Export(name="agreeTerms", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> agreeTerms;

    /**
     * @return You agree to the applicable terms of service and privacy policy.
     * 
     */
    public Output<Boolean> agreeTerms() {
        return this.agreeTerms;
    }
    /**
     * The internal ID for this organization.
     * 
     */
    @Export(name="internalId", refs={String.class}, tree="[0]")
    private Output<String> internalId;

    /**
     * @return The internal ID for this organization.
     * 
     */
    public Output<String> internalId() {
        return this.internalId;
    }
    /**
     * The human readable name for the organization.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The human readable name for the organization.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The unique URL slug for this organization.
     * 
     */
    @Export(name="slug", refs={String.class}, tree="[0]")
    private Output<String> slug;

    /**
     * @return The unique URL slug for this organization.
     * 
     */
    public Output<String> slug() {
        return this.slug;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public SentryOrganization(java.lang.String name) {
        this(name, SentryOrganizationArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public SentryOrganization(java.lang.String name, SentryOrganizationArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public SentryOrganization(java.lang.String name, SentryOrganizationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sentry:index/sentryOrganization:SentryOrganization", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private SentryOrganization(java.lang.String name, Output<java.lang.String> id, @Nullable SentryOrganizationState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sentry:index/sentryOrganization:SentryOrganization", name, state, makeResourceOptions(options, id), false);
    }

    private static SentryOrganizationArgs makeArgs(SentryOrganizationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? SentryOrganizationArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static SentryOrganization get(java.lang.String name, Output<java.lang.String> id, @Nullable SentryOrganizationState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new SentryOrganization(name, id, state, options);
    }
}
