// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Sentry.Outputs
{

    [OutputType]
    public sealed class GetSentryIssueAlertActionsV2GithubEnterpriseCreateTicketResult
    {
        public readonly string Assignee;
        public readonly string Integration;
        public readonly ImmutableArray<string> Labels;
        public readonly string Name;
        public readonly string Repo;

        [OutputConstructor]
        private GetSentryIssueAlertActionsV2GithubEnterpriseCreateTicketResult(
            string assignee,

            string integration,

            ImmutableArray<string> labels,

            string name,

            string repo)
        {
            Assignee = assignee;
            Integration = integration;
            Labels = labels;
            Name = name;
            Repo = repo;
        }
    }
}
