// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Sentry.Outputs
{

    [OutputType]
    public sealed class GetSentryIssueAlertFiltersV2IssueOccurrencesResult
    {
        public readonly string Name;
        public readonly int Value;

        [OutputConstructor]
        private GetSentryIssueAlertFiltersV2IssueOccurrencesResult(
            string name,

            int value)
        {
            Name = name;
            Value = value;
        }
    }
}
