// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Sentry.Outputs
{

    [OutputType]
    public sealed class GetSentryIssueAlertFiltersV2LevelResult
    {
        public readonly string Level;
        public readonly string Match;
        public readonly string Name;

        [OutputConstructor]
        private GetSentryIssueAlertFiltersV2LevelResult(
            string level,

            string match,

            string name)
        {
            Level = level;
            Match = match;
            Name = name;
        }
    }
}
