// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Sentry.Outputs
{

    [OutputType]
    public sealed class SentryIssueAlertActionsV2GithubEnterpriseCreateTicket
    {
        /// <summary>
        /// The GitHub user to assign the issue to.
        /// </summary>
        public readonly string? Assignee;
        /// <summary>
        /// The integration ID associated with GitHub Enterprise.
        /// </summary>
        public readonly string Integration;
        /// <summary>
        /// A list of labels to assign to the issue.
        /// </summary>
        public readonly ImmutableArray<string> Labels;
        public readonly string? Name;
        /// <summary>
        /// The name of the repository to create the issue in.
        /// </summary>
        public readonly string Repo;

        [OutputConstructor]
        private SentryIssueAlertActionsV2GithubEnterpriseCreateTicket(
            string? assignee,

            string integration,

            ImmutableArray<string> labels,

            string? name,

            string repo)
        {
            Assignee = assignee;
            Integration = integration;
            Labels = labels;
            Name = name;
            Repo = repo;
        }
    }
}
