// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Sentry.Outputs
{

    [OutputType]
    public sealed class SentryIssueAlertFiltersV2
    {
        /// <summary>
        /// The issue is older or newer than `value` `time`.
        /// </summary>
        public readonly Outputs.SentryIssueAlertFiltersV2AgeComparison? AgeComparison;
        /// <summary>
        /// The issue is assigned to no one, team, or member.
        /// </summary>
        public readonly Outputs.SentryIssueAlertFiltersV2AssignedTo? AssignedTo;
        /// <summary>
        /// The event's `attribute` value `match` `value`.
        /// </summary>
        public readonly Outputs.SentryIssueAlertFiltersV2EventAttribute? EventAttribute;
        /// <summary>
        /// The issue's category is equal to `value`.
        /// </summary>
        public readonly Outputs.SentryIssueAlertFiltersV2IssueCategory? IssueCategory;
        /// <summary>
        /// The issue has happened at least `value` times (Note: this is approximate).
        /// </summary>
        public readonly Outputs.SentryIssueAlertFiltersV2IssueOccurrences? IssueOccurrences;
        /// <summary>
        /// The {oldest*or*newest} adopted release associated with the event's issue is {older*or*newer} than the latest adopted release in {environment}.
        /// </summary>
        public readonly Outputs.SentryIssueAlertFiltersV2LatestAdoptedRelease? LatestAdoptedRelease;
        /// <summary>
        /// The event is from the latest release.
        /// </summary>
        public readonly Outputs.SentryIssueAlertFiltersV2LatestRelease? LatestRelease;
        /// <summary>
        /// The event's level is `match` `level`.
        /// </summary>
        public readonly Outputs.SentryIssueAlertFiltersV2Level? Level;
        /// <summary>
        /// The event's tags match `key` `match` `value`.
        /// </summary>
        public readonly Outputs.SentryIssueAlertFiltersV2TaggedEvent? TaggedEvent;

        [OutputConstructor]
        private SentryIssueAlertFiltersV2(
            Outputs.SentryIssueAlertFiltersV2AgeComparison? ageComparison,

            Outputs.SentryIssueAlertFiltersV2AssignedTo? assignedTo,

            Outputs.SentryIssueAlertFiltersV2EventAttribute? eventAttribute,

            Outputs.SentryIssueAlertFiltersV2IssueCategory? issueCategory,

            Outputs.SentryIssueAlertFiltersV2IssueOccurrences? issueOccurrences,

            Outputs.SentryIssueAlertFiltersV2LatestAdoptedRelease? latestAdoptedRelease,

            Outputs.SentryIssueAlertFiltersV2LatestRelease? latestRelease,

            Outputs.SentryIssueAlertFiltersV2Level? level,

            Outputs.SentryIssueAlertFiltersV2TaggedEvent? taggedEvent)
        {
            AgeComparison = ageComparison;
            AssignedTo = assignedTo;
            EventAttribute = eventAttribute;
            IssueCategory = issueCategory;
            IssueOccurrences = issueOccurrences;
            LatestAdoptedRelease = latestAdoptedRelease;
            LatestRelease = latestRelease;
            Level = level;
            TaggedEvent = taggedEvent;
        }
    }
}
