# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetSentryKeyResult',
    'AwaitableGetSentryKeyResult',
    'get_sentry_key',
    'get_sentry_key_output',
]

@pulumi.output_type
class GetSentryKeyResult:
    """
    A collection of values returned by getSentryKey.
    """
    def __init__(__self__, dsn=None, dsn_csp=None, dsn_public=None, dsn_secret=None, first=None, id=None, javascript_loader_script=None, name=None, organization=None, project=None, project_id=None, public=None, rate_limit_count=None, rate_limit_window=None, secret=None):
        if dsn and not isinstance(dsn, dict):
            raise TypeError("Expected argument 'dsn' to be a dict")
        pulumi.set(__self__, "dsn", dsn)
        if dsn_csp and not isinstance(dsn_csp, str):
            raise TypeError("Expected argument 'dsn_csp' to be a str")
        pulumi.set(__self__, "dsn_csp", dsn_csp)
        if dsn_public and not isinstance(dsn_public, str):
            raise TypeError("Expected argument 'dsn_public' to be a str")
        pulumi.set(__self__, "dsn_public", dsn_public)
        if dsn_secret and not isinstance(dsn_secret, str):
            raise TypeError("Expected argument 'dsn_secret' to be a str")
        pulumi.set(__self__, "dsn_secret", dsn_secret)
        if first and not isinstance(first, bool):
            raise TypeError("Expected argument 'first' to be a bool")
        pulumi.set(__self__, "first", first)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if javascript_loader_script and not isinstance(javascript_loader_script, dict):
            raise TypeError("Expected argument 'javascript_loader_script' to be a dict")
        pulumi.set(__self__, "javascript_loader_script", javascript_loader_script)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if organization and not isinstance(organization, str):
            raise TypeError("Expected argument 'organization' to be a str")
        pulumi.set(__self__, "organization", organization)
        if project and not isinstance(project, str):
            raise TypeError("Expected argument 'project' to be a str")
        pulumi.set(__self__, "project", project)
        if project_id and not isinstance(project_id, str):
            raise TypeError("Expected argument 'project_id' to be a str")
        pulumi.set(__self__, "project_id", project_id)
        if public and not isinstance(public, str):
            raise TypeError("Expected argument 'public' to be a str")
        pulumi.set(__self__, "public", public)
        if rate_limit_count and not isinstance(rate_limit_count, int):
            raise TypeError("Expected argument 'rate_limit_count' to be a int")
        pulumi.set(__self__, "rate_limit_count", rate_limit_count)
        if rate_limit_window and not isinstance(rate_limit_window, int):
            raise TypeError("Expected argument 'rate_limit_window' to be a int")
        pulumi.set(__self__, "rate_limit_window", rate_limit_window)
        if secret and not isinstance(secret, str):
            raise TypeError("Expected argument 'secret' to be a str")
        pulumi.set(__self__, "secret", secret)

    @property
    @pulumi.getter
    def dsn(self) -> Mapping[str, str]:
        """
        This is a map of DSN values. The keys include `public`, `secret`, `csp`, `security`, `minidump`, `nel`, `unreal`, `cdn`, and `crons`.
        """
        return pulumi.get(self, "dsn")

    @property
    @pulumi.getter(name="dsnCsp")
    @_utilities.deprecated("""This field is deprecated and will be removed in a future version. Use `dsn[\"csp\"]` instead.""")
    def dsn_csp(self) -> str:
        """
        Security header endpoint for features like CSP and Expect-CT reports. **Deprecated** Use `dsn["csp"]` instead.
        """
        return pulumi.get(self, "dsn_csp")

    @property
    @pulumi.getter(name="dsnPublic")
    @_utilities.deprecated("""This field is deprecated and will be removed in a future version. Use `dsn[\"public\"]` instead.""")
    def dsn_public(self) -> str:
        """
        The DSN tells the SDK where to send the events to. **Deprecated** Use `dsn["public"]` instead.
        """
        return pulumi.get(self, "dsn_public")

    @property
    @pulumi.getter(name="dsnSecret")
    @_utilities.deprecated("""This field is deprecated and will be removed in a future version. Use `dsn[\"secret\"]` instead.""")
    def dsn_secret(self) -> str:
        """
        Deprecated DSN includes a secret which is no longer required by newer SDK versions. If you are unsure which to use, follow installation instructions for your language. **Deprecated** Use `dsn["secret"] instead.
        """
        return pulumi.get(self, "dsn_secret")

    @property
    @pulumi.getter
    def first(self) -> Optional[bool]:
        """
        Boolean flag indicating that we want the first key of the returned keys.
        """
        return pulumi.get(self, "first")

    @property
    @pulumi.getter
    def id(self) -> Optional[str]:
        """
        The ID of this resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="javascriptLoaderScript")
    def javascript_loader_script(self) -> 'outputs.GetSentryKeyJavascriptLoaderScriptResult':
        """
        The JavaScript loader script configuration.
        """
        return pulumi.get(self, "javascript_loader_script")

    @property
    @pulumi.getter
    def name(self) -> Optional[str]:
        """
        The name of the client key.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def organization(self) -> str:
        """
        The organization the resource belongs to.
        """
        return pulumi.get(self, "organization")

    @property
    @pulumi.getter
    def project(self) -> str:
        """
        The project the resource belongs to.
        """
        return pulumi.get(self, "project")

    @property
    @pulumi.getter(name="projectId")
    def project_id(self) -> str:
        """
        The ID of the project that the key belongs to.
        """
        return pulumi.get(self, "project_id")

    @property
    @pulumi.getter
    def public(self) -> str:
        """
        The public key.
        """
        return pulumi.get(self, "public")

    @property
    @pulumi.getter(name="rateLimitCount")
    def rate_limit_count(self) -> int:
        """
        Number of events that can be reported within the rate limit window.
        """
        return pulumi.get(self, "rate_limit_count")

    @property
    @pulumi.getter(name="rateLimitWindow")
    def rate_limit_window(self) -> int:
        """
        Length of time in seconds that will be considered when checking the rate limit.
        """
        return pulumi.get(self, "rate_limit_window")

    @property
    @pulumi.getter
    def secret(self) -> str:
        """
        The secret key.
        """
        return pulumi.get(self, "secret")


class AwaitableGetSentryKeyResult(GetSentryKeyResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetSentryKeyResult(
            dsn=self.dsn,
            dsn_csp=self.dsn_csp,
            dsn_public=self.dsn_public,
            dsn_secret=self.dsn_secret,
            first=self.first,
            id=self.id,
            javascript_loader_script=self.javascript_loader_script,
            name=self.name,
            organization=self.organization,
            project=self.project,
            project_id=self.project_id,
            public=self.public,
            rate_limit_count=self.rate_limit_count,
            rate_limit_window=self.rate_limit_window,
            secret=self.secret)


def get_sentry_key(first: Optional[bool] = None,
                   id: Optional[str] = None,
                   name: Optional[str] = None,
                   organization: Optional[str] = None,
                   project: Optional[str] = None,
                   opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetSentryKeyResult:
    """
    Retrieve a Project's Client Key.


    :param bool first: Boolean flag indicating that we want the first key of the returned keys.
    :param str id: The ID of this resource.
    :param str name: The name of the client key.
    :param str organization: The organization the resource belongs to.
    :param str project: The project the resource belongs to.
    """
    __args__ = dict()
    __args__['first'] = first
    __args__['id'] = id
    __args__['name'] = name
    __args__['organization'] = organization
    __args__['project'] = project
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('sentry:index/getSentryKey:getSentryKey', __args__, opts=opts, typ=GetSentryKeyResult).value

    return AwaitableGetSentryKeyResult(
        dsn=pulumi.get(__ret__, 'dsn'),
        dsn_csp=pulumi.get(__ret__, 'dsn_csp'),
        dsn_public=pulumi.get(__ret__, 'dsn_public'),
        dsn_secret=pulumi.get(__ret__, 'dsn_secret'),
        first=pulumi.get(__ret__, 'first'),
        id=pulumi.get(__ret__, 'id'),
        javascript_loader_script=pulumi.get(__ret__, 'javascript_loader_script'),
        name=pulumi.get(__ret__, 'name'),
        organization=pulumi.get(__ret__, 'organization'),
        project=pulumi.get(__ret__, 'project'),
        project_id=pulumi.get(__ret__, 'project_id'),
        public=pulumi.get(__ret__, 'public'),
        rate_limit_count=pulumi.get(__ret__, 'rate_limit_count'),
        rate_limit_window=pulumi.get(__ret__, 'rate_limit_window'),
        secret=pulumi.get(__ret__, 'secret'))
def get_sentry_key_output(first: Optional[pulumi.Input[Optional[bool]]] = None,
                          id: Optional[pulumi.Input[Optional[str]]] = None,
                          name: Optional[pulumi.Input[Optional[str]]] = None,
                          organization: Optional[pulumi.Input[str]] = None,
                          project: Optional[pulumi.Input[str]] = None,
                          opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetSentryKeyResult]:
    """
    Retrieve a Project's Client Key.


    :param bool first: Boolean flag indicating that we want the first key of the returned keys.
    :param str id: The ID of this resource.
    :param str name: The name of the client key.
    :param str organization: The organization the resource belongs to.
    :param str project: The project the resource belongs to.
    """
    __args__ = dict()
    __args__['first'] = first
    __args__['id'] = id
    __args__['name'] = name
    __args__['organization'] = organization
    __args__['project'] = project
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('sentry:index/getSentryKey:getSentryKey', __args__, opts=opts, typ=GetSentryKeyResult)
    return __ret__.apply(lambda __response__: GetSentryKeyResult(
        dsn=pulumi.get(__response__, 'dsn'),
        dsn_csp=pulumi.get(__response__, 'dsn_csp'),
        dsn_public=pulumi.get(__response__, 'dsn_public'),
        dsn_secret=pulumi.get(__response__, 'dsn_secret'),
        first=pulumi.get(__response__, 'first'),
        id=pulumi.get(__response__, 'id'),
        javascript_loader_script=pulumi.get(__response__, 'javascript_loader_script'),
        name=pulumi.get(__response__, 'name'),
        organization=pulumi.get(__response__, 'organization'),
        project=pulumi.get(__response__, 'project'),
        project_id=pulumi.get(__response__, 'project_id'),
        public=pulumi.get(__response__, 'public'),
        rate_limit_count=pulumi.get(__response__, 'rate_limit_count'),
        rate_limit_window=pulumi.get(__response__, 'rate_limit_window'),
        secret=pulumi.get(__response__, 'secret')))
