// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetSentryIssueAlertActionsV2DiscordNotifyService {
    private String channelId;
    private String name;
    private String server;
    private List<String> tags;

    private GetSentryIssueAlertActionsV2DiscordNotifyService() {}
    public String channelId() {
        return this.channelId;
    }
    public String name() {
        return this.name;
    }
    public String server() {
        return this.server;
    }
    public List<String> tags() {
        return this.tags;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSentryIssueAlertActionsV2DiscordNotifyService defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String channelId;
        private String name;
        private String server;
        private List<String> tags;
        public Builder() {}
        public Builder(GetSentryIssueAlertActionsV2DiscordNotifyService defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.channelId = defaults.channelId;
    	      this.name = defaults.name;
    	      this.server = defaults.server;
    	      this.tags = defaults.tags;
        }

        @CustomType.Setter
        public Builder channelId(String channelId) {
            if (channelId == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertActionsV2DiscordNotifyService", "channelId");
            }
            this.channelId = channelId;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertActionsV2DiscordNotifyService", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder server(String server) {
            if (server == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertActionsV2DiscordNotifyService", "server");
            }
            this.server = server;
            return this;
        }
        @CustomType.Setter
        public Builder tags(List<String> tags) {
            if (tags == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertActionsV2DiscordNotifyService", "tags");
            }
            this.tags = tags;
            return this;
        }
        public Builder tags(String... tags) {
            return tags(List.of(tags));
        }
        public GetSentryIssueAlertActionsV2DiscordNotifyService build() {
            final var _resultValue = new GetSentryIssueAlertActionsV2DiscordNotifyService();
            _resultValue.channelId = channelId;
            _resultValue.name = name;
            _resultValue.server = server;
            _resultValue.tags = tags;
            return _resultValue;
        }
    }
}
