// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetSentryIssueAlertActionsV2NotifyEventService {
    private String name;
    private String service;

    private GetSentryIssueAlertActionsV2NotifyEventService() {}
    public String name() {
        return this.name;
    }
    public String service() {
        return this.service;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSentryIssueAlertActionsV2NotifyEventService defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String name;
        private String service;
        public Builder() {}
        public Builder(GetSentryIssueAlertActionsV2NotifyEventService defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.service = defaults.service;
        }

        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertActionsV2NotifyEventService", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder service(String service) {
            if (service == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertActionsV2NotifyEventService", "service");
            }
            this.service = service;
            return this;
        }
        public GetSentryIssueAlertActionsV2NotifyEventService build() {
            final var _resultValue = new GetSentryIssueAlertActionsV2NotifyEventService();
            _resultValue.name = name;
            _resultValue.service = service;
            return _resultValue;
        }
    }
}
