// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetSentryIssueAlertActionsV2NotifyEmail {
    private String fallthroughType;
    private String name;
    private String targetIdentifier;
    private String targetType;

    private GetSentryIssueAlertActionsV2NotifyEmail() {}
    public String fallthroughType() {
        return this.fallthroughType;
    }
    public String name() {
        return this.name;
    }
    public String targetIdentifier() {
        return this.targetIdentifier;
    }
    public String targetType() {
        return this.targetType;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSentryIssueAlertActionsV2NotifyEmail defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String fallthroughType;
        private String name;
        private String targetIdentifier;
        private String targetType;
        public Builder() {}
        public Builder(GetSentryIssueAlertActionsV2NotifyEmail defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.fallthroughType = defaults.fallthroughType;
    	      this.name = defaults.name;
    	      this.targetIdentifier = defaults.targetIdentifier;
    	      this.targetType = defaults.targetType;
        }

        @CustomType.Setter
        public Builder fallthroughType(String fallthroughType) {
            if (fallthroughType == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertActionsV2NotifyEmail", "fallthroughType");
            }
            this.fallthroughType = fallthroughType;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertActionsV2NotifyEmail", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder targetIdentifier(String targetIdentifier) {
            if (targetIdentifier == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertActionsV2NotifyEmail", "targetIdentifier");
            }
            this.targetIdentifier = targetIdentifier;
            return this;
        }
        @CustomType.Setter
        public Builder targetType(String targetType) {
            if (targetType == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertActionsV2NotifyEmail", "targetType");
            }
            this.targetType = targetType;
            return this;
        }
        public GetSentryIssueAlertActionsV2NotifyEmail build() {
            final var _resultValue = new GetSentryIssueAlertActionsV2NotifyEmail();
            _resultValue.fallthroughType = fallthroughType;
            _resultValue.name = name;
            _resultValue.targetIdentifier = targetIdentifier;
            _resultValue.targetType = targetType;
            return _resultValue;
        }
    }
}
