// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.sentry.outputs.GetSentryDashboardWidgetLayout;
import com.pulumi.sentry.outputs.GetSentryDashboardWidgetQuery;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetSentryDashboardWidget {
    private String displayType;
    private String id;
    private String interval;
    private List<GetSentryDashboardWidgetLayout> layouts;
    private Integer limit;
    private List<GetSentryDashboardWidgetQuery> queries;
    private String title;
    private String widgetType;

    private GetSentryDashboardWidget() {}
    public String displayType() {
        return this.displayType;
    }
    public String id() {
        return this.id;
    }
    public String interval() {
        return this.interval;
    }
    public List<GetSentryDashboardWidgetLayout> layouts() {
        return this.layouts;
    }
    public Integer limit() {
        return this.limit;
    }
    public List<GetSentryDashboardWidgetQuery> queries() {
        return this.queries;
    }
    public String title() {
        return this.title;
    }
    public String widgetType() {
        return this.widgetType;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSentryDashboardWidget defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String displayType;
        private String id;
        private String interval;
        private List<GetSentryDashboardWidgetLayout> layouts;
        private Integer limit;
        private List<GetSentryDashboardWidgetQuery> queries;
        private String title;
        private String widgetType;
        public Builder() {}
        public Builder(GetSentryDashboardWidget defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.displayType = defaults.displayType;
    	      this.id = defaults.id;
    	      this.interval = defaults.interval;
    	      this.layouts = defaults.layouts;
    	      this.limit = defaults.limit;
    	      this.queries = defaults.queries;
    	      this.title = defaults.title;
    	      this.widgetType = defaults.widgetType;
        }

        @CustomType.Setter
        public Builder displayType(String displayType) {
            if (displayType == null) {
              throw new MissingRequiredPropertyException("GetSentryDashboardWidget", "displayType");
            }
            this.displayType = displayType;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetSentryDashboardWidget", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder interval(String interval) {
            if (interval == null) {
              throw new MissingRequiredPropertyException("GetSentryDashboardWidget", "interval");
            }
            this.interval = interval;
            return this;
        }
        @CustomType.Setter
        public Builder layouts(List<GetSentryDashboardWidgetLayout> layouts) {
            if (layouts == null) {
              throw new MissingRequiredPropertyException("GetSentryDashboardWidget", "layouts");
            }
            this.layouts = layouts;
            return this;
        }
        public Builder layouts(GetSentryDashboardWidgetLayout... layouts) {
            return layouts(List.of(layouts));
        }
        @CustomType.Setter
        public Builder limit(Integer limit) {
            if (limit == null) {
              throw new MissingRequiredPropertyException("GetSentryDashboardWidget", "limit");
            }
            this.limit = limit;
            return this;
        }
        @CustomType.Setter
        public Builder queries(List<GetSentryDashboardWidgetQuery> queries) {
            if (queries == null) {
              throw new MissingRequiredPropertyException("GetSentryDashboardWidget", "queries");
            }
            this.queries = queries;
            return this;
        }
        public Builder queries(GetSentryDashboardWidgetQuery... queries) {
            return queries(List.of(queries));
        }
        @CustomType.Setter
        public Builder title(String title) {
            if (title == null) {
              throw new MissingRequiredPropertyException("GetSentryDashboardWidget", "title");
            }
            this.title = title;
            return this;
        }
        @CustomType.Setter
        public Builder widgetType(String widgetType) {
            if (widgetType == null) {
              throw new MissingRequiredPropertyException("GetSentryDashboardWidget", "widgetType");
            }
            this.widgetType = widgetType;
            return this;
        }
        public GetSentryDashboardWidget build() {
            final var _resultValue = new GetSentryDashboardWidget();
            _resultValue.displayType = displayType;
            _resultValue.id = id;
            _resultValue.interval = interval;
            _resultValue.layouts = layouts;
            _resultValue.limit = limit;
            _resultValue.queries = queries;
            _resultValue.title = title;
            _resultValue.widgetType = widgetType;
            return _resultValue;
        }
    }
}
