// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.sentry.outputs.GetSentryIssueAlertConditionsV2EventFrequency;
import com.pulumi.sentry.outputs.GetSentryIssueAlertConditionsV2EventFrequencyPercent;
import com.pulumi.sentry.outputs.GetSentryIssueAlertConditionsV2EventUniqueUserFrequency;
import com.pulumi.sentry.outputs.GetSentryIssueAlertConditionsV2ExistingHighPriorityIssue;
import com.pulumi.sentry.outputs.GetSentryIssueAlertConditionsV2FirstSeenEvent;
import com.pulumi.sentry.outputs.GetSentryIssueAlertConditionsV2NewHighPriorityIssue;
import com.pulumi.sentry.outputs.GetSentryIssueAlertConditionsV2ReappearedEvent;
import com.pulumi.sentry.outputs.GetSentryIssueAlertConditionsV2RegressionEvent;
import java.util.Objects;

@CustomType
public final class GetSentryIssueAlertConditionsV2 {
    /**
     * @return When the `comparison_type` is `count`, the number of events in an issue is more than `value` in `interval`. When the `comparison_type` is `percent`, the number of events in an issue is `value` % higher in `interval` compared to `comparison_interval` ago.
     * 
     */
    private GetSentryIssueAlertConditionsV2EventFrequency eventFrequency;
    /**
     * @return When the `comparison_type` is `count`, the percent of sessions affected by an issue is more than `value` in `interval`. When the `comparison_type` is `percent`, the percent of sessions affected by an issue is `value` % higher in `interval` compared to `comparison_interval` ago.
     * 
     */
    private GetSentryIssueAlertConditionsV2EventFrequencyPercent eventFrequencyPercent;
    /**
     * @return When the `comparison_type` is `count`, the number of users affected by an issue is more than `value` in `interval`. When the `comparison_type` is `percent`, the number of users affected by an issue is `value` % higher in `interval` compared to `comparison_interval` ago.
     * 
     */
    private GetSentryIssueAlertConditionsV2EventUniqueUserFrequency eventUniqueUserFrequency;
    /**
     * @return Sentry marks an existing issue as high priority.
     * 
     */
    private GetSentryIssueAlertConditionsV2ExistingHighPriorityIssue existingHighPriorityIssue;
    /**
     * @return A new issue is created.
     * 
     */
    private GetSentryIssueAlertConditionsV2FirstSeenEvent firstSeenEvent;
    /**
     * @return Sentry marks a new issue as high priority.
     * 
     */
    private GetSentryIssueAlertConditionsV2NewHighPriorityIssue newHighPriorityIssue;
    /**
     * @return The issue changes state from ignored to unresolved.
     * 
     */
    private GetSentryIssueAlertConditionsV2ReappearedEvent reappearedEvent;
    /**
     * @return The issue changes state from resolved to unresolved.
     * 
     */
    private GetSentryIssueAlertConditionsV2RegressionEvent regressionEvent;

    private GetSentryIssueAlertConditionsV2() {}
    /**
     * @return When the `comparison_type` is `count`, the number of events in an issue is more than `value` in `interval`. When the `comparison_type` is `percent`, the number of events in an issue is `value` % higher in `interval` compared to `comparison_interval` ago.
     * 
     */
    public GetSentryIssueAlertConditionsV2EventFrequency eventFrequency() {
        return this.eventFrequency;
    }
    /**
     * @return When the `comparison_type` is `count`, the percent of sessions affected by an issue is more than `value` in `interval`. When the `comparison_type` is `percent`, the percent of sessions affected by an issue is `value` % higher in `interval` compared to `comparison_interval` ago.
     * 
     */
    public GetSentryIssueAlertConditionsV2EventFrequencyPercent eventFrequencyPercent() {
        return this.eventFrequencyPercent;
    }
    /**
     * @return When the `comparison_type` is `count`, the number of users affected by an issue is more than `value` in `interval`. When the `comparison_type` is `percent`, the number of users affected by an issue is `value` % higher in `interval` compared to `comparison_interval` ago.
     * 
     */
    public GetSentryIssueAlertConditionsV2EventUniqueUserFrequency eventUniqueUserFrequency() {
        return this.eventUniqueUserFrequency;
    }
    /**
     * @return Sentry marks an existing issue as high priority.
     * 
     */
    public GetSentryIssueAlertConditionsV2ExistingHighPriorityIssue existingHighPriorityIssue() {
        return this.existingHighPriorityIssue;
    }
    /**
     * @return A new issue is created.
     * 
     */
    public GetSentryIssueAlertConditionsV2FirstSeenEvent firstSeenEvent() {
        return this.firstSeenEvent;
    }
    /**
     * @return Sentry marks a new issue as high priority.
     * 
     */
    public GetSentryIssueAlertConditionsV2NewHighPriorityIssue newHighPriorityIssue() {
        return this.newHighPriorityIssue;
    }
    /**
     * @return The issue changes state from ignored to unresolved.
     * 
     */
    public GetSentryIssueAlertConditionsV2ReappearedEvent reappearedEvent() {
        return this.reappearedEvent;
    }
    /**
     * @return The issue changes state from resolved to unresolved.
     * 
     */
    public GetSentryIssueAlertConditionsV2RegressionEvent regressionEvent() {
        return this.regressionEvent;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSentryIssueAlertConditionsV2 defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private GetSentryIssueAlertConditionsV2EventFrequency eventFrequency;
        private GetSentryIssueAlertConditionsV2EventFrequencyPercent eventFrequencyPercent;
        private GetSentryIssueAlertConditionsV2EventUniqueUserFrequency eventUniqueUserFrequency;
        private GetSentryIssueAlertConditionsV2ExistingHighPriorityIssue existingHighPriorityIssue;
        private GetSentryIssueAlertConditionsV2FirstSeenEvent firstSeenEvent;
        private GetSentryIssueAlertConditionsV2NewHighPriorityIssue newHighPriorityIssue;
        private GetSentryIssueAlertConditionsV2ReappearedEvent reappearedEvent;
        private GetSentryIssueAlertConditionsV2RegressionEvent regressionEvent;
        public Builder() {}
        public Builder(GetSentryIssueAlertConditionsV2 defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.eventFrequency = defaults.eventFrequency;
    	      this.eventFrequencyPercent = defaults.eventFrequencyPercent;
    	      this.eventUniqueUserFrequency = defaults.eventUniqueUserFrequency;
    	      this.existingHighPriorityIssue = defaults.existingHighPriorityIssue;
    	      this.firstSeenEvent = defaults.firstSeenEvent;
    	      this.newHighPriorityIssue = defaults.newHighPriorityIssue;
    	      this.reappearedEvent = defaults.reappearedEvent;
    	      this.regressionEvent = defaults.regressionEvent;
        }

        @CustomType.Setter
        public Builder eventFrequency(GetSentryIssueAlertConditionsV2EventFrequency eventFrequency) {
            if (eventFrequency == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertConditionsV2", "eventFrequency");
            }
            this.eventFrequency = eventFrequency;
            return this;
        }
        @CustomType.Setter
        public Builder eventFrequencyPercent(GetSentryIssueAlertConditionsV2EventFrequencyPercent eventFrequencyPercent) {
            if (eventFrequencyPercent == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertConditionsV2", "eventFrequencyPercent");
            }
            this.eventFrequencyPercent = eventFrequencyPercent;
            return this;
        }
        @CustomType.Setter
        public Builder eventUniqueUserFrequency(GetSentryIssueAlertConditionsV2EventUniqueUserFrequency eventUniqueUserFrequency) {
            if (eventUniqueUserFrequency == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertConditionsV2", "eventUniqueUserFrequency");
            }
            this.eventUniqueUserFrequency = eventUniqueUserFrequency;
            return this;
        }
        @CustomType.Setter
        public Builder existingHighPriorityIssue(GetSentryIssueAlertConditionsV2ExistingHighPriorityIssue existingHighPriorityIssue) {
            if (existingHighPriorityIssue == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertConditionsV2", "existingHighPriorityIssue");
            }
            this.existingHighPriorityIssue = existingHighPriorityIssue;
            return this;
        }
        @CustomType.Setter
        public Builder firstSeenEvent(GetSentryIssueAlertConditionsV2FirstSeenEvent firstSeenEvent) {
            if (firstSeenEvent == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertConditionsV2", "firstSeenEvent");
            }
            this.firstSeenEvent = firstSeenEvent;
            return this;
        }
        @CustomType.Setter
        public Builder newHighPriorityIssue(GetSentryIssueAlertConditionsV2NewHighPriorityIssue newHighPriorityIssue) {
            if (newHighPriorityIssue == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertConditionsV2", "newHighPriorityIssue");
            }
            this.newHighPriorityIssue = newHighPriorityIssue;
            return this;
        }
        @CustomType.Setter
        public Builder reappearedEvent(GetSentryIssueAlertConditionsV2ReappearedEvent reappearedEvent) {
            if (reappearedEvent == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertConditionsV2", "reappearedEvent");
            }
            this.reappearedEvent = reappearedEvent;
            return this;
        }
        @CustomType.Setter
        public Builder regressionEvent(GetSentryIssueAlertConditionsV2RegressionEvent regressionEvent) {
            if (regressionEvent == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertConditionsV2", "regressionEvent");
            }
            this.regressionEvent = regressionEvent;
            return this;
        }
        public GetSentryIssueAlertConditionsV2 build() {
            final var _resultValue = new GetSentryIssueAlertConditionsV2();
            _resultValue.eventFrequency = eventFrequency;
            _resultValue.eventFrequencyPercent = eventFrequencyPercent;
            _resultValue.eventUniqueUserFrequency = eventUniqueUserFrequency;
            _resultValue.existingHighPriorityIssue = existingHighPriorityIssue;
            _resultValue.firstSeenEvent = firstSeenEvent;
            _resultValue.newHighPriorityIssue = newHighPriorityIssue;
            _resultValue.reappearedEvent = reappearedEvent;
            _resultValue.regressionEvent = regressionEvent;
            return _resultValue;
        }
    }
}
