// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetSentryIssueAlertFiltersV2LatestAdoptedRelease {
    private Integer environment;
    private String name;
    private Integer olderOrNewer;
    private Integer oldestOrNewest;

    private GetSentryIssueAlertFiltersV2LatestAdoptedRelease() {}
    public Integer environment() {
        return this.environment;
    }
    public String name() {
        return this.name;
    }
    public Integer olderOrNewer() {
        return this.olderOrNewer;
    }
    public Integer oldestOrNewest() {
        return this.oldestOrNewest;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSentryIssueAlertFiltersV2LatestAdoptedRelease defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer environment;
        private String name;
        private Integer olderOrNewer;
        private Integer oldestOrNewest;
        public Builder() {}
        public Builder(GetSentryIssueAlertFiltersV2LatestAdoptedRelease defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.environment = defaults.environment;
    	      this.name = defaults.name;
    	      this.olderOrNewer = defaults.olderOrNewer;
    	      this.oldestOrNewest = defaults.oldestOrNewest;
        }

        @CustomType.Setter
        public Builder environment(Integer environment) {
            if (environment == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertFiltersV2LatestAdoptedRelease", "environment");
            }
            this.environment = environment;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertFiltersV2LatestAdoptedRelease", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder olderOrNewer(Integer olderOrNewer) {
            if (olderOrNewer == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertFiltersV2LatestAdoptedRelease", "olderOrNewer");
            }
            this.olderOrNewer = olderOrNewer;
            return this;
        }
        @CustomType.Setter
        public Builder oldestOrNewest(Integer oldestOrNewest) {
            if (oldestOrNewest == null) {
              throw new MissingRequiredPropertyException("GetSentryIssueAlertFiltersV2LatestAdoptedRelease", "oldestOrNewest");
            }
            this.oldestOrNewest = oldestOrNewest;
            return this;
        }
        public GetSentryIssueAlertFiltersV2LatestAdoptedRelease build() {
            final var _resultValue = new GetSentryIssueAlertFiltersV2LatestAdoptedRelease();
            _resultValue.environment = environment;
            _resultValue.name = name;
            _resultValue.olderOrNewer = olderOrNewer;
            _resultValue.oldestOrNewest = oldestOrNewest;
            return _resultValue;
        }
    }
}
