// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class SentryProjectSymbolSourceLayout {
    /**
     * @return The casing of the symbol source layout. The layout of the folder structure. The options are: `default` - Default (mixed case), `uppercase` - Uppercase, `lowercase` - Lowercase.
     * 
     */
    private String casing;
    /**
     * @return The layout of the folder structure. The options are: `native` - Platform-Specific (SymStore / GDB / LLVM), `symstore` - Microsoft SymStore, `symstore_index2` - Microsoft SymStore (with index2.txt), `ssqp` - Microsoft SSQP, `unified` - Unified Symbol Server Layout, `debuginfod` - debuginfod.
     * 
     */
    private String type;

    private SentryProjectSymbolSourceLayout() {}
    /**
     * @return The casing of the symbol source layout. The layout of the folder structure. The options are: `default` - Default (mixed case), `uppercase` - Uppercase, `lowercase` - Lowercase.
     * 
     */
    public String casing() {
        return this.casing;
    }
    /**
     * @return The layout of the folder structure. The options are: `native` - Platform-Specific (SymStore / GDB / LLVM), `symstore` - Microsoft SymStore, `symstore_index2` - Microsoft SymStore (with index2.txt), `ssqp` - Microsoft SSQP, `unified` - Unified Symbol Server Layout, `debuginfod` - debuginfod.
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SentryProjectSymbolSourceLayout defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String casing;
        private String type;
        public Builder() {}
        public Builder(SentryProjectSymbolSourceLayout defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.casing = defaults.casing;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder casing(String casing) {
            if (casing == null) {
              throw new MissingRequiredPropertyException("SentryProjectSymbolSourceLayout", "casing");
            }
            this.casing = casing;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("SentryProjectSymbolSourceLayout", "type");
            }
            this.type = type;
            return this;
        }
        public SentryProjectSymbolSourceLayout build() {
            final var _resultValue = new SentryProjectSymbolSourceLayout();
            _resultValue.casing = casing;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
