// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class SentrygetAllProjectsProject {
    /**
     * @return The color of this project.
     * 
     */
    private String color;
    /**
     * @return The date this project was created.
     * 
     */
    private String dateCreated;
    /**
     * @return The features of this project.
     * 
     */
    private List<String> features;
    /**
     * @return The internal ID of this project.
     * 
     */
    private String internalId;
    /**
     * @return The name of this project.
     * 
     */
    private String name;
    /**
     * @return The platform of this project.
     * 
     */
    private String platform;
    /**
     * @return The slug of this project.
     * 
     */
    private String slug;

    private SentrygetAllProjectsProject() {}
    /**
     * @return The color of this project.
     * 
     */
    public String color() {
        return this.color;
    }
    /**
     * @return The date this project was created.
     * 
     */
    public String dateCreated() {
        return this.dateCreated;
    }
    /**
     * @return The features of this project.
     * 
     */
    public List<String> features() {
        return this.features;
    }
    /**
     * @return The internal ID of this project.
     * 
     */
    public String internalId() {
        return this.internalId;
    }
    /**
     * @return The name of this project.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The platform of this project.
     * 
     */
    public String platform() {
        return this.platform;
    }
    /**
     * @return The slug of this project.
     * 
     */
    public String slug() {
        return this.slug;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SentrygetAllProjectsProject defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String color;
        private String dateCreated;
        private List<String> features;
        private String internalId;
        private String name;
        private String platform;
        private String slug;
        public Builder() {}
        public Builder(SentrygetAllProjectsProject defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.color = defaults.color;
    	      this.dateCreated = defaults.dateCreated;
    	      this.features = defaults.features;
    	      this.internalId = defaults.internalId;
    	      this.name = defaults.name;
    	      this.platform = defaults.platform;
    	      this.slug = defaults.slug;
        }

        @CustomType.Setter
        public Builder color(String color) {
            if (color == null) {
              throw new MissingRequiredPropertyException("SentrygetAllProjectsProject", "color");
            }
            this.color = color;
            return this;
        }
        @CustomType.Setter
        public Builder dateCreated(String dateCreated) {
            if (dateCreated == null) {
              throw new MissingRequiredPropertyException("SentrygetAllProjectsProject", "dateCreated");
            }
            this.dateCreated = dateCreated;
            return this;
        }
        @CustomType.Setter
        public Builder features(List<String> features) {
            if (features == null) {
              throw new MissingRequiredPropertyException("SentrygetAllProjectsProject", "features");
            }
            this.features = features;
            return this;
        }
        public Builder features(String... features) {
            return features(List.of(features));
        }
        @CustomType.Setter
        public Builder internalId(String internalId) {
            if (internalId == null) {
              throw new MissingRequiredPropertyException("SentrygetAllProjectsProject", "internalId");
            }
            this.internalId = internalId;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("SentrygetAllProjectsProject", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder platform(String platform) {
            if (platform == null) {
              throw new MissingRequiredPropertyException("SentrygetAllProjectsProject", "platform");
            }
            this.platform = platform;
            return this;
        }
        @CustomType.Setter
        public Builder slug(String slug) {
            if (slug == null) {
              throw new MissingRequiredPropertyException("SentrygetAllProjectsProject", "slug");
            }
            this.slug = slug;
            return this;
        }
        public SentrygetAllProjectsProject build() {
            final var _resultValue = new SentrygetAllProjectsProject();
            _resultValue.color = color;
            _resultValue.dateCreated = dateCreated;
            _resultValue.features = features;
            _resultValue.internalId = internalId;
            _resultValue.name = name;
            _resultValue.platform = platform;
            _resultValue.slug = slug;
            return _resultValue;
        }
    }
}
