// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class SentrygetIssueAlertActionsV2NotifyEvent {
    private String name;

    private SentrygetIssueAlertActionsV2NotifyEvent() {}
    public String name() {
        return this.name;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SentrygetIssueAlertActionsV2NotifyEvent defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String name;
        public Builder() {}
        public Builder(SentrygetIssueAlertActionsV2NotifyEvent defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("SentrygetIssueAlertActionsV2NotifyEvent", "name");
            }
            this.name = name;
            return this;
        }
        public SentrygetIssueAlertActionsV2NotifyEvent build() {
            final var _resultValue = new SentrygetIssueAlertActionsV2NotifyEvent();
            _resultValue.name = name;
            return _resultValue;
        }
    }
}
