// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class SentryIssueAlertActionsV2JiraCreateTicket {
    /**
     * @return The integration ID associated with Jira.
     * 
     */
    private String integration;
    /**
     * @return The ID of the type of issue that the ticket should be created as.
     * 
     */
    private String issueType;
    private @Nullable String name;
    /**
     * @return The ID of the Jira project.
     * 
     */
    private String project;

    private SentryIssueAlertActionsV2JiraCreateTicket() {}
    /**
     * @return The integration ID associated with Jira.
     * 
     */
    public String integration() {
        return this.integration;
    }
    /**
     * @return The ID of the type of issue that the ticket should be created as.
     * 
     */
    public String issueType() {
        return this.issueType;
    }
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return The ID of the Jira project.
     * 
     */
    public String project() {
        return this.project;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SentryIssueAlertActionsV2JiraCreateTicket defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String integration;
        private String issueType;
        private @Nullable String name;
        private String project;
        public Builder() {}
        public Builder(SentryIssueAlertActionsV2JiraCreateTicket defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.integration = defaults.integration;
    	      this.issueType = defaults.issueType;
    	      this.name = defaults.name;
    	      this.project = defaults.project;
        }

        @CustomType.Setter
        public Builder integration(String integration) {
            if (integration == null) {
              throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2JiraCreateTicket", "integration");
            }
            this.integration = integration;
            return this;
        }
        @CustomType.Setter
        public Builder issueType(String issueType) {
            if (issueType == null) {
              throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2JiraCreateTicket", "issueType");
            }
            this.issueType = issueType;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder project(String project) {
            if (project == null) {
              throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2JiraCreateTicket", "project");
            }
            this.project = project;
            return this;
        }
        public SentryIssueAlertActionsV2JiraCreateTicket build() {
            final var _resultValue = new SentryIssueAlertActionsV2JiraCreateTicket();
            _resultValue.integration = integration;
            _resultValue.issueType = issueType;
            _resultValue.name = name;
            _resultValue.project = project;
            return _resultValue;
        }
    }
}
