// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.sentry.outputs.SentrygetAllProjectsProject;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class SentrygetAllProjectsResult {
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return The organization the resource belongs to.
     * 
     */
    private String organization;
    /**
     * @return The slugs of the projects.
     * 
     */
    private List<String> projectSlugs;
    /**
     * @return The list of projects.
     * 
     */
    private List<SentrygetAllProjectsProject> projects;

    private SentrygetAllProjectsResult() {}
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The organization the resource belongs to.
     * 
     */
    public String organization() {
        return this.organization;
    }
    /**
     * @return The slugs of the projects.
     * 
     */
    public List<String> projectSlugs() {
        return this.projectSlugs;
    }
    /**
     * @return The list of projects.
     * 
     */
    public List<SentrygetAllProjectsProject> projects() {
        return this.projects;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SentrygetAllProjectsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private String organization;
        private List<String> projectSlugs;
        private List<SentrygetAllProjectsProject> projects;
        public Builder() {}
        public Builder(SentrygetAllProjectsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.organization = defaults.organization;
    	      this.projectSlugs = defaults.projectSlugs;
    	      this.projects = defaults.projects;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("SentrygetAllProjectsResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder organization(String organization) {
            if (organization == null) {
              throw new MissingRequiredPropertyException("SentrygetAllProjectsResult", "organization");
            }
            this.organization = organization;
            return this;
        }
        @CustomType.Setter
        public Builder projectSlugs(List<String> projectSlugs) {
            if (projectSlugs == null) {
              throw new MissingRequiredPropertyException("SentrygetAllProjectsResult", "projectSlugs");
            }
            this.projectSlugs = projectSlugs;
            return this;
        }
        public Builder projectSlugs(String... projectSlugs) {
            return projectSlugs(List.of(projectSlugs));
        }
        @CustomType.Setter
        public Builder projects(List<SentrygetAllProjectsProject> projects) {
            if (projects == null) {
              throw new MissingRequiredPropertyException("SentrygetAllProjectsResult", "projects");
            }
            this.projects = projects;
            return this;
        }
        public Builder projects(SentrygetAllProjectsProject... projects) {
            return projects(List.of(projects));
        }
        public SentrygetAllProjectsResult build() {
            final var _resultValue = new SentrygetAllProjectsResult();
            _resultValue.id = id;
            _resultValue.organization = organization;
            _resultValue.projectSlugs = projectSlugs;
            _resultValue.projects = projects;
            return _resultValue;
        }
    }
}
