// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class SentryIssueAlertActionsV2AzureDevopsCreateTicket {
    /**
     * @return The integration ID.
     * 
     */
    private String integration;
    private @Nullable String name;
    /**
     * @return The ID of the Azure DevOps project.
     * 
     */
    private String project;
    /**
     * @return The type of work item to create.
     * 
     */
    private String workItemType;

    private SentryIssueAlertActionsV2AzureDevopsCreateTicket() {}
    /**
     * @return The integration ID.
     * 
     */
    public String integration() {
        return this.integration;
    }
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return The ID of the Azure DevOps project.
     * 
     */
    public String project() {
        return this.project;
    }
    /**
     * @return The type of work item to create.
     * 
     */
    public String workItemType() {
        return this.workItemType;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SentryIssueAlertActionsV2AzureDevopsCreateTicket defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String integration;
        private @Nullable String name;
        private String project;
        private String workItemType;
        public Builder() {}
        public Builder(SentryIssueAlertActionsV2AzureDevopsCreateTicket defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.integration = defaults.integration;
    	      this.name = defaults.name;
    	      this.project = defaults.project;
    	      this.workItemType = defaults.workItemType;
        }

        @CustomType.Setter
        public Builder integration(String integration) {
            if (integration == null) {
              throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2AzureDevopsCreateTicket", "integration");
            }
            this.integration = integration;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder project(String project) {
            if (project == null) {
              throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2AzureDevopsCreateTicket", "project");
            }
            this.project = project;
            return this;
        }
        @CustomType.Setter
        public Builder workItemType(String workItemType) {
            if (workItemType == null) {
              throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2AzureDevopsCreateTicket", "workItemType");
            }
            this.workItemType = workItemType;
            return this;
        }
        public SentryIssueAlertActionsV2AzureDevopsCreateTicket build() {
            final var _resultValue = new SentryIssueAlertActionsV2AzureDevopsCreateTicket();
            _resultValue.integration = integration;
            _resultValue.name = name;
            _resultValue.project = project;
            _resultValue.workItemType = workItemType;
            return _resultValue;
        }
    }
}
