// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class SentryIssueAlertActionsV2NotifyEventService {
    private @Nullable String name;
    private String service;

    private SentryIssueAlertActionsV2NotifyEventService() {}
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    public String service() {
        return this.service;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SentryIssueAlertActionsV2NotifyEventService defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String name;
        private String service;
        public Builder() {}
        public Builder(SentryIssueAlertActionsV2NotifyEventService defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.service = defaults.service;
        }

        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder service(String service) {
            if (service == null) {
              throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2NotifyEventService", "service");
            }
            this.service = service;
            return this;
        }
        public SentryIssueAlertActionsV2NotifyEventService build() {
            final var _resultValue = new SentryIssueAlertActionsV2NotifyEventService();
            _resultValue.name = name;
            _resultValue.service = service;
            return _resultValue;
        }
    }
}
