// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class SentryIssueAlertActionsV2OpsgenieNotifyTeam {
    private String account;
    private @Nullable String name;
    private String priority;
    private String team;

    private SentryIssueAlertActionsV2OpsgenieNotifyTeam() {}
    public String account() {
        return this.account;
    }
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    public String priority() {
        return this.priority;
    }
    public String team() {
        return this.team;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SentryIssueAlertActionsV2OpsgenieNotifyTeam defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String account;
        private @Nullable String name;
        private String priority;
        private String team;
        public Builder() {}
        public Builder(SentryIssueAlertActionsV2OpsgenieNotifyTeam defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.account = defaults.account;
    	      this.name = defaults.name;
    	      this.priority = defaults.priority;
    	      this.team = defaults.team;
        }

        @CustomType.Setter
        public Builder account(String account) {
            if (account == null) {
              throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2OpsgenieNotifyTeam", "account");
            }
            this.account = account;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder priority(String priority) {
            if (priority == null) {
              throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2OpsgenieNotifyTeam", "priority");
            }
            this.priority = priority;
            return this;
        }
        @CustomType.Setter
        public Builder team(String team) {
            if (team == null) {
              throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2OpsgenieNotifyTeam", "team");
            }
            this.team = team;
            return this;
        }
        public SentryIssueAlertActionsV2OpsgenieNotifyTeam build() {
            final var _resultValue = new SentryIssueAlertActionsV2OpsgenieNotifyTeam();
            _resultValue.account = account;
            _resultValue.name = name;
            _resultValue.priority = priority;
            _resultValue.team = team;
            return _resultValue;
        }
    }
}
