// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class SentryIssueAlertFiltersV2IssueOccurrences {
    private @Nullable String name;
    private Integer value;

    private SentryIssueAlertFiltersV2IssueOccurrences() {}
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    public Integer value() {
        return this.value;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SentryIssueAlertFiltersV2IssueOccurrences defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String name;
        private Integer value;
        public Builder() {}
        public Builder(SentryIssueAlertFiltersV2IssueOccurrences defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.value = defaults.value;
        }

        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder value(Integer value) {
            if (value == null) {
              throw new MissingRequiredPropertyException("SentryIssueAlertFiltersV2IssueOccurrences", "value");
            }
            this.value = value;
            return this;
        }
        public SentryIssueAlertFiltersV2IssueOccurrences build() {
            final var _resultValue = new SentryIssueAlertFiltersV2IssueOccurrences();
            _resultValue.name = name;
            _resultValue.value = value;
            return _resultValue;
        }
    }
}
