// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class SentryIssueAlertFiltersV2Level {
    /**
     * @return Valid values are: `sample`, `debug`, `info`, `warning`, `error`, and `fatal`.
     * 
     */
    private String level;
    /**
     * @return The comparison operator. Valid values are: `EQUAL`, `GREATER_OR_EQUAL`, and `LESS_OR_EQUAL`.
     * 
     */
    private String match;
    private @Nullable String name;

    private SentryIssueAlertFiltersV2Level() {}
    /**
     * @return Valid values are: `sample`, `debug`, `info`, `warning`, `error`, and `fatal`.
     * 
     */
    public String level() {
        return this.level;
    }
    /**
     * @return The comparison operator. Valid values are: `EQUAL`, `GREATER_OR_EQUAL`, and `LESS_OR_EQUAL`.
     * 
     */
    public String match() {
        return this.match;
    }
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SentryIssueAlertFiltersV2Level defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String level;
        private String match;
        private @Nullable String name;
        public Builder() {}
        public Builder(SentryIssueAlertFiltersV2Level defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.level = defaults.level;
    	      this.match = defaults.match;
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder level(String level) {
            if (level == null) {
              throw new MissingRequiredPropertyException("SentryIssueAlertFiltersV2Level", "level");
            }
            this.level = level;
            return this;
        }
        @CustomType.Setter
        public Builder match(String match) {
            if (match == null) {
              throw new MissingRequiredPropertyException("SentryIssueAlertFiltersV2Level", "match");
            }
            this.match = match;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        public SentryIssueAlertFiltersV2Level build() {
            final var _resultValue = new SentryIssueAlertFiltersV2Level();
            _resultValue.level = level;
            _resultValue.match = match;
            _resultValue.name = name;
            return _resultValue;
        }
    }
}
