// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class SentryDashboardWidgetQuery {
    private @Nullable List<String> aggregates;
    private @Nullable List<String> columns;
    private @Nullable String conditions;
    private @Nullable List<String> fieldAliases;
    private @Nullable List<String> fields;
    /**
     * @return The ID of the query.
     * 
     */
    private @Nullable String id;
    private @Nullable String name;
    private @Nullable String orderBy;

    private SentryDashboardWidgetQuery() {}
    public List<String> aggregates() {
        return this.aggregates == null ? List.of() : this.aggregates;
    }
    public List<String> columns() {
        return this.columns == null ? List.of() : this.columns;
    }
    public Optional<String> conditions() {
        return Optional.ofNullable(this.conditions);
    }
    public List<String> fieldAliases() {
        return this.fieldAliases == null ? List.of() : this.fieldAliases;
    }
    public List<String> fields() {
        return this.fields == null ? List.of() : this.fields;
    }
    /**
     * @return The ID of the query.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    public Optional<String> orderBy() {
        return Optional.ofNullable(this.orderBy);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SentryDashboardWidgetQuery defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<String> aggregates;
        private @Nullable List<String> columns;
        private @Nullable String conditions;
        private @Nullable List<String> fieldAliases;
        private @Nullable List<String> fields;
        private @Nullable String id;
        private @Nullable String name;
        private @Nullable String orderBy;
        public Builder() {}
        public Builder(SentryDashboardWidgetQuery defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.aggregates = defaults.aggregates;
    	      this.columns = defaults.columns;
    	      this.conditions = defaults.conditions;
    	      this.fieldAliases = defaults.fieldAliases;
    	      this.fields = defaults.fields;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.orderBy = defaults.orderBy;
        }

        @CustomType.Setter
        public Builder aggregates(@Nullable List<String> aggregates) {

            this.aggregates = aggregates;
            return this;
        }
        public Builder aggregates(String... aggregates) {
            return aggregates(List.of(aggregates));
        }
        @CustomType.Setter
        public Builder columns(@Nullable List<String> columns) {

            this.columns = columns;
            return this;
        }
        public Builder columns(String... columns) {
            return columns(List.of(columns));
        }
        @CustomType.Setter
        public Builder conditions(@Nullable String conditions) {

            this.conditions = conditions;
            return this;
        }
        @CustomType.Setter
        public Builder fieldAliases(@Nullable List<String> fieldAliases) {

            this.fieldAliases = fieldAliases;
            return this;
        }
        public Builder fieldAliases(String... fieldAliases) {
            return fieldAliases(List.of(fieldAliases));
        }
        @CustomType.Setter
        public Builder fields(@Nullable List<String> fields) {

            this.fields = fields;
            return this;
        }
        public Builder fields(String... fields) {
            return fields(List.of(fields));
        }
        @CustomType.Setter
        public Builder id(@Nullable String id) {

            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder orderBy(@Nullable String orderBy) {

            this.orderBy = orderBy;
            return this;
        }
        public SentryDashboardWidgetQuery build() {
            final var _resultValue = new SentryDashboardWidgetQuery();
            _resultValue.aggregates = aggregates;
            _resultValue.columns = columns;
            _resultValue.conditions = conditions;
            _resultValue.fieldAliases = fieldAliases;
            _resultValue.fields = fields;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.orderBy = orderBy;
            return _resultValue;
        }
    }
}
