// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class SentryIssueAlertActionsV2SlackNotifyService {
    /**
     * @return The name of the channel to send the notification to (e.g., #critical, Jane Schmidt).
     * 
     */
    private String channel;
    /**
     * @return The ID of the channel to send the notification to.
     * 
     */
    private @Nullable String channelId;
    private @Nullable String name;
    /**
     * @return Text to show alongside the notification. To {@literal @} a user, include their user id like `{@literal @}&lt;USER_ID&gt;`. To include a clickable link, format the link and title like `&lt;http://example.com|Click Here&gt;`.
     * 
     */
    private @Nullable String notes;
    /**
     * @return A string of tags to show in the notification.
     * 
     */
    private @Nullable List<String> tags;
    /**
     * @return The integration ID associated with the Slack workspace.
     * 
     */
    private String workspace;

    private SentryIssueAlertActionsV2SlackNotifyService() {}
    /**
     * @return The name of the channel to send the notification to (e.g., #critical, Jane Schmidt).
     * 
     */
    public String channel() {
        return this.channel;
    }
    /**
     * @return The ID of the channel to send the notification to.
     * 
     */
    public Optional<String> channelId() {
        return Optional.ofNullable(this.channelId);
    }
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return Text to show alongside the notification. To {@literal @} a user, include their user id like `{@literal @}&lt;USER_ID&gt;`. To include a clickable link, format the link and title like `&lt;http://example.com|Click Here&gt;`.
     * 
     */
    public Optional<String> notes() {
        return Optional.ofNullable(this.notes);
    }
    /**
     * @return A string of tags to show in the notification.
     * 
     */
    public List<String> tags() {
        return this.tags == null ? List.of() : this.tags;
    }
    /**
     * @return The integration ID associated with the Slack workspace.
     * 
     */
    public String workspace() {
        return this.workspace;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SentryIssueAlertActionsV2SlackNotifyService defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String channel;
        private @Nullable String channelId;
        private @Nullable String name;
        private @Nullable String notes;
        private @Nullable List<String> tags;
        private String workspace;
        public Builder() {}
        public Builder(SentryIssueAlertActionsV2SlackNotifyService defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.channel = defaults.channel;
    	      this.channelId = defaults.channelId;
    	      this.name = defaults.name;
    	      this.notes = defaults.notes;
    	      this.tags = defaults.tags;
    	      this.workspace = defaults.workspace;
        }

        @CustomType.Setter
        public Builder channel(String channel) {
            if (channel == null) {
              throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2SlackNotifyService", "channel");
            }
            this.channel = channel;
            return this;
        }
        @CustomType.Setter
        public Builder channelId(@Nullable String channelId) {

            this.channelId = channelId;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder notes(@Nullable String notes) {

            this.notes = notes;
            return this;
        }
        @CustomType.Setter
        public Builder tags(@Nullable List<String> tags) {

            this.tags = tags;
            return this;
        }
        public Builder tags(String... tags) {
            return tags(List.of(tags));
        }
        @CustomType.Setter
        public Builder workspace(String workspace) {
            if (workspace == null) {
              throw new MissingRequiredPropertyException("SentryIssueAlertActionsV2SlackNotifyService", "workspace");
            }
            this.workspace = workspace;
            return this;
        }
        public SentryIssueAlertActionsV2SlackNotifyService build() {
            final var _resultValue = new SentryIssueAlertActionsV2SlackNotifyService();
            _resultValue.channel = channel;
            _resultValue.channelId = channelId;
            _resultValue.name = name;
            _resultValue.notes = notes;
            _resultValue.tags = tags;
            _resultValue.workspace = workspace;
            return _resultValue;
        }
    }
}
