// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sentry.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;

@CustomType
public final class SentryDashboardWidgetLayout {
    private Integer h;
    private Integer minH;
    private Integer w;
    private Integer x;
    private Integer y;

    private SentryDashboardWidgetLayout() {}
    public Integer h() {
        return this.h;
    }
    public Integer minH() {
        return this.minH;
    }
    public Integer w() {
        return this.w;
    }
    public Integer x() {
        return this.x;
    }
    public Integer y() {
        return this.y;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SentryDashboardWidgetLayout defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer h;
        private Integer minH;
        private Integer w;
        private Integer x;
        private Integer y;
        public Builder() {}
        public Builder(SentryDashboardWidgetLayout defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.h = defaults.h;
    	      this.minH = defaults.minH;
    	      this.w = defaults.w;
    	      this.x = defaults.x;
    	      this.y = defaults.y;
        }

        @CustomType.Setter
        public Builder h(Integer h) {
            if (h == null) {
              throw new MissingRequiredPropertyException("SentryDashboardWidgetLayout", "h");
            }
            this.h = h;
            return this;
        }
        @CustomType.Setter
        public Builder minH(Integer minH) {
            if (minH == null) {
              throw new MissingRequiredPropertyException("SentryDashboardWidgetLayout", "minH");
            }
            this.minH = minH;
            return this;
        }
        @CustomType.Setter
        public Builder w(Integer w) {
            if (w == null) {
              throw new MissingRequiredPropertyException("SentryDashboardWidgetLayout", "w");
            }
            this.w = w;
            return this;
        }
        @CustomType.Setter
        public Builder x(Integer x) {
            if (x == null) {
              throw new MissingRequiredPropertyException("SentryDashboardWidgetLayout", "x");
            }
            this.x = x;
            return this;
        }
        @CustomType.Setter
        public Builder y(Integer y) {
            if (y == null) {
              throw new MissingRequiredPropertyException("SentryDashboardWidgetLayout", "y");
            }
            this.y = y;
            return this;
        }
        public SentryDashboardWidgetLayout build() {
            final var _resultValue = new SentryDashboardWidgetLayout();
            _resultValue.h = h;
            _resultValue.minH = minH;
            _resultValue.w = w;
            _resultValue.x = x;
            _resultValue.y = y;
            return _resultValue;
        }
    }
}
