// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Sentry.Inputs
{

    public sealed class SentryIssueAlertActionsV2GithubCreateTicketGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The GitHub user to assign the issue to.
        /// </summary>
        [Input("assignee")]
        public Input<string>? Assignee { get; set; }

        /// <summary>
        /// The integration ID associated with GitHub.
        /// </summary>
        [Input("integration", required: true)]
        public Input<string> Integration { get; set; } = null!;

        [Input("labels")]
        private InputList<string>? _labels;

        /// <summary>
        /// A list of labels to assign to the issue.
        /// </summary>
        public InputList<string> Labels
        {
            get => _labels ?? (_labels = new InputList<string>());
            set => _labels = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The name of the repository to create the issue in.
        /// </summary>
        [Input("repo", required: true)]
        public Input<string> Repo { get; set; } = null!;

        public SentryIssueAlertActionsV2GithubCreateTicketGetArgs()
        {
        }
        public static new SentryIssueAlertActionsV2GithubCreateTicketGetArgs Empty => new SentryIssueAlertActionsV2GithubCreateTicketGetArgs();
    }
}
