// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Sentry.Inputs
{

    public sealed class SentryIssueAlertActionsV2SlackNotifyServiceGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the channel to send the notification to (e.g., #critical, Jane Schmidt).
        /// </summary>
        [Input("channel", required: true)]
        public Input<string> Channel { get; set; } = null!;

        /// <summary>
        /// The ID of the channel to send the notification to.
        /// </summary>
        [Input("channelId")]
        public Input<string>? ChannelId { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Text to show alongside the notification. To @ a user, include their user id like `@&lt;USER_ID&gt;`. To include a clickable link, format the link and title like `&lt;http://example.com|Click Here&gt;`.
        /// </summary>
        [Input("notes")]
        public Input<string>? Notes { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// A string of tags to show in the notification.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The integration ID associated with the Slack workspace.
        /// </summary>
        [Input("workspace", required: true)]
        public Input<string> Workspace { get; set; } = null!;

        public SentryIssueAlertActionsV2SlackNotifyServiceGetArgs()
        {
        }
        public static new SentryIssueAlertActionsV2SlackNotifyServiceGetArgs Empty => new SentryIssueAlertActionsV2SlackNotifyServiceGetArgs();
    }
}
