// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Sentry.Inputs
{

    public sealed class SentryIssueAlertActionsV2MsteamsNotifyServiceGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the channel to send the notification to.
        /// </summary>
        [Input("channel", required: true)]
        public Input<string> Channel { get; set; } = null!;

        [Input("channelId")]
        public Input<string>? ChannelId { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The integration ID associated with the Microsoft Teams team.
        /// </summary>
        [Input("team", required: true)]
        public Input<string> Team { get; set; } = null!;

        public SentryIssueAlertActionsV2MsteamsNotifyServiceGetArgs()
        {
        }
        public static new SentryIssueAlertActionsV2MsteamsNotifyServiceGetArgs Empty => new SentryIssueAlertActionsV2MsteamsNotifyServiceGetArgs();
    }
}
