// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Sentry.Inputs
{

    public sealed class SentryIssueAlertFiltersV2Args : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The issue is older or newer than `value` `time`.
        /// </summary>
        [Input("ageComparison")]
        public Input<Inputs.SentryIssueAlertFiltersV2AgeComparisonArgs>? AgeComparison { get; set; }

        /// <summary>
        /// The issue is assigned to no one, team, or member.
        /// </summary>
        [Input("assignedTo")]
        public Input<Inputs.SentryIssueAlertFiltersV2AssignedToArgs>? AssignedTo { get; set; }

        /// <summary>
        /// The event's `attribute` value `match` `value`.
        /// </summary>
        [Input("eventAttribute")]
        public Input<Inputs.SentryIssueAlertFiltersV2EventAttributeArgs>? EventAttribute { get; set; }

        /// <summary>
        /// The issue's category is equal to `value`.
        /// </summary>
        [Input("issueCategory")]
        public Input<Inputs.SentryIssueAlertFiltersV2IssueCategoryArgs>? IssueCategory { get; set; }

        /// <summary>
        /// The issue has happened at least `value` times (Note: this is approximate).
        /// </summary>
        [Input("issueOccurrences")]
        public Input<Inputs.SentryIssueAlertFiltersV2IssueOccurrencesArgs>? IssueOccurrences { get; set; }

        /// <summary>
        /// The {oldest*or*newest} adopted release associated with the event's issue is {older*or*newer} than the latest adopted release in {environment}.
        /// </summary>
        [Input("latestAdoptedRelease")]
        public Input<Inputs.SentryIssueAlertFiltersV2LatestAdoptedReleaseArgs>? LatestAdoptedRelease { get; set; }

        /// <summary>
        /// The event is from the latest release.
        /// </summary>
        [Input("latestRelease")]
        public Input<Inputs.SentryIssueAlertFiltersV2LatestReleaseArgs>? LatestRelease { get; set; }

        /// <summary>
        /// The event's level is `match` `level`.
        /// </summary>
        [Input("level")]
        public Input<Inputs.SentryIssueAlertFiltersV2LevelArgs>? Level { get; set; }

        /// <summary>
        /// The event's tags match `key` `match` `value`.
        /// </summary>
        [Input("taggedEvent")]
        public Input<Inputs.SentryIssueAlertFiltersV2TaggedEventArgs>? TaggedEvent { get; set; }

        public SentryIssueAlertFiltersV2Args()
        {
        }
        public static new SentryIssueAlertFiltersV2Args Empty => new SentryIssueAlertFiltersV2Args();
    }
}
