// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Sentry.Inputs
{

    public sealed class SentryKeyJavascriptLoaderScriptArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The version of the browser SDK to load.
        /// </summary>
        [Input("browserSdkVersion")]
        public Input<string>? BrowserSdkVersion { get; set; }

        /// <summary>
        /// Whether debug bundles &amp; logging are enabled for this key.
        /// </summary>
        [Input("debugEnabled")]
        public Input<bool>? DebugEnabled { get; set; }

        /// <summary>
        /// Whether performance monitoring is enabled for this key.
        /// </summary>
        [Input("performanceMonitoringEnabled")]
        public Input<bool>? PerformanceMonitoringEnabled { get; set; }

        /// <summary>
        /// Whether session replay is enabled for this key.
        /// </summary>
        [Input("sessionReplayEnabled")]
        public Input<bool>? SessionReplayEnabled { get; set; }

        public SentryKeyJavascriptLoaderScriptArgs()
        {
        }
        public static new SentryKeyJavascriptLoaderScriptArgs Empty => new SentryKeyJavascriptLoaderScriptArgs();
    }
}
