// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Sentry.Inputs
{

    public sealed class SentryIssueAlertActionsV2PagerdutyNotifyServiceArgs : global::Pulumi.ResourceArgs
    {
        [Input("account", required: true)]
        public Input<string> Account { get; set; } = null!;

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("service", required: true)]
        public Input<string> Service { get; set; } = null!;

        [Input("severity", required: true)]
        public Input<string> Severity { get; set; } = null!;

        public SentryIssueAlertActionsV2PagerdutyNotifyServiceArgs()
        {
        }
        public static new SentryIssueAlertActionsV2PagerdutyNotifyServiceArgs Empty => new SentryIssueAlertActionsV2PagerdutyNotifyServiceArgs();
    }
}
