// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Sentry.Inputs
{

    public sealed class SentryIssueAlertFiltersV2GetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The issue is older or newer than `value` `time`.
        /// </summary>
        [Input("ageComparison")]
        public Input<Inputs.SentryIssueAlertFiltersV2AgeComparisonGetArgs>? AgeComparison { get; set; }

        /// <summary>
        /// The issue is assigned to no one, team, or member.
        /// </summary>
        [Input("assignedTo")]
        public Input<Inputs.SentryIssueAlertFiltersV2AssignedToGetArgs>? AssignedTo { get; set; }

        /// <summary>
        /// The event's `attribute` value `match` `value`.
        /// </summary>
        [Input("eventAttribute")]
        public Input<Inputs.SentryIssueAlertFiltersV2EventAttributeGetArgs>? EventAttribute { get; set; }

        /// <summary>
        /// The issue's category is equal to `value`.
        /// </summary>
        [Input("issueCategory")]
        public Input<Inputs.SentryIssueAlertFiltersV2IssueCategoryGetArgs>? IssueCategory { get; set; }

        /// <summary>
        /// The issue has happened at least `value` times (Note: this is approximate).
        /// </summary>
        [Input("issueOccurrences")]
        public Input<Inputs.SentryIssueAlertFiltersV2IssueOccurrencesGetArgs>? IssueOccurrences { get; set; }

        /// <summary>
        /// The {oldest*or*newest} adopted release associated with the event's issue is {older*or*newer} than the latest adopted release in {environment}.
        /// </summary>
        [Input("latestAdoptedRelease")]
        public Input<Inputs.SentryIssueAlertFiltersV2LatestAdoptedReleaseGetArgs>? LatestAdoptedRelease { get; set; }

        /// <summary>
        /// The event is from the latest release.
        /// </summary>
        [Input("latestRelease")]
        public Input<Inputs.SentryIssueAlertFiltersV2LatestReleaseGetArgs>? LatestRelease { get; set; }

        /// <summary>
        /// The event's level is `match` `level`.
        /// </summary>
        [Input("level")]
        public Input<Inputs.SentryIssueAlertFiltersV2LevelGetArgs>? Level { get; set; }

        /// <summary>
        /// The event's tags match `key` `match` `value`.
        /// </summary>
        [Input("taggedEvent")]
        public Input<Inputs.SentryIssueAlertFiltersV2TaggedEventGetArgs>? TaggedEvent { get; set; }

        public SentryIssueAlertFiltersV2GetArgs()
        {
        }
        public static new SentryIssueAlertFiltersV2GetArgs Empty => new SentryIssueAlertFiltersV2GetArgs();
    }
}
