"use strict";
// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getSentryAllOrganizationMembersOutput = exports.getSentryAllOrganizationMembers = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("./utilities");
/**
 * Retrieve all organization members.
 */
function getSentryAllOrganizationMembers(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sentry:index/getSentryAllOrganizationMembers:getSentryAllOrganizationMembers", {
        "organization": args.organization,
    }, opts);
}
exports.getSentryAllOrganizationMembers = getSentryAllOrganizationMembers;
/**
 * Retrieve all organization members.
 */
function getSentryAllOrganizationMembersOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("sentry:index/getSentryAllOrganizationMembers:getSentryAllOrganizationMembers", {
        "organization": args.organization,
    }, opts);
}
exports.getSentryAllOrganizationMembersOutput = getSentryAllOrganizationMembersOutput;
