"use strict";
// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getSentryKeyOutput = exports.getSentryKey = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("./utilities");
/**
 * Retrieve a Project's Client Key.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sentry from "@pulumi/sentry";
 *
 * const default = sentry.getSentryKey({
 *     name: "Default",
 *     organization: "my-organization",
 *     project: "web-app",
 * });
 * const first = sentry.getSentryKey({
 *     first: true,
 *     organization: "my-organization",
 *     project: "web-app",
 * });
 * ```
 */
function getSentryKey(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sentry:index/getSentryKey:getSentryKey", {
        "first": args.first,
        "id": args.id,
        "name": args.name,
        "organization": args.organization,
        "project": args.project,
    }, opts);
}
exports.getSentryKey = getSentryKey;
/**
 * Retrieve a Project's Client Key.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sentry from "@pulumi/sentry";
 *
 * const default = sentry.getSentryKey({
 *     name: "Default",
 *     organization: "my-organization",
 *     project: "web-app",
 * });
 * const first = sentry.getSentryKey({
 *     first: true,
 *     organization: "my-organization",
 *     project: "web-app",
 * });
 * ```
 */
function getSentryKeyOutput(args, opts) {
    return pulumi.output(args).apply((a) => getSentryKey(a, opts));
}
exports.getSentryKeyOutput = getSentryKeyOutput;
//# sourceMappingURL=getSentryKey.js.map