"use strict";
// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getSentryProjectOutput = exports.getSentryProject = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("./utilities");
/**
 * Return a list of projects available to the authenticated session.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sentry from "@pulumi/sentry";
 *
 * const default = sentry.getSentryProject({
 *     organization: "my-organization",
 *     slug: "my-project",
 * });
 * ```
 */
function getSentryProject(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sentry:index/getSentryProject:getSentryProject", {
        "organization": args.organization,
        "slug": args.slug,
    }, opts);
}
exports.getSentryProject = getSentryProject;
/**
 * Return a list of projects available to the authenticated session.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sentry from "@pulumi/sentry";
 *
 * const default = sentry.getSentryProject({
 *     organization: "my-organization",
 *     slug: "my-project",
 * });
 * ```
 */
function getSentryProjectOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("sentry:index/getSentryProject:getSentryProject", {
        "organization": args.organization,
        "slug": args.slug,
    }, opts);
}
exports.getSentryProjectOutput = getSentryProjectOutput;
