// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Sentry Issue Alert data source. See the [Sentry documentation](https://docs.sentry.io/api/alerts/retrieve-an-issue-alert-rule-for-a-project/) for more information.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sentry from "@pulumi/sentry";
 *
 * // Retrieve an Issue Alert
 * const original = sentry.getSentryIssueAlert({
 *     organization: "my-organization",
 *     project: "my-project",
 *     id: "42",
 * });
 * ```
 */
export function getSentryIssueAlert(args: GetSentryIssueAlertArgs, opts?: pulumi.InvokeOptions): Promise<GetSentryIssueAlertResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sentry:index/getSentryIssueAlert:getSentryIssueAlert", {
        "id": args.id,
        "organization": args.organization,
        "project": args.project,
    }, opts);
}

/**
 * A collection of arguments for invoking getSentryIssueAlert.
 */
export interface GetSentryIssueAlertArgs {
    /**
     * The ID of this resource.
     */
    id: string;
    /**
     * The organization the resource belongs to.
     */
    organization: string;
    /**
     * The project the resource belongs to.
     */
    project: string;
}

/**
 * A collection of values returned by getSentryIssueAlert.
 */
export interface GetSentryIssueAlertResult {
    /**
     * Trigger actions when an event is captured by Sentry and `any` or `all` of the specified conditions happen.
     */
    readonly actionMatch: string;
    /**
     * List of actions. In JSON string format.
     */
    readonly actions: string;
    /**
     * A list of actions that take place when all required conditions and filters for the rule are met.
     */
    readonly actionsV2s: outputs.GetSentryIssueAlertActionsV2[];
    /**
     * List of conditions. In JSON string format.
     */
    readonly conditions: string;
    /**
     * A list of triggers that determine when the rule fires.
     */
    readonly conditionsV2s: outputs.GetSentryIssueAlertConditionsV2[];
    /**
     * Perform issue alert in a specific environment.
     */
    readonly environment: string;
    /**
     * A string determining which filters need to be true before any actions take place. Required when a value is provided for `filters`.
     */
    readonly filterMatch: string;
    /**
     * A list of filters that determine if a rule fires after the necessary conditions have been met. In JSON string format.
     */
    readonly filters: string;
    /**
     * A list of filters that determine if a rule fires after the necessary conditions have been met.
     */
    readonly filtersV2s: outputs.GetSentryIssueAlertFiltersV2[];
    /**
     * Perform actions at most once every `X` minutes for this issue.
     */
    readonly frequency: number;
    /**
     * The ID of this resource.
     */
    readonly id: string;
    /**
     * The issue alert name.
     */
    readonly name: string;
    /**
     * The organization the resource belongs to.
     */
    readonly organization: string;
    /**
     * The ID of the team or user that owns the rule.
     */
    readonly owner: string;
    /**
     * The project the resource belongs to.
     */
    readonly project: string;
}
/**
 * Sentry Issue Alert data source. See the [Sentry documentation](https://docs.sentry.io/api/alerts/retrieve-an-issue-alert-rule-for-a-project/) for more information.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sentry from "@pulumi/sentry";
 *
 * // Retrieve an Issue Alert
 * const original = sentry.getSentryIssueAlert({
 *     organization: "my-organization",
 *     project: "my-project",
 *     id: "42",
 * });
 * ```
 */
export function getSentryIssueAlertOutput(args: GetSentryIssueAlertOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetSentryIssueAlertResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("sentry:index/getSentryIssueAlert:getSentryIssueAlert", {
        "id": args.id,
        "organization": args.organization,
        "project": args.project,
    }, opts);
}

/**
 * A collection of arguments for invoking getSentryIssueAlert.
 */
export interface GetSentryIssueAlertOutputArgs {
    /**
     * The ID of this resource.
     */
    id: pulumi.Input<string>;
    /**
     * The organization the resource belongs to.
     */
    organization: pulumi.Input<string>;
    /**
     * The project the resource belongs to.
     */
    project: pulumi.Input<string>;
}
